/* Folio changelog — shown on the Mission page, grouped by day (newest first).
   Each entry: { d: "YYYY-MM-DD" (sort key), label: optional display override, t: day title, items: ["…"] }.
   POLICY: whenever a user-requested change ships to the live site, append a one-line summary to TODAY's
   entry (create it if missing). Keep items short, plain-English, and reader-facing (what changed for the
   user, not how). Loaded before app.js. */
window.CHANGELOG = [
  {
    d: "2026-08-02",
    t: "Every glossary term now lists its sources",
    items: [
      "Two hundred and sixty-seven more glossary terms now list the works behind them and point at them sentence by sentence. Reading each term against those works turned up ninety-five that overstated or misremembered something: fifty-five population counts several years out of date, one of them by seven years and three too high rather than too low, a distance nobody could source, a much-repeated story about a historian's punishment that his own surviving letter tells rather differently, how much of Antarctica is actually bare rock, the size of the Pacific and the depth of its deepest point, the year the Fertile Crescent was given its name \u2014 which turns out to be two years earlier than everybody says \u2014 the height of Etna, where the map that first called a continent America was really printed, what the British actually burned in Washington in 1814, who William Henry Harrison was really fighting at the Thames, how many southern states actually left the Union when Lincoln was elected, whether Rutherford B. Hayes really struck a bargain to become president, which president gave the country a single national budget \u2014 one had the idea and Congress refused him, the other signed it into law \u2014 what Djibouti was called when it became independent, how big Senegal, Fiji, Panama, Ecuador, Switzerland, Iraq and Nepal are, and which job Eisenhower actually held on D-Day, the title the term gave him being one he did not receive until six years later. All are corrected, in every language. Thirty entries on American presidents also gained the record that states outright which number president each was and the exact days he held office \u2014 which nothing cited for them had actually said. All thirty turned out to be right. Every American president now lists the works behind his entry. A hundred and ninety-seven country entries follow, every country in the world \u2014 among them the Vatican, which is a little smaller than the entry said, on the word of its own government. Every area and population figure in twenty-five European entries was checked against two official records and every one held \u2014 on three of them the second record was what showed the entry had been right all along. The Chinese of five entries, which ran to four sentences where the English runs to three, has been brought back into line. With these, every one of the 333 glossary terms now lists the works behind it.",
      "The home page now counts your day the way Anki does: how many cards are new, how many you are still learning, and how many are due for review, in blue, red and green — with the same three numbers beside every deck you have added, and the button lined up with them. Each added deck now sits on a single line — its counts, its name and how far through it you are, side by side instead of stacked with space around them. The big gold number on the daily review is that day's total rather than your level, and becomes a tick once you have cleared it; your level is written just underneath. On a phone the page is one column: the daily review, then the five minigames under a centred heading of their own, three across; a small blue “Add decks” tab hangs off the review for the Library, with a quiet “About Folio” line, given room to breathe, at the foot, now that both have left the bar at the bottom of the screen. The card and term of the day are no longer shown there — they are still on a computer. The map game is now called simply “Find it”. “Chrono” now reads “Ordered”, and the daily quote keeps its height when you turn it over to its original language, so nothing below it jumps.",
      "The pen for drawing on a card is easier to use on a phone. It no longer sits on top of the bar along the bottom of the screen; the three sizes are the pen itself, so tapping the size you are using puts it away; Mark sits beside them; and a colour of your own is chosen in an ordinary colour picker inside the tools — a shade square with a hue bar under it — rather than your phone's full-screen colour dialog, and is remembered. Show answer, the grade buttons and the row beneath them can be tapped with the pen down instead of being covered by the drawing layer. Starting a card no longer opens the keyboard by itself. The grade buttons themselves can now be dragged by their top edge to half their height, at which point the four of them sit side by side as plain colours with the \u201c?\u201d, Undo and Suspend as icons beside them \u2014 the whole bar in half the room, and it opens the way you left it. Settings has a Text size of small, medium or large, which sets how large the text you read is: a card's question and background, a glossary popup, a place on the Atlas. And on the Atlas a place's panel can be dragged taller or shorter by its top edge, and opens at the height you left it.",
    ],
  },
  {
    d: "2026-08-01",
    t: "Every card, sourced",
    items: [
      "Glossary popups now carry the same small numbers as the cards. Where a term lists its sources, each sentence points at the works it rests on, so you can see which one carries the date and which the measurement instead of being handed a list and left to guess. Clicking a number opens the list on that entry. Every sourced term has them, in every language.",
"The list of sources in a glossary popup now starts closed, and starts closed again each time you open another term. A popup is a quick look at one word, and its sources were taking up a third of it; open the list whenever you want it. The list at the foot of a card is unchanged, and still opens by itself.",
      "On a phone every page — Home, Atlas, About, your account, Settings, and the editor for those who have one — now sits in a bar along the bottom of the screen, named, within reach of a thumb. They were icons without labels at the top, in a strip of nine that had to be scrolled sideways to reach the last of them. The Library is reached from a banner of its own on the home page instead, under the review and the decks it belongs beside. The top bar has gone from phones altogether: light and dark, and the language you read in, now live on the Settings page, where they are easy to find on any screen.",
      "The home page on a phone is now three screens side by side instead of one long column. It opens on the daily review, as it always did; swipe left for the games, right for the day's card and glossary term, with dots underneath saying where you are. The Atlas panel has gone from the phone's home page — the Atlas has a button of its own along the bottom — and the review no longer shows a Seen total, since the bar just above it already counts the cards you have studied. The name under the page you are on at the bottom of the screen now sits straight under its icon again.",
      "The Atlas is easier to use on a phone: the search box and the layer list no longer cover the map, but sit as two small buttons in the corner and open when tapped; the timeline has a row of its own, so the years along it are readable instead of piling into an unreadable smudge; and the grade buttons while studying now fit on one row instead of taking a quarter of the screen.",
      "Small things across the site: the Library no longer shows a level and a progress bar on collections that have nothing in them yet, the Settings and Account pages use the whole width of the screen rather than leaving half of it empty, the card of the day says which deck it comes from, the “?” beside the grade buttons now lists the keyboard shortcuts — including the new one for taking a grade back, a glossary popup on a phone no longer blinks out for an instant just as it finishes sliding up, a coming-soon collection's title now sits in the middle of its banner, the editor's button on a phone has moved from the bottom bar to the top right of the home page — and to the top right of a card you are studying, where it opens that card, and the Atlas has lost the Copy link button on a place — links already shared still open where they always did.",
      "The pen for drawing on a card can now be dragged anywhere on the screen, on a phone as well as a computer, and stays where you leave it — including on the Atlas. Its colours and tools open on whichever side of it there is room for them, and putting them away no longer lifts the pen: you keep drawing with the panel out of the way, and stop by unselecting Draw, Mark or Erase inside it.",
      "A picture or video whose link has gone dead no longer leaves a grey hole in the middle of a card. Readers simply don’t see it; in the editor it stays, marked, so it can be fixed.",
      "On a phone, a place's panel on the Atlas is now read by swiping sideways through its parts — the description, the year, the figures, the sources — instead of scrolling down past all of them, and it always opens on the description. Dots under the panel say how many parts there are and take you straight to one. A firm swipe moves one part at a time, so a quick flick can no longer carry past the year and skip it, and the mark for a place you are opening for the first time now sits beside its name rather than on a line of its own.",
      "On the Atlas, city dots and their names now appear and disappear together. The names waited for the globe to settle while the dots stayed put, so turning or zooming left a scatter of unnamed markers.",
      "While studying you can now go back a card and take back the answer you gave it, with a button beside Exit or Ctrl+Z on a keyboard. The card returns with its answer showing, ready to be answered again, and its schedule goes back to what it was. On a phone that button sits with the grade buttons at the bottom of the screen, beside the “?”, rather than at the top of a card that runs several screens.",
      "Writing a card is less fiddly: a card's sources are now edited the way they read, italics and all, instead of as HTML tags in a text box, and the picture and video boxes have become one box that works out for itself whether the link you pasted is a picture or a clip.",
      "The formatting toolbar in the card editor now follows you down the page and stays just below the menu bar, so it is still within reach in the middle of a long background. It has also gained a +Source button, which drops a footnote marker where you are writing and opens a fresh citation line for it.",
      "The citation pass is finished: all 109 cards in the World History prehistory deck now show their sources, and every one meets the bar of five. Where the paper announcing a find sits behind a paywall, what usually opened it was the body responsible for the thing itself — a museum catalogue, a culture ministry's portal, the foundation that runs a dig. Checking the cards against those sources produced a long run of corrections, mostly dates and counts: several ages turned out to be raw radiocarbon readings presented as calendar years, and a number of figures appear in nothing that can be read openly and were dropped rather than left standing. The glossary is now doing the same, and 66 terms list at least two sources each, which finishes its prehistory section. Checking those turned up corrections of its own — the man usually said to have invented the three-age system called it an old idea himself, the oldest known stone tools were described as being struck the wrong way round, and figures already put right on a card were found still standing in the glossary — and settled where the Stone Age begins, which the glossary and the cards had been answering differently.",
    ],
  },
  {
    d: "2026-07-31",
    t: "Where it comes from",
    items: [
      "Cards in the World History prehistory deck began showing their sources, and the deck is now held to a minimum of five each; 96 of the 109 were done on the day. At the foot of a card there is now a numbered Sources list, with small numbers in the text pointing at the work behind each claim, and every entry says whether it is free to read or behind a paywall. Checking each card against its sources produced 172 corrections — mostly dates, counts and measurements, along with a number of claims that appear in nothing openly readable and were dropped rather than left standing. Where a card's sources genuinely cannot be found or opened, that is now recorded rather than quietly left blank.",
      "On a narrow phone screen, a card carrying sources was sometimes laid out wider than the card itself, so the right-hand edge of the answer, the background text and everything else on the back was cut off and could not be read. A long web address in a citation was pushing the whole card wide; those addresses now wrap, and the back of a card always fits the screen it is read on.",
      "The small numbers in a card's text that point at its sources are now the same red as the answer term, so they can no longer be mistaken for a glossary term you have not opened yet.",
      "Switching the site language while a card's answer is showing no longer snaps it shut — the card stays turned over, sources and all, in the language you just chose.",
      "On some devices the Sources list at the foot of a card would not open when tapped, the small numbers pointing into it showed as blank gaps, and the citations came out as plain text with the web address neither coloured nor clickable. All three now work wherever a card, a glossary term or an Atlas place is shown. The list also opens by itself from now on, since a source you have to go looking for is one you will never check — close it and Folio will keep it closed until you open it again.",
    ],
  },
  {
    d: "2026-07-30",
    t: "After the ice",
    items: [
      "Glossary terms you have not opened yet now stand out in the same gold as the blank in a card's question, and turn back to ordinary blue once you have read them. Opening a term or an Atlas place for the first time sets off a small gold burst with your running count and a chime, so a glance tells you how much is left to discover.",
      "Four new badges for the reading you do around the cards: opening 25 and 100 glossary terms, and 50 and then every one of the world's present-day countries on the Atlas.",
      "The Beyond the cards panel on your account page now counts the countries you have opened on the Atlas against the world's 258, instead of also counting territories from the historical maps, which could push the figure past its own total. Those older territories now have a count of their own.",
      "Cards can now ask their question in more than one way. Each card may carry several phrasings of the same question, official cards will carry three, and the study page picks one at random each time, so you learn the idea itself rather than the shape of one sentence. If you write your own decks, arrows beside the question box let you add and edit up to ten phrasings per card.",
      "Two extra ways of asking the question added to 105 cards in the World History prehistory deck, in all ten site languages.",
      "Eleven new cards in the World History prehistory deck, in all ten site languages.",
      "The Feedback tab on the Edit page now shows in red rather than grey, matching the coloured tabs beside it.",
      "In the card editor, the controls for a card's extra ways of asking now say question instead of phrasing.",
      "On a phone, the Timeline tab of the Edit page no longer cuts off partway down: the list of eras now runs the full length of the page and scrolls with it.",
      "The menu bar now shows each page as an icon: point at one and its name unfolds beside it, and the page you are on keeps its name showing.",
      "Studying the Card of the day now asks you the very question you saw on the tile, rather than another of the card's phrasings.",
      "The Atlas tile on the home page now introduces itself in one short line.",
      "Refreshing the browser on the Edit page now keeps you there instead of dropping you back on the home page.",
      "The light-and-dark switch in the menu bar is now slimmer, and the coloured line marking the page you are on underlines its name alone rather than running under the icon too.",
      "The Clay and Garden themes have been retired from Settings; if you had one of them on, Folio returns to its default look.",
      "The decks you add to the Daily review now share the tile's colouring: its bronze edge and wash run down the list, which turns bronze — or gold on a perfect day — along with the tile once today's cards are cleared.",
      "Cards, glossary popups and Atlas place panels can now carry footnotes. A Sources list folds open at the foot of each, and the small numbers in the text jump to the work a particular claim comes from. Nothing has been cited yet, so the list stays out of sight until a card or term has its sources written.",
    ],
  },
  {
    d: "2026-07-29",
    t: "Video on your cards",
    items: [
      "The place panel in the Atlas now folds: the description, the year paragraph and the figures each open and shut on their own, and a part with nothing to show starts closed instead of taking up the panel with a dash. On a phone, opening a new place also starts you at the top of its panel rather than wherever you had scrolled to in the last one.",
      "Clicking a country on the present-day Atlas map lights it up again. The gold highlight had stopped being drawn on that map, so a country you picked stayed exactly as it looked before; the historical maps were unaffected.",
      "The Card of the day on the home page now opens that one card when you press Study this card. Grade it and the card joins your daily review on its own, without its whole deck coming with it: the cards you pick up this way gather under Card of the Day additions below the review tile, and you can clear the lot whenever you like.",
      "Every deck in the daily review list now shows how far through it you are, as a bar reading how many of its cards you have studied. It takes the place of the dot that used to sit beside the name.",
      "The quote on the home page now moves between voices: the same writer never appears two days running, and never more than twice in one week.",
      "The Daily review tile on the home page now has a colour of its own: a bronze edge and wash while today's cards are still waiting, a full bronze fill once you have cleared them, and shining gold when every card came back right on the first try. Its level bar is gold as well, so it no longer reads as one more deck progress bar.",
      "You can now write to the people who make Folio without leaving the site: there is a message box at the foot of the About page for a wrong date, something broken, an idea, or anything else you want to say while Folio is in beta. It needs no account, and every message goes straight to the editors.",
      "Cards and glossary terms can now show a video in place of a picture. Paste a YouTube or Vimeo link, or a link straight to a video file, and it plays inside the card in the same frame a picture would have used, with a button in the corner to open it full screen. A card shows one or the other, never both. Anyone writing their own deck can add videos to their cards and terms the same way. Videos are linked rather than uploaded, so the file stays wherever it already lives.",
      "Adding a picture or a video to a card or a glossary term now asks where it came from. Until you give a source it is not saved: the panel says so plainly, and a small box asks you for the credit, so nothing on Folio can go out uncredited.",
      "Your account page now shows statistics for one deck at a time — pick a deck to see how far through it you are, how much of it has settled into long-term memory and what it owes you today. A new Beyond the cards panel sits beside it, counting the glossary terms you have opened, the places you have looked up in the Atlas, your longest run of study days and how the daily games have gone.",
      "Sixteen new cards in the World History prehistory deck, in all ten site languages.",
    ],
  },
  {
    d: "2026-07-28",
    t: "Who said it? in your language",
    items: [
      "Thirty-two more cards in the World History deck, in all ten site languages.",
      "A question in the World History deck has been rewritten to read more clearly.",
      "Who said it? and True or False are now fully in your language — the quotation or statement, the four names you choose between, the category, the explanation that follows and the result line after each answer. Famous lines use the wording they are actually known by in each language. Every daily game now reads in all ten site languages.",
      "Dates now read in your language across the site: the years under a deck title, the lifespans and reigns on glossary terms, and the spans on the Atlas country panel. Eras are written the way each language writes them — n. Chr., av. J.-C., 公元前 — and ages in deep time are spelled out rather than left as Mya.",
      "The Atlas globe now reads in your language at every year on the timeline: present-day countries, the empires, colonies and old kingdoms of the historical maps, the map's own descriptions of the peoples who lived beyond them, and capital cities under the names they went by at the time — Constantinople, Peking, Saigon, Edo. Country names follow you everywhere — on the map itself, in the name that follows your cursor, and in the home-location picker in Settings. That completes the Atlas: zoom in at any year, in any of the ten languages, and the map speaks it.",
      "These release notes now read in your language too, every day of them back to the first, and the date beside each day follows your language as well. Days that listed the same kind of change over and over — a run of new-card lines, or a string of separate \"now in your language\" notes — are now single lines carrying the whole story.",
      "The historical maps in the Atlas now turn as smoothly as the present-day one. The older years used to stutter badly while you dragged or zoomed, and could bring the browser to a halt once you had clicked an empire; they now draw at the same speed as the map of today.",
      "The Atlas map of 1900 was missing the Ottoman Empire and Greece, leaving a blank stretch from the southern Balkans across Turkey, the Middle East and Libya. Both are now on the map, and clicking either one opens its description as usual.",
      "Click the daily quote on the home page and it turns into the original: the words, the speaker's name and the source in the language they were written in, whether that is classical Chinese, Latin or Greek. Click again to come back to your own language, and the two now fade gently into one another instead of cutting. A few quotes stay as they are, either because they were written in English or because the original wording could not be confirmed.",
      "When the Gloss of the day on the home page has a picture, it now fills the right-hand side of the tile as a portrait. In a term's own panel the picture now sits in the top-right corner with the opening sentences running beside it: it is always the same height and never wider than half the panel.",
      "Card questions are now about a third shorter — one tight clue instead of a paragraph — in all ten site languages.",
    ],
  },
  {
    d: "2026-07-27",
    t: "Write your own decks",
    items: [
      "More of Folio now reads in your language: collection and deck names everywhere they appear — the Library, the bar above a study session, your daily review list, your profile's progress lists and the level-up message — the whole Atlas, from its welcome guide and search box to the year labels and the country panel's controls, the Shared decks pages, the \"Your decks\" section of the Library, the deck Studio, the Find it on the map scoreboard, the Sound effects setting, and the source line under the daily quote. Browser tabs, bookmarks and shared links carry the page name in your language too, instead of always in English.",
      "Fixed the About page walkthrough, which was showing a mix of English and your own language instead of translating properly.",
      "Twenty new cards in the World History deck, in all ten site languages.",
      "Badges you've earned now stand out in gold on your profile, so a glance tells you which ones you have and which are still locked.",
      "Your study history chart now starts on the day you made your account, instead of always showing a full year with months of blank squares before you joined.",
      "The Ancient Greece level badge now shows the plain Greek letter, without the small mark after it.",
      "Cards can now be dated in deep time — millions or thousands of years ago — so prehistory cards sort and appear in the right order rather than being pinned to the year they were discovered.",
      "Signing in to a brand-new account now starts you at level 1 with no badges, instead of showing the levels, badges and streak from the account you were using before on the same device. Study history you built up before you ever made an account still comes with you into your first account, as it always did.",
      "The Atlas welcome note now warns that historical borders are rough estimates and shouldn't be read as exact.",
      "New readers now start with three new cards a day instead of five. You can still change it in Settings.",
      "Folio now speaks Japanese. Pick 日本語 from the language menu and the whole site is in Japanese — buttons, pages, the About guide, the daily quotes, all 30 cards of the World History deck, written as Japanese rather than translated word for word, and a three-sentence Japanese explanation on all 333 glossary terms.",
      "Switching to a language other than English is much quicker now, and uses far less data: your device only downloads the language you are actually reading, instead of all of them at once.",
      "The daily quote on the home page now says where the words come from — the work and chapter — in small type under the speaker's name.",
      "Badges on your profile now turn over when you click them, showing on the back what you have to do to earn each one. Click again to turn it back.",
      "Glossary terms can now carry a picture. It sits at the bottom of the term's popup and opens full screen when you click it, just like the picture on a card.",
      "Shared decks can now be rated out of five, with a short review if you want to leave one. You can only rate a deck once you've actually studied a few of its cards, and the list sorts by rating in a way that doesn't let a single glowing review beat a deck with fifty good ones.",
      "Decks an editor has read and vouched for now carry a Staff pick mark, and you can filter the list down to just those.",
      "A deck page now shows more decks by the same author, and a deck you duplicated says what it was based on.",
      "A deck you write can now have its own glossary. Add your terms in the Studio and they underline themselves wherever they appear in that deck's backgrounds, exactly like Folio's do — and only inside your deck. You can choose whether a deck uses Folio's glossary, only your own terms, or both.",
      "You can now share a deck you've written with everyone else. Publish it from the Studio and it appears under \"Browse shared decks\", where anyone can read what it covers, flip through a sample card and add it to their own collection.",
      "Decks you install from other people update when their author improves them, and your progress on the cards that didn't change is kept.",
      "Every shared deck has a Report button if something is wrong with it.",
      "You can now write your own decks of flashcards. There's a new Studio — find it under \"Your decks\" at the bottom of the Library — where you can add cards, write the question, answer, date and background, and put them in the order you want.",
      "Your own decks study exactly like Folio's: add one to your daily review, and it turns up alongside everything else with the same spacing and the same level badge.",
      "Share a deck by exporting it to a file, which anyone can bring in with Import. Your decks stay on your own device until you do.",
      "Tightened the site's security settings, so the browser now refuses to run anything Folio didn't ship itself.",
    ],
  },
  {
    d: "2026-07-26",
    t: "The first toolmakers",
    items: [
      "On phones, the Atlas country panel is now half as tall, so it covers much less of the globe.",
      "Sixteen new cards in the World History prehistory deck, in English and all eight site languages.",
      "Corrected the age given for a fossil boy on one prehistory card, in every language.",
      "Eighty more glossary terms, in English and all eight site languages: one for every president of the United States, with the years they lived and held office, plus the earliest human ancestors and the places their fossils and tools come from, and the ice ages, the geological timescale and how the world is divided up.",
      "Folio now opens far faster. The Atlas's maps used to download on every page, even if you never opened it; now they load only when you go there, and everything else arrives in about an eighth of the data it used to take.",
      "Folio can be installed to your home screen, and once you've visited it works without a connection.",
      "A new Review statistics panel on your account page: a year-long map of the days you studied, how much of what you've learned you're holding on to, and what's due over the next two weeks.",
      "The Library now leads with what's ready to study and shows how many cards each collection holds; the subjects still being written are tucked behind a \"Coming soon\" heading you can open.",
      "You can now link straight to Folio in a particular language by adding ?lang= to the address — ?lang=es for Spanish, ?lang=zh for Chinese, and so on.",
      "Browser tabs, bookmarks and shared links now name the page you're actually on instead of always saying \"Folio\".",
      "If your device is set to reduce motion, the page no longer scrolls smoothly and the Atlas jumps straight to a searched place rather than flying there.",
    ],
  },
  {
    d: "2026-07-25",
    t: "A glossary that speaks eight languages",
    items: [
      "The glossary is being rebuilt from the ground up, and every new term now carries a pop-up definition translated into all eight site languages — so switching Folio to Spanish, Chinese, Arabic or any other language translates the glossary too. A first set of foundational terms on deep prehistory has landed.",
      "One new card in the World History prehistory deck, in English and all eight site languages.",
      "237 more glossary terms, in English and all eight site languages: the world's continents, regions and major countries, then one for every country in Europe, Asia, Africa, Oceania and the Americas — every country in the world now has a glossary entry.",
    ],
  },
  {
    d: "2026-07-24",
    t: "The world of 1500, and a more readable Atlas",
    items: [
      "The Atlas timeline now reaches back to 1500 — the world on the eve of the modern age, with the Ming, the Ottomans, the Aztec and Inca empires, and over 140 states and peoples drawn on the globe. Each comes with a researched description, the years it existed, a note on what was happening there in 1500, and 69 period-accurate capitals — Tenochtitlan, Vijayanagara, Constantinople and the rest.",
      "Historical maps finally name their states: switch on \"Country names\" in any year and the territories label themselves — empires in larger type, small states appearing as you zoom. Hovering anywhere also shows what's under your cursor, with its empire when it belongs to one.",
      "You can now search the Atlas. Type any country, historical territory or capital — Ottoman Empire, Tenochtitlan, Kalmar Union — and the globe flies there, jumping the timeline to the right era and opening the info card.",
      "The timeline is easier to use: the mapped centuries now spread across most of the rail instead of crowding the right edge, every map-year tick is clickable and names its era, and a plate title above the globe always shows which year you're looking at.",
      "The globe itself got a quiet polish — a soft shading toward the edge and a faint atmospheric glow, so it reads as a sphere rather than a flat disk.",
      "The Atlas also loads faster: two data files for long-removed map layers (about 1.7 MB) no longer ship with every page.",
      "The country info card now opens as a tall panel on the left of the globe instead of a bar across the bottom, so you can read about a place while looking at it; the legend moved to the top-right under the search box. On phones it still slides up from the bottom.",
      "Fixed a glitch where zooming or flying across the Atlas could wash the whole page in a golden glow.",
      "Editor tidy-ups: the image title, description and source fields now appear only after an image URL is set; the HTML source box stays collapsed until you open it; the card preview sits properly centred; and a stray divider line no longer cuts across the Timeline editing page.",
      "The timeline now teaches change: stepping between years briefly flashes gold over every territory that changed hands, old borders crossfade into new ones instead of snapping, and a play button walks the whole timeline as a time-lapse from 1500 to today.",
      "The country panel learned history: a \"Through the ages\" button lists who held that exact spot in every mapped year — Ming, then Qing, then the Republic — with each entry clickable to jump there. A breadcrumb above the title shows the empire a territory belongs to, one click to climb up.",
      "You can now share the Atlas: a Copy-link button gives a link straight to a year and place — send someone the Ottoman Empire in 1500 and their globe opens right on it.",
      "On old maps, land that no source records as any state's is now stippled with fine dots — the mapmaker's mark for terra incognita — so it no longer reads as a mystery country.",
      "A fifth daily game: Find it on the map. Five places a day — countries, historical territories, even a period capital — and you hunt them down on the real globe, with a distance hint if your first click misses. First-try finds count; five of five turns the tile gold, and the Clean Sweep badge now asks for all five games.",
      "The Atlas greets first-time visitors with a short how-to card (reopen it any time with the ? button), the zoom buttons returned to the bottom-right corner, and the whole globe now works from the keyboard — arrows rotate, Enter selects, [ and ] step through the years.",
      "The globe's edge shading and atmospheric glow no longer blink out while you drag or zoom — they now stay put through every movement.",
      "Find it on the map now teaches as you play: a wrong guess flashes the country you actually clicked red and opens its info panel, a right guess flashes green, and every reveal opens the answer's panel — so each round ends on something learned.",
      "The home-page game tiles now wear their colour as a wash fading to the right, matching the Library's collection banners — and in daylight both are noticeably more colourful (they were nearly invisible); night mode keeps its quieter shading.",
      "The home page's glossary tile is now called \"Gloss of the day\", and clicking it opens the term right beside the tile instead of far away in the corner of the screen.",
      "Studying is one key faster: once the answer is showing, pressing Enter marks the card Good and moves on — the same as clicking the green button.",
      "The Card of the day, Gloss of the day and Atlas tiles now wear the same rightward colour wash as the game tiles — and all of them kept their soft glow in the bottom-right corner.",
      "Levelling up is a proper celebration now: confetti rains across the whole screen, a golden flash bursts behind the card as it springs in, and a little fanfare plays.",
      "In the card editor, the text-formatting toolbar now stays pinned at the top while you scroll down a long card.",
      "The Session complete screen now closes with a simple checkmark instead of a Chinese character — Folio covers many histories, not just China's.",
      "The little spinning globe on the home page now follows the day/night switch instead of keeping its daylight colours in the dark.",
      "The Atlas runs markedly smoother. Spinning and zooming do far less work per frame, the first jump to a historical map no longer freezes for a second while it prepares the coastlines, zooming with a trackpad stopped rendering frames nobody sees, and having a whole empire selected no longer bogs the globe down while you drag it. It also holds on to a lot less memory.",
    ],
  },
  {
    d: "2026-07-23",
    t: "Fuller cards, for older readers",
    items: [
      "Every card's background is now longer and richer — about 300 words — and written for an older student rather than a young teenager: more of the detail and nuance is back, the vocabulary is a step up, and the careful 'scholars still disagree' notes remain. The same fuller version was rewritten fresh in all eight languages, to read naturally in each.",
      "The little spinning globe on the home page no longer shows false seas and gaps between neighbouring countries.",
      "Editing translations is now simpler: switch the site language in the top-right corner and the card and glossary editors edit that language directly — the separate language tabs inside the editor are gone, and glossary translations became editable for the first time.",
      "The card editor was rebuilt around the card itself: one live card — centred in the page — where double-clicking the question, answer, date or background edits it in place, with the formatting toolbar and the off-card details (decks, id, chronology, answer text) above and a collapsible HTML view of the whole card below. Cards without a picture show an add-image spot (editor only), and the little-used Chinese text fields left the form.",
      "In the editor's collection tree, decks and collections can now be dragged onto a sibling to reorder them — the Library page follows the same order.",
      "The glossary has been reset to be regrown entry by entry, like the card deck before it — terms and their translations will return as the new collections take shape.",
    ],
  },
  {
    d: "2026-07-22",
    t: "A quiet voice for the interface",
    items: [
      "The site now makes gentle sounds: a soft tick on buttons, a chirp on switches, a little pop when a card reveals, warm and low notes for the grade buttons, and a tiny fanfare for level-ups, achievements and perfect games. Turn them off any time under Settings → Audio.",
      "The daily quote on the home page now appears in your language — established translations of each passage, with authors under their familiar names (Confucio, Konfuzius, Конфуций…). Readers in Chinese see the classical originals: 学而时习之，不亦说乎？",
    ],
  },
  {
    d: "2026-07-21",
    t: "Plainer words, in every language",
    items: [
      "The whole site now reads in your language, not just the cards: the menus, buttons, settings, and every page including About are translated into Spanish, French, German, Italian, Dutch, Russian, Arabic and Mandarin. Choosing Arabic also flips the page to read right-to-left.",
      "Every card has been rewritten in plainer language with shorter sentences, so a curious 14-year-old can follow it — and the translations were redone to sound natural in each language rather than word-for-word. Nothing was simplified away: the facts, dates and the careful 'scientists still argue about this' notes are all still there.",
      "Three more cards in the World History › Prehistory deck.",
      "The China collection has been emptied while it sits in 'coming soon' — it will be rebuilt from the ground up.",
      "The card editor speaks every language too: language tabs above the fields let a card's Spanish, French, German, Italian, Dutch, Russian, Arabic or Mandarin translation be edited directly, with the live preview following along.",
      "Cards can now carry an image: a widescreen picture at the top of the Background section that opens fullscreen when clicked — zoom in with the scroll wheel or a click, drag to look around, and read the picture's title, description and source at the bottom. Admins add and edit all of it from the card editor.",
      "Fixed a doubled dash before the author's name under the daily quote, and the Card of the day tile got its missing coloured left edge.",
    ],
  },
  {
    d: "2026-07-20",
    t: "A wider world, in many tongues",
    items: [
      "Folio is opening up to all of history: the China collection has been set aside as 'coming soon' while we build a brand-new World History collection, which opens today with a Prehistory deck of four cards.",
      "The language menu in the top corner now shows a country flag beside each language, and gained two more: Arabic and Mandarin Chinese. Newly written cards and glossary terms come translated into all of them, and switching language now translates the site itself, not just the menu.",
      "Read-aloud has been set aside for now — the spoken-audio buttons and the Audio settings are gone while we rework how it sounds.",
    ],
  },
  {
    d: "2026-07-19",
    t: "A more welcoming home",
    items: [
      "First-time visitors now get a proper welcome: the home page explains what Folio is in one sentence, walks through spaced repetition in three short steps, and starts your first study session with a single button.",
      "Three new doorways on the home page: a Card of the day you can flip over, a Term of the day from the glossary, and a slowly spinning mini globe that opens the Atlas.",
      "The review banner now shows your day streak and tells 'all caught up' apart from 'not started yet'; the daily quote now rotates through history's great voices, East and West — Confucius and Sima Qian alongside Seneca, Cicero and Plato.",
      "The Mission page became the About page, rewritten in plain language anyone can follow: a picture of the forgetting curve, a five-step guide to using Folio, and answers to common questions — with the changelog and credits below.",
      "The About page went quiet: no more read-aloud there, on the intro or in its glossary popups.",
      "A fresh coat of colour in the Library: every collection now has its own identity — Aegean blue for Greece, imperial purple for Rome, saffron for India, lacquer red for Russia — with a gold seal, a soft colour wash and a drifting motif on every theme, including the default.",
      "The About page brightened too: coloured section accents with small icons, the forgetting curve on a soft panel, the changelog drawn as a timeline, and a drop cap on the intro — plus an accent line under page titles and deck rows tinted in their collection's colour.",
      "Seven brand-new themes in Settings, each a complete makeover of the site: Arcade (16-bit console), Academy (formal faculty), Scroll (aged parchment), Marble (classical inscriptions), Dynasty (vermilion and gold), Grove (deep forest) and Gazette (1940s newsprint, with two-column reading).",
      "The drifting patterns on the Library banners are gone — collection banners are now calm and still on every theme.",
      "The default theme found its colour: minigame tiles now hint at their hue before you play them, a fine indigo-vermilion-gold ribbon runs under the navigation, due and new counts colour themselves, Library bars fill in each collection's shade, and the discovery tiles wear their own accents.",
      "Settings reorganised into titled sections — Appearance, Study, Audio, Atlas, Data and a fenced-off Danger zone that asks you to type RESET. Themes now show little previews of themselves and try on live as you hover; narrators became pickable cards; random review order joined the page.",
      "The Account page got a profile makeover: a golden level ring around your photo, headline tiles for cards, streak, badges and quiz wins, badges that show their unlock date or your progress toward them, collection levels in their own colours and numerals — and on a friend's page, your level beside theirs.",
      "A pruning: the gold seals left the Library banners, Marble lost its patterned top band, and seven themes (Scroll, Grove, Dynasty, Tide, Press, Bloom, Atlas) were retired — eight distinct ones remain.",
      "On the Atlas, Capitals and Borders are now separate legend layers in every year — historical capitals can be switched on and off just like today's.",
    ],
  },
  {
    d: "2026-07-14",
    t: "Counting in every script",
    items: [
      "The upcoming collections on the Library page now count their levels in their own script: Roman numerals for Ancient Rome, ancient Greek numerals for Ancient Greece, Devanagari for India, and Cyrillic numerals for Russia — joining China's Chinese numerals.",
    ],
  },
  {
    d: "2026-07-13",
    t: "Live editing",
    items: [
      "Content edits made by an admin on the live site now publish to the cloud and reach every visitor within seconds — no redeploy needed.",
      "The Edit page and the Editor/Visitor switch are now visible only to signed-in admin accounts; visitors and regular accounts no longer see them.",
      "Nineteen new cards in the Eastern Zhou deck.",
      "Pre-recorded narration for five more cards.",
    ],
  },
  {
    d: "2026-07-12",
    t: "Style pass",
    items: [
      "A consistency pass across every card and glossary entry: precise numbers above 20 are now written as numerals, centuries and millennia are always numbered (“11th century”), and literature titles are properly italicised — nearly 400 corrections in all.",
      "Twenty new cards: three in the Western Zhou deck and 17 in the Eastern Zhou deck.",
      "Profile photos: click your avatar on the Account page to add a picture — it shows on your profile and in your friends' lists.",
      "Read-aloud is now off by default — switch it on under Settings → Text-to-speech whenever you want the narration.",
    ],
  },
  {
    d: "2026-07-11",
    t: "Folio goes online",
    items: [
      "The site is now live on the web, updated directly from the development machine.",
      "Online accounts: sign up with email, and your study progress syncs to the cloud and follows you across devices.",
      "Friends are server-backed — send requests, accept, and browse a friend's badges and deck progress from any device.",
      "Every card's question, answer and background now has pre-recorded narration by a single warm male voice on all devices, with the device's own speech as fallback.",
      "New Mission page: why spaced repetition, source credits, and this changelog.",
      "Mission page refined: its tab moved next to Atlas, the changelog now sits above the credits, glossary popups work inside the intro, and admins can click the intro title or paragraphs to edit them in place.",
      "Fourteen new cards in the Western Zhou deck.",
      "Card backgrounds now play their recorded narration too (a mismatch had them falling back to the robotic device voice), and Settings gained a Narrator picker: American or British English, male or female.",
      "New accounts now start with five new cards per day instead of three (adjustable in Settings as before).",
      "The minigame tiles now earn their colour: quiet with just a coloured edge until you play, filling with colour once completed, and turning gold for a perfect score.",
      "Completed game tiles now show your score for the day (e.g. “4/5 correct!”), light mode lost the dark corner on coloured tiles, and the Daily-review button moved to the bottom-right so the level bar runs the full width.",
      "The Daily review now sits above the minigame tiles, sharing one grid, and the Mission intro gained a read-aloud button — silent until you click it.",
      "This changelog became a true day-by-day record back to June 24th, its dates now always in English, and the review banner got a neutral left bar with its button on the stats line.",
    ],
  },
  {
    d: "2026-07-10",
    t: "The deck regrown",
    items: [
      "The card deck was regrown one researched card at a time into per-dynasty history decks — mythology through the Western Zhou, around 150 cards — each with a uniform, information-dense background story.",
      "Cards file into every deck their era touches, ordered chronologically, with etymology and date boxes throughout.",
    ],
  },
  {
    d: "2026-07-09",
    t: "Glossary day",
    items: [
      "The glossary passed 2,100 terms — every one a three-sentence, neutral definition with category tags, dates and aliases.",
      "Fixed a save bug that quietly dropped some terms' settings when the editor wrote its files.",
    ],
  },
  {
    d: "2026-07-08",
    t: "Read-aloud arrives",
    items: [
      "Cards learned to speak: a slow male voice reads the question, answer and background; a female Chinese voice reads the hanzi. Mute button on every card, tiny play buttons behind the section titles, and glossary popups read themselves when opened.",
      "Select any background text and right-click for Copy / Read aloud.",
      "Settings gained a text-to-speech switch and device-voice pickers that automatically prefer the most human-sounding voices a device offers.",
    ],
  },
  {
    d: "2026-07-07",
    t: "Study polish",
    items: [
      "New cards graded “Good” now return later the same session (Anki-style learning step) instead of jumping to tomorrow.",
      "Levelling up shows a congratulations popup naming the deck; level numerals turned gold on the home and Library banners.",
      "The Atlas country info-box is capped on every screen size, so the globe and its close button always stay visible.",
      "Collection banners stopped showing the card date-spans (decks keep theirs), and repaired glossary links on a dozen cards.",
    ],
  },
  {
    d: "2026-07-06",
    t: "Games day",
    items: [
      "True or False grew to 79 statements and Who said it? to 64 quotations — all researched and fact-checked.",
      "The home tiles got icon artwork, daily checkmarks for all four games, and the Clean Sweep badge for winning everything in one day.",
      "Ctrl+Z now undoes the last edit on the editor page, and open glossary popups survive a page reload.",
    ],
  },
  {
    d: "2026-07-05",
    t: "Feature sprint",
    items: [
      "The Atlas opens centred on your home location (set in Settings; the Netherlands by default), and gained global terrain relief — mountains and ocean floor blended into the map.",
      "The country info-box grew up: the state's full official name, the years it existed, a general description beside what was happening in the selected year, and year-specific population / area / GDP.",
      "Undo and redo came to the whiteboard, on both the globe and card studies.",
      "Daily review's Random mode now draws the day's new cards randomly from your active decks, Library collections are studiable with one click, and the whiteboard covers the whole page before the answer is revealed.",
      "Editor quality-of-life: automatic save-to-files while editing, and the page remembers your place through reloads.",
    ],
  },
  {
    d: "2026-07-04",
    t: "The Atlas learns history",
    items: [
      "Historical border eras joined the globe's timeline — accurate snapshots from 1600 through 2020, changing only the political borders while today's coastlines, lakes and rivers stay put.",
      "Around 1,400 period-accurate capitals researched across the eras, with relocations honoured (St. Petersburg → Moscow, Constantinople → Ankara, Calcutta → Delhi…).",
      "Empires drill down: one click selects a whole colonial empire, a double-click the single territory, and the United Kingdom opens into its constituent countries in every era.",
      "The source data's quirks were cleaned in the build — overlapping territories removed, stray border ends welded onto the coastline.",
    ],
  },
  {
    d: "2026-06-25",
    t: "Depth, theming, admin tooling and the Atlas",
    items: [
      "The Atlas was born: an orthographic globe with drag, zoom and a bottom timeline.",
      "Eight visual themes, each with light and dark variants.",
      "The admin editor arrived — a three-pane back-end for cards, decks and the glossary, with local-overlay persistence and JSON export.",
      "The glossary grew from hundreds to thousands of terms with clickable, nested definitions.",
      "Cards gained multi-deck membership with shared progress, ordered chronologically.",
    ],
  },
  {
    d: "2026-06-24",
    t: "Folio is built in a day",
    items: [
      "The whole foundation in one day: an Anki-style spaced-repetition study site built from scratch in plain JavaScript — no frameworks, no build step.",
      "Study flow (question → reveal → grade), daily review scheduling, nested decks, daily games, a whiteboard, glossary tooltips, and an editorial design system.",
      "The China deck imported and reorganised into period decks; questions rewritten as fill-in-the-blank statements.",
    ],
  },
];
