/* Atlas source footnotes — the scholarship behind the place panel's prose.

   COUNTRY_SOURCES       <lowercased place name> -> [ "<Chicago note-form citation>", … ]
                         the works behind the state's GENERAL description (countries.js), which is
                         constant across map-years.
   COUNTRY_YEAR_SOURCES  <lowercased place name> -> { "<map-year>": [ … ] }
                         the works behind that year's paragraph (country-years.js).

   The panel merges the two into ONE numbered list, general first, de-duplicated — a work behind both
   paragraphs is one footnote, not two. A place with no entry simply shows no Sources fold; a missing
   citation is never invented.

   Keyed exactly like countries.js / country-years.js: the name as it appears on the map, lowercased and
   whitespace-collapsed (present-day name, or the era iteration's name).

   Citations are NOT translated — a citation names an edition that exists in one language.

   Lazy: part of the `atlas` data bundle (see DATA_BUNDLES in app.js).
   Written by `node .claude/add-country-sources.js <batch.json>` — see CLAUDE.md. */
window.COUNTRY_SOURCES = Object.assign(window.COUNTRY_SOURCES || {}, {
"bangladesh": ["United Nations Statistics Division, “Bangladesh,” UNdata Country Profile, https://data.un.org/en/iso/bd.html. [Open access]","Office of the Historian, U.S. Department of State, “Bangladesh,” A Guide to the United States' History of Recognition, Diplomatic, and Consular Relations, by Country, since 1776, https://history.state.gov/countries/bangladesh. [Open access]","Office of the Historian, U.S. Department of State, “The South Asia Crisis and the Founding of Bangladesh, 1971,” Milestones in the History of U.S. Foreign Relations, https://history.state.gov/milestones/1969-1976/south-asia. [Open access]","World Bank, “Population, total: Bangladesh,” World Development Indicators, https://api.worldbank.org/v2/country/BGD/indicator/SP.POP.TOTL?format=json. [Open access]","World Bank, “Surface area (sq. km): Bangladesh,” World Development Indicators, https://api.worldbank.org/v2/country/BGD/indicator/AG.SRF.TOTL.K2?format=json. [Open access]"],
"brazil": ["United Nations Statistics Division, “Brazil,” UNdata Country Profile, https://data.un.org/en/iso/br.html. [Open access]","Office of the Historian, U.S. Department of State, “Brazil,” A Guide to the United States' History of Recognition, Diplomatic, and Consular Relations, by Country, since 1776, https://history.state.gov/countries/brazil. [Open access]","Office of the Historian, U.S. Department of State, “Monroe Doctrine, 1823,” Milestones in the History of U.S. Foreign Relations, https://history.state.gov/milestones/1801-1829/monroe. [Open access]","World Bank, “Population, total: Brazil,” World Development Indicators, https://api.worldbank.org/v2/country/BRA/indicator/SP.POP.TOTL?format=json. [Open access]","World Bank, “Surface area (sq. km): Brazil,” World Development Indicators, https://api.worldbank.org/v2/country/BRA/indicator/AG.SRF.TOTL.K2?format=json. [Open access]"],
"china": ["United Nations Statistics Division, “China,” UNdata Country Profile, https://data.un.org/en/iso/cn.html. [Open access]","Office of the Historian, U.S. Department of State, “China,” A Guide to the United States' History of Recognition, Diplomatic, and Consular Relations, by Country, since 1776, https://history.state.gov/countries/china. [Open access]","Office of the Historian, U.S. Department of State, “Rapprochement with China, 1972,” Milestones in the History of U.S. Foreign Relations, https://history.state.gov/milestones/1969-1976/rapprochement-china. [Open access]","World Bank, “Population, total: China,” World Development Indicators, https://api.worldbank.org/v2/country/CHN/indicator/SP.POP.TOTL?format=json. [Open access]","World Bank, “Surface area (sq. km): China,” World Development Indicators, https://api.worldbank.org/v2/country/CHN/indicator/AG.SRF.TOTL.K2?format=json. [Open access]"],
"india": ["United Nations Statistics Division, “India,” UNdata Country Profile, https://data.un.org/en/iso/in.html. [Open access]","Office of the Historian, U.S. Department of State, “India,” A Guide to the United States' History of Recognition, Diplomatic, and Consular Relations, by Country, since 1776, https://history.state.gov/countries/india. [Open access]","Office of the Historian, U.S. Department of State, “Decolonization of Asia and Africa, 1945–1960,” Milestones in the History of U.S. Foreign Relations, https://history.state.gov/milestones/1945-1952/asia-and-africa. [Open access]","World Bank, “Population, total: India,” World Development Indicators, https://api.worldbank.org/v2/country/IND/indicator/SP.POP.TOTL?format=json. [Open access]","World Bank, “Surface area (sq. km): India,” World Development Indicators, https://api.worldbank.org/v2/country/IND/indicator/AG.SRF.TOTL.K2?format=json. [Open access]"],
"indonesia": ["United Nations Statistics Division, “Indonesia,” UNdata Country Profile, https://data.un.org/en/iso/id.html. [Open access]","Office of the Historian, U.S. Department of State, “Indonesia,” A Guide to the United States' History of Recognition, Diplomatic, and Consular Relations, by Country, since 1776, https://history.state.gov/countries/indonesia. [Open access]","Office of the Historian, U.S. Department of State, “Bandung Conference (Asian-African Conference), 1955,” Milestones in the History of U.S. Foreign Relations, https://history.state.gov/milestones/1953-1960/bandung-conf. [Open access]","World Bank, “Population, total: Indonesia,” World Development Indicators, https://api.worldbank.org/v2/country/IDN/indicator/SP.POP.TOTL?format=json. [Open access]","World Bank, “Surface area (sq. km): Indonesia,” World Development Indicators, https://api.worldbank.org/v2/country/IDN/indicator/AG.SRF.TOTL.K2?format=json. [Open access]"],
"nigeria": ["United Nations Statistics Division, “Nigeria,” UNdata Country Profile, https://data.un.org/en/iso/ng.html. [Open access]","Office of the Historian, U.S. Department of State, “Nigeria,” A Guide to the United States' History of Recognition, Diplomatic, and Consular Relations, by Country, since 1776, https://history.state.gov/countries/nigeria. [Open access]","Office of the Historian, U.S. Department of State, “Decolonization of Asia and Africa, 1945–1960,” Milestones in the History of U.S. Foreign Relations, https://history.state.gov/milestones/1945-1952/asia-and-africa. [Open access]","World Bank, “Population, total: Nigeria,” World Development Indicators, https://api.worldbank.org/v2/country/NGA/indicator/SP.POP.TOTL?format=json. [Open access]","World Bank, “Surface area (sq. km): Nigeria,” World Development Indicators, https://api.worldbank.org/v2/country/NGA/indicator/AG.SRF.TOTL.K2?format=json. [Open access]"],
"pakistan": ["United Nations Statistics Division, “Pakistan,” UNdata Country Profile, https://data.un.org/en/iso/pk.html. [Open access]","Office of the Historian, U.S. Department of State, “Pakistan,” A Guide to the United States' History of Recognition, Diplomatic, and Consular Relations, by Country, since 1776, https://history.state.gov/countries/pakistan. [Open access]","Office of the Historian, U.S. Department of State, “The India-Pakistan War of 1965,” Milestones in the History of U.S. Foreign Relations, https://history.state.gov/milestones/1961-1968/india-pakistan-war. [Open access]","World Bank, “Population, total: Pakistan,” World Development Indicators, https://api.worldbank.org/v2/country/PAK/indicator/SP.POP.TOTL?format=json. [Open access]","World Bank, “Surface area (sq. km): Pakistan,” World Development Indicators, https://api.worldbank.org/v2/country/PAK/indicator/AG.SRF.TOTL.K2?format=json. [Open access]"],
"united states of america": ["United Nations Statistics Division, “United States of America,” UNdata Country Profile, https://data.un.org/en/iso/us.html. [Open access]","National Archives and Records Administration, “Declaration of Independence (1776),” Milestone Documents, https://www.archives.gov/milestone-documents/declaration-of-independence. [Open access]","Office of the Historian, U.S. Department of State, “Monroe Doctrine, 1823,” Milestones in the History of U.S. Foreign Relations, https://history.state.gov/milestones/1801-1829/monroe. [Open access]","World Bank, “Population, total: United States,” World Development Indicators, https://api.worldbank.org/v2/country/USA/indicator/SP.POP.TOTL?format=json. [Open access]","World Bank, “Surface area (sq. km): United States,” World Development Indicators, https://api.worldbank.org/v2/country/USA/indicator/AG.SRF.TOTL.K2?format=json. [Open access]"]
});

window.COUNTRY_YEAR_SOURCES = Object.assign(window.COUNTRY_YEAR_SOURCES || {}, {

});
