/* Atlas source footnotes — the scholarship behind the place panel's prose.

   COUNTRY_SOURCES       <lowercased place name> -> [ "<Chicago note-form citation>", … ]
                         the works behind the state's GENERAL description (countries.js), which is
                         constant across map-years.
   COUNTRY_YEAR_SOURCES  <lowercased place name> -> { "<map-year>": [ … ] }
                         the works behind that year's paragraph (country-years.js).

   The panel merges the two into ONE numbered list, general first, de-duplicated — a work behind both
   paragraphs is one footnote, not two. A place with no entry simply shows no Sources fold; a missing
   citation is never invented.

   Keyed exactly like countries.js / country-years.js: the name as it appears on the map, lowercased and
   whitespace-collapsed (present-day name, or the era iteration's name).

   Citations are NOT translated — a citation names an edition that exists in one language.

   Lazy: part of the `atlas` data bundle (see DATA_BUNDLES in app.js).
   Written by `node .claude/add-country-sources.js <batch.json>` — see CLAUDE.md. */
window.COUNTRY_SOURCES = Object.assign(window.COUNTRY_SOURCES || {}, {
"bangladesh": ["United Nations Statistics Division, “Bangladesh,” UNdata Country Profile, https://data.un.org/en/iso/bd.html. [Open access]","Office of the Historian, U.S. Department of State, “Bangladesh,” A Guide to the United States' History of Recognition, Diplomatic, and Consular Relations, by Country, since 1776, https://history.state.gov/countries/bangladesh. [Open access]","Office of the Historian, U.S. Department of State, “The South Asia Crisis and the Founding of Bangladesh, 1971,” Milestones in the History of U.S. Foreign Relations, https://history.state.gov/milestones/1969-1976/south-asia. [Open access]","World Bank, “Population, total: Bangladesh,” World Development Indicators, https://api.worldbank.org/v2/country/BGD/indicator/SP.POP.TOTL?format=json. [Open access]","World Bank, “Surface area (sq. km): Bangladesh,” World Development Indicators, https://api.worldbank.org/v2/country/BGD/indicator/AG.SRF.TOTL.K2?format=json. [Open access]"],
"brazil": ["United Nations Statistics Division, “Brazil,” UNdata Country Profile, https://data.un.org/en/iso/br.html. [Open access]","Office of the Historian, U.S. Department of State, “Brazil,” A Guide to the United States' History of Recognition, Diplomatic, and Consular Relations, by Country, since 1776, https://history.state.gov/countries/brazil. [Open access]","Office of the Historian, U.S. Department of State, “Monroe Doctrine, 1823,” Milestones in the History of U.S. Foreign Relations, https://history.state.gov/milestones/1801-1829/monroe. [Open access]","World Bank, “Population, total: Brazil,” World Development Indicators, https://api.worldbank.org/v2/country/BRA/indicator/SP.POP.TOTL?format=json. [Open access]","World Bank, “Surface area (sq. km): Brazil,” World Development Indicators, https://api.worldbank.org/v2/country/BRA/indicator/AG.SRF.TOTL.K2?format=json. [Open access]"],
"china": ["United Nations Statistics Division, “China,” UNdata Country Profile, https://data.un.org/en/iso/cn.html. [Open access]","Office of the Historian, U.S. Department of State, “Rapprochement with China, 1972,” Milestones in the History of U.S. Foreign Relations, https://history.state.gov/milestones/1969-1976/rapprochement-china. [Open access]","World Bank, “Population, total: China,” World Development Indicators, https://api.worldbank.org/v2/country/CHN/indicator/SP.POP.TOTL?format=json. [Open access]","World Bank, “Surface area (sq. km): China,” World Development Indicators, https://api.worldbank.org/v2/country/CHN/indicator/AG.SRF.TOTL.K2?format=json. [Open access]","UN General Assembly, “Restoration of the lawful rights of the People's Republic of China in the United Nations,” resolution 2758 (XXVI), adopted 25 October 1971, https://digitallibrary.un.org/record/192054. [Open access]"],
"dem. rep. congo": ["United Nations Statistics Division, “Democratic Republic of the Congo,” UNdata Country Profile, https://data.un.org/en/iso/cd.html. [Open access]","Office of the Historian, U.S. Department of State, “The Democratic Republic of the Congo,” A Guide to the United States’ History of Recognition, Diplomatic, and Consular Relations, by Country, since 1776, https://history.state.gov/countries/congo-democratic-republic. [Open access]","World Bank, “Population, total: Congo, Dem. Rep.,” World Development Indicators, https://api.worldbank.org/v2/country/COD/indicator/SP.POP.TOTL?format=json. [Open access]","World Bank, “Surface area (sq. km): the Democratic Republic of the Congo and the United States,” World Development Indicators, https://api.worldbank.org/v2/country/COD;USA/indicator/AG.SRF.TOTL.K2?format=json. [Open access]","Office of the Historian, U.S. Department of State, “The Congo, Decolonization, and the Cold War, 1960–1965,” Milestones in the History of U.S. Foreign Relations, https://history.state.gov/milestones/1961-1968/congo-decolonization. [Open access]"],
"egypt": ["United Nations Statistics Division, “Egypt,” UNdata Country Profile, https://data.un.org/en/iso/eg.html. [Open access]","Office of the Historian, U.S. Department of State, “Egypt,” A Guide to the United States’ History of Recognition, Diplomatic, and Consular Relations, by Country, since 1776, https://history.state.gov/countries/egypt. [Open access]","World Bank, “Population, total: Egypt, Arab Rep.,” World Development Indicators, https://api.worldbank.org/v2/country/EGY/indicator/SP.POP.TOTL?format=json. [Open access]","World Bank, “Surface area (sq. km): Egypt and the United Kingdom,” World Development Indicators, https://api.worldbank.org/v2/country/EGY;GBR/indicator/AG.SRF.TOTL.K2?format=json. [Open access]","Office of the Historian, U.S. Department of State, “The Suez Crisis, 1956,” Milestones in the History of U.S. Foreign Relations, https://history.state.gov/milestones/1953-1960/suez. [Open access]"],
"ethiopia": ["United Nations Statistics Division, “Ethiopia,” UNdata Country Profile, https://data.un.org/en/iso/et.html. [Open access]","Office of the Historian, U.S. Department of State, “Ethiopia,” A Guide to the United States’ History of Recognition, Diplomatic, and Consular Relations, by Country, since 1776, https://history.state.gov/countries/ethiopia. [Open access]","World Bank, “Population, total: Ethiopia,” World Development Indicators, https://api.worldbank.org/v2/country/ETH/indicator/SP.POP.TOTL?format=json. [Open access]","World Bank, “Surface area (sq. km): Ethiopia and Italy,” World Development Indicators, https://api.worldbank.org/v2/country/ETH;ITA/indicator/AG.SRF.TOTL.K2?format=json. [Open access]","Office of the Historian, U.S. Department of State, “Eritrea,” A Guide to the United States’ History of Recognition, Diplomatic, and Consular Relations, by Country, since 1776, https://history.state.gov/countries/eritrea. [Open access]"],
"france": ["United Nations Statistics Division, “France,” UNdata Country Profile, https://data.un.org/en/iso/fr.html. [Open access]","Office of the Historian, U.S. Department of State, “France,” A Guide to the United States’ History of Recognition, Diplomatic, and Consular Relations, by Country, since 1776, https://history.state.gov/countries/france. [Open access]","World Bank, “Population, total: France,” World Development Indicators, https://api.worldbank.org/v2/country/FRA/indicator/SP.POP.TOTL?format=json. [Open access]","World Bank, “Surface area (sq. km): France and Spain,” World Development Indicators, https://api.worldbank.org/v2/country/FRA;ESP/indicator/AG.SRF.TOTL.K2?format=json. [Open access]","European Union, “France,” EU countries, https://european-union.europa.eu/principles-countries-history/eu-countries/france_en. [Open access]"],
"germany": ["United Nations Statistics Division, “Germany,” UNdata Country Profile, https://data.un.org/en/iso/de.html. [Open access]","Office of the Historian, U.S. Department of State, “Germany,” A Guide to the United States’ History of Recognition, Diplomatic, and Consular Relations, by Country, since 1776, https://history.state.gov/countries/germany. [Open access]","World Bank, “Population, total: Germany,” World Development Indicators, https://api.worldbank.org/v2/country/DEU/indicator/SP.POP.TOTL?format=json. [Open access]","World Bank, “Surface area (sq. km): Germany and Italy,” World Development Indicators, https://api.worldbank.org/v2/country/DEU;ITA/indicator/AG.SRF.TOTL.K2?format=json. [Open access]","European Union, “Germany,” EU countries, https://european-union.europa.eu/principles-countries-history/eu-countries/germany_en. [Open access]"],
"india": ["United Nations Statistics Division, “India,” UNdata Country Profile, https://data.un.org/en/iso/in.html. [Open access]","Office of the Historian, U.S. Department of State, “India,” A Guide to the United States' History of Recognition, Diplomatic, and Consular Relations, by Country, since 1776, https://history.state.gov/countries/india. [Open access]","Office of the Historian, U.S. Department of State, “Decolonization of Asia and Africa, 1945–1960,” Milestones in the History of U.S. Foreign Relations, https://history.state.gov/milestones/1945-1952/asia-and-africa. [Open access]","World Bank, “Population, total: India,” World Development Indicators, https://api.worldbank.org/v2/country/IND/indicator/SP.POP.TOTL?format=json. [Open access]","World Bank, “Surface area (sq. km): India,” World Development Indicators, https://api.worldbank.org/v2/country/IND/indicator/AG.SRF.TOTL.K2?format=json. [Open access]"],
"indonesia": ["United Nations Statistics Division, “Indonesia,” UNdata Country Profile, https://data.un.org/en/iso/id.html. [Open access]","Office of the Historian, U.S. Department of State, “Indonesia,” A Guide to the United States' History of Recognition, Diplomatic, and Consular Relations, by Country, since 1776, https://history.state.gov/countries/indonesia. [Open access]","Office of the Historian, U.S. Department of State, “Bandung Conference (Asian-African Conference), 1955,” Milestones in the History of U.S. Foreign Relations, https://history.state.gov/milestones/1953-1960/bandung-conf. [Open access]","World Bank, “Population, total: Indonesia,” World Development Indicators, https://api.worldbank.org/v2/country/IDN/indicator/SP.POP.TOTL?format=json. [Open access]","World Bank, “Surface area (sq. km): Indonesia,” World Development Indicators, https://api.worldbank.org/v2/country/IDN/indicator/AG.SRF.TOTL.K2?format=json. [Open access]"],
"iran": ["United Nations Statistics Division, “Iran (Islamic Republic of),” UNdata Country Profile, https://data.un.org/en/iso/ir.html. [Open access]","Office of the Historian, U.S. Department of State, “Iran,” A Guide to the United States’ History of Recognition, Diplomatic, and Consular Relations, by Country, since 1776, https://history.state.gov/countries/iran. [Open access]","World Bank, “Population, total: Iran, Islamic Rep.,” World Development Indicators, https://api.worldbank.org/v2/country/IRN/indicator/SP.POP.TOTL?format=json. [Open access]","World Bank, “Surface area (sq. km): Iran and Egypt,” World Development Indicators, https://api.worldbank.org/v2/country/IRN;EGY/indicator/AG.SRF.TOTL.K2?format=json. [Open access]","Office of the Historian, U.S. Department of State, “The Tehran Conference, 1943,” Milestones in the History of U.S. Foreign Relations, https://history.state.gov/milestones/1937-1945/tehran-conf. [Open access]"],
"italy": ["United Nations Statistics Division, “Italy,” UNdata Country Profile, https://data.un.org/en/iso/it.html. [Open access]","Office of the Historian, U.S. Department of State, “Italy,” A Guide to the United States’ History of Recognition, Diplomatic, and Consular Relations, by Country, since 1776, https://history.state.gov/countries/italy. [Open access]","World Bank, “Population, total: Italy,” World Development Indicators, https://api.worldbank.org/v2/country/ITA/indicator/SP.POP.TOTL?format=json. [Open access]","World Bank, “Surface area (sq. km): Italy and the United Kingdom,” World Development Indicators, https://api.worldbank.org/v2/country/ITA;GBR/indicator/AG.SRF.TOTL.K2?format=json. [Open access]","European Union, “Italy,” EU countries, https://european-union.europa.eu/principles-countries-history/eu-countries/italy_en. [Open access]"],
"japan": ["United Nations Statistics Division, “Japan,” UNdata Country Profile, https://data.un.org/en/iso/jp.html. [Open access]","Office of the Historian, U.S. Department of State, “Japan,” A Guide to the United States’ History of Recognition, Diplomatic, and Consular Relations, by Country, since 1776, https://history.state.gov/countries/japan. [Open access]","World Bank, “Population, total: Japan,” World Development Indicators, https://api.worldbank.org/v2/country/JPN/indicator/SP.POP.TOTL?format=json. [Open access]","World Bank, “Surface area (sq. km): Japan and Germany,” World Development Indicators, https://api.worldbank.org/v2/country/JPN;DEU/indicator/AG.SRF.TOTL.K2?format=json. [Open access]","Office of the Historian, U.S. Department of State, “The United States and the Opening to Japan, 1853,” Milestones in the History of U.S. Foreign Relations, https://history.state.gov/milestones/1830-1860/opening-to-japan. [Open access]"],
"mexico": ["United Nations Statistics Division, “Mexico,” UNdata Country Profile, https://data.un.org/en/iso/mx.html. [Open access]","Office of the Historian, U.S. Department of State, “Mexico,” A Guide to the United States’ History of Recognition, Diplomatic, and Consular Relations, by Country, since 1776, https://history.state.gov/countries/mexico. [Open access]","World Bank, “Population, total: Mexico,” World Development Indicators, https://api.worldbank.org/v2/country/MEX/indicator/SP.POP.TOTL?format=json. [Open access]","World Bank, “Surface area (sq. km): Mexico and the United Kingdom,” World Development Indicators, https://api.worldbank.org/v2/country/MEX;GBR/indicator/AG.SRF.TOTL.K2?format=json. [Open access]","National Archives and Records Administration, “Treaty of Guadalupe Hidalgo (1848),” Milestone Documents, https://www.archives.gov/milestone-documents/treaty-of-guadalupe-hidalgo. [Open access]"],
"nigeria": ["United Nations Statistics Division, “Nigeria,” UNdata Country Profile, https://data.un.org/en/iso/ng.html. [Open access]","Office of the Historian, U.S. Department of State, “Nigeria,” A Guide to the United States' History of Recognition, Diplomatic, and Consular Relations, by Country, since 1776, https://history.state.gov/countries/nigeria. [Open access]","Office of the Historian, U.S. Department of State, “Decolonization of Asia and Africa, 1945–1960,” Milestones in the History of U.S. Foreign Relations, https://history.state.gov/milestones/1945-1952/asia-and-africa. [Open access]","World Bank, “Population, total: Nigeria,” World Development Indicators, https://api.worldbank.org/v2/country/NGA/indicator/SP.POP.TOTL?format=json. [Open access]","World Bank, “Surface area (sq. km): Nigeria,” World Development Indicators, https://api.worldbank.org/v2/country/NGA/indicator/AG.SRF.TOTL.K2?format=json. [Open access]"],
"pakistan": ["United Nations Statistics Division, “Pakistan,” UNdata Country Profile, https://data.un.org/en/iso/pk.html. [Open access]","Office of the Historian, U.S. Department of State, “Pakistan,” A Guide to the United States' History of Recognition, Diplomatic, and Consular Relations, by Country, since 1776, https://history.state.gov/countries/pakistan. [Open access]","Office of the Historian, U.S. Department of State, “The India-Pakistan War of 1965,” Milestones in the History of U.S. Foreign Relations, https://history.state.gov/milestones/1961-1968/india-pakistan-war. [Open access]","World Bank, “Population, total: Pakistan,” World Development Indicators, https://api.worldbank.org/v2/country/PAK/indicator/SP.POP.TOTL?format=json. [Open access]","World Bank, “Surface area (sq. km): Pakistan,” World Development Indicators, https://api.worldbank.org/v2/country/PAK/indicator/AG.SRF.TOTL.K2?format=json. [Open access]"],
"philippines": ["United Nations Statistics Division, “Philippines,” UNdata Country Profile, https://data.un.org/en/iso/ph.html. [Open access]","Office of the Historian, U.S. Department of State, “Philippines,” A Guide to the United States’ History of Recognition, Diplomatic, and Consular Relations, by Country, since 1776, https://history.state.gov/countries/philippines. [Open access]","World Bank, “Population, total: Philippines,” World Development Indicators, https://api.worldbank.org/v2/country/PHL/indicator/SP.POP.TOTL?format=json. [Open access]","World Bank, “Surface area (sq. km): the Philippines and Italy,” World Development Indicators, https://api.worldbank.org/v2/country/PHL;ITA/indicator/AG.SRF.TOTL.K2?format=json. [Open access]","Office of the Historian, U.S. Department of State, “The Philippine-American War, 1899–1902,” Milestones in the History of U.S. Foreign Relations, https://history.state.gov/milestones/1899-1913/war. [Open access]"],
"russia": ["United Nations Statistics Division, “Russian Federation,” UNdata Country Profile, https://data.un.org/en/iso/ru.html. [Open access]","Office of the Historian, U.S. Department of State, “Russia,” A Guide to the United States’ History of Recognition, Diplomatic, and Consular Relations, by Country, since 1776, https://history.state.gov/countries/russia. [Open access]","World Bank, “Population, total: Russian Federation,” World Development Indicators, https://api.worldbank.org/v2/country/RUS/indicator/SP.POP.TOTL?format=json. [Open access]","World Bank, “Surface area (sq. km): Russian Federation and India,” World Development Indicators, https://api.worldbank.org/v2/country/RUS;IND/indicator/AG.SRF.TOTL.K2?format=json. [Open access]","Office of the Historian, U.S. Department of State, “The Collapse of the Soviet Union,” Milestones in the History of U.S. Foreign Relations, https://history.state.gov/milestones/1989-1992/collapse-soviet-union. [Open access]"],
"south africa": ["United Nations Statistics Division, “South Africa,” UNdata Country Profile, https://data.un.org/en/iso/za.html. [Open access]","Office of the Historian, U.S. Department of State, “South Africa,” A Guide to the United States’ History of Recognition, Diplomatic, and Consular Relations, by Country, since 1776, https://history.state.gov/countries/south-africa. [Open access]","World Bank, “Population, total: South Africa,” World Development Indicators, https://api.worldbank.org/v2/country/ZAF/indicator/SP.POP.TOTL?format=json. [Open access]","World Bank, “Surface area (sq. km): South Africa and Nigeria,” World Development Indicators, https://api.worldbank.org/v2/country/ZAF;NGA/indicator/AG.SRF.TOTL.K2?format=json. [Open access]","Office of the Historian, U.S. Department of State, “The End of Apartheid,” Milestones in the History of U.S. Foreign Relations, https://history.state.gov/milestones/1989-1992/apartheid. [Open access]"],
"thailand": ["United Nations Statistics Division, “Thailand,” UNdata Country Profile, https://data.un.org/en/iso/th.html. [Open access]","Office of the Historian, U.S. Department of State, “Thailand,” A Guide to the United States’ History of Recognition, Diplomatic, and Consular Relations, by Country, since 1776, https://history.state.gov/countries/thailand. [Open access]","World Bank, “Population, total: Thailand,” World Development Indicators, https://api.worldbank.org/v2/country/THA/indicator/SP.POP.TOTL?format=json. [Open access]","World Bank, “Surface area (sq. km): Thailand and Spain,” World Development Indicators, https://api.worldbank.org/v2/country/THA;ESP/indicator/AG.SRF.TOTL.K2?format=json. [Open access]","Office of the Historian, U.S. Department of State, “Southeast Asia Treaty Organization (SEATO), 1954,” Milestones in the History of U.S. Foreign Relations, https://history.state.gov/milestones/1953-1960/seato. [Open access]"],
"turkey": ["United Nations Statistics Division, “Türkiye,” UNdata Country Profile, https://data.un.org/en/iso/tr.html. [Open access]","Office of the Historian, U.S. Department of State, “Turkey,” A Guide to the United States’ History of Recognition, Diplomatic, and Consular Relations, by Country, since 1776, https://history.state.gov/countries/turkey. [Open access]","World Bank, “Population, total: Türkiye,” World Development Indicators, https://api.worldbank.org/v2/country/TUR/indicator/SP.POP.TOTL?format=json. [Open access]","World Bank, “Surface area (sq. km): Türkiye and Germany,” World Development Indicators, https://api.worldbank.org/v2/country/TUR;DEU/indicator/AG.SRF.TOTL.K2?format=json. [Open access]","Office of the Historian, U.S. Department of State, “The Truman Doctrine, 1947,” Milestones in the History of U.S. Foreign Relations, https://history.state.gov/milestones/1945-1952/truman-doctrine. [Open access]"],
"united kingdom": ["United Nations Statistics Division, “United Kingdom,” UNdata Country Profile, https://data.un.org/en/iso/gb.html. [Open access]","Office of the Historian, U.S. Department of State, “The United Kingdom,” A Guide to the United States’ History of Recognition, Diplomatic, and Consular Relations, by Country, since 1776, https://history.state.gov/countries/united-kingdom. [Open access]","World Bank, “Population, total: United Kingdom,” World Development Indicators, https://api.worldbank.org/v2/country/GBR/indicator/SP.POP.TOTL?format=json. [Open access]","World Bank, “Surface area (sq. km): the United Kingdom and Germany,” World Development Indicators, https://api.worldbank.org/v2/country/GBR;DEU/indicator/AG.SRF.TOTL.K2?format=json. [Open access]","Office of the Historian, U.S. Department of State, “North Atlantic Treaty Organization (NATO), 1949,” Milestones in the History of U.S. Foreign Relations, https://history.state.gov/milestones/1945-1952/nato. [Open access]"],
"united states of america": ["United Nations Statistics Division, “United States of America,” UNdata Country Profile, https://data.un.org/en/iso/us.html. [Open access]","National Archives and Records Administration, “Declaration of Independence (1776),” Milestone Documents, https://www.archives.gov/milestone-documents/declaration-of-independence. [Open access]","Office of the Historian, U.S. Department of State, “Monroe Doctrine, 1823,” Milestones in the History of U.S. Foreign Relations, https://history.state.gov/milestones/1801-1829/monroe. [Open access]","World Bank, “Population, total: United States,” World Development Indicators, https://api.worldbank.org/v2/country/USA/indicator/SP.POP.TOTL?format=json. [Open access]","World Bank, “Surface area (sq. km): United States,” World Development Indicators, https://api.worldbank.org/v2/country/USA/indicator/AG.SRF.TOTL.K2?format=json. [Open access]"],
"vietnam": ["United Nations Statistics Division, “Viet Nam,” UNdata Country Profile, https://data.un.org/en/iso/vn.html. [Open access]","Office of the Historian, U.S. Department of State, “Vietnam,” A Guide to the United States’ History of Recognition, Diplomatic, and Consular Relations, by Country, since 1776, https://history.state.gov/countries/vietnam. [Open access]","World Bank, “Population, total: Viet Nam,” World Development Indicators, https://api.worldbank.org/v2/country/VNM/indicator/SP.POP.TOTL?format=json. [Open access]","World Bank, “Surface area (sq. km): Viet Nam and the Philippines,” World Development Indicators, https://api.worldbank.org/v2/country/VNM;PHL/indicator/AG.SRF.TOTL.K2?format=json. [Open access]","Office of the Historian, U.S. Department of State, “Ending the Vietnam War, 1969–1973,” Milestones in the History of U.S. Foreign Relations, https://history.state.gov/milestones/1969-1976/ending-vietnam. [Open access]"]
});

window.COUNTRY_YEAR_SOURCES = Object.assign(window.COUNTRY_YEAR_SOURCES || {}, {

});
