/* CROSSWORD — the daily grid's own bank of clues and answers.
   `window.CROSSWORD = [{ a: "<ANSWER>", c: "<clue>" }]`, the sibling of `whatyear.js`, `truefalse.js`
   and `quotes.js`: a minigame with a pool of its own rather than one drawn from the cards.

   WHY IT IS NOT BUILT ON THE CARDS ANY MORE (Sep 2026, on request: "the crossword puzzles should no
   longer use questions from the cards; create completely unique, simple history-based crossword
   puzzles"). It was, and a card question is the wrong shape for a crossword three ways over.

   · A CARD QUESTION IS A CLOZE, not a clue. It is written to be read with a blank in the middle of it
     ("the <span class=\"blank\">_____</span> is the god of the east"), it runs 20 to 34 words by house
     rule, and it carries markup. Set beside a numbered grid, that is a paragraph where a crossword wants
     a phrase.
   · THE ANSWERS WERE WHATEVER THE DECK HAPPENED TO HOLD. The pool was every one-word answer term rated
     inside `GAME_MAX_DIFFICULTY`, which is a set chosen for a completely different purpose — so the grid
     filled with the terms that happen to be one word rather than with the words a crossword wants, and
     the same handful recurred because that is what a small pool does.
   · AND A READER WHO HAD STUDIED THE CARD HAD SEEN THE CLUE. The point of a daily game is a fresh test.

   So the bank is written for this game and nothing else. THE RULES FOR AN ENTRY:

   · THE ANSWER IS ONE WORD, 4 to 11 letters, A-Z only. That is `XW_MIN_LEN`/`XW_MAX_LEN` and what
     `xwNorm` leaves of a string; a two-word answer run together reads as a misprint under a grid that
     prints its enumeration as a single number.
   · THE ANSWER IS WRITTEN IN CAPITALS AND ALREADY NORMALISED — no accents, no punctuation. The game
     normalises anyway, and an entry that has to be transformed before it can be compared is an entry
     nobody can grep for.
   · THE CLUE IS ONE SHORT PHRASE OR SENTENCE. It is emitted RAW rather than through `esc()` (the game
     has always done that, since a card question is authored HTML), so a bare `<`, `>` or `&` must never
     appear in one. Write "and", never an ampersand.
   · IT MAY NOT CONTAIN ITS OWN ANSWER, nor a word sharing its stem. A clue that names what it is asking
     for is a clue already solved.
   · ERAS ARE BCE AND CE, never BC or AD — the house rule, and `check-style.js` reads this file.
   · IT IS SIMPLE. The request asks for simple history, and the grid deals its clues cold with no card
     behind them: a reader who knows the subject in outline should get most of a grid, which is what
     makes the rest worth working at.

   334 entries, spread across world history from Sumer to the fall of the Soviet Union, and across
   the letter lengths the layout search needs — a grid hangs its later words off a long first one, so a
   bank of short words alone will not cross. Not researched to the citation bar the CARDS are held to:
   these are the outline facts of a general history education, which is the level the game plays at. */
window.CROSSWORD = [
{"a":"PHARAOH","c":"The title borne by the rulers of ancient Egypt."},
{"a":"PAPYRUS","c":"The reed the Egyptians beat into sheets to write on."},
{"a":"OBELISK","c":"A tapering four-sided pillar raised outside an Egyptian temple."},
{"a":"SPHINX","c":"The lion-bodied figure with a human head that guards Giza."},
{"a":"MUMMY","c":"A body preserved for the afterlife by Egyptian embalmers."},
{"a":"NILE","c":"The river whose flood laid the silt Egypt's harvests depended on."},
{"a":"CARTOUCHE","c":"The oval ring drawn round a royal name in hieroglyphs."},
{"a":"ROSETTA","c":"The stone whose three scripts unlocked hieroglyphic Egyptian."},
{"a":"PYRAMID","c":"The tomb shape built for Old Kingdom kings at Giza."},
{"a":"SCRIBE","c":"The literate official who kept the records of an ancient state."},
{"a":"ZIGGURAT","c":"The stepped temple platform of Mesopotamian cities."},
{"a":"CUNEIFORM","c":"The wedge-shaped writing pressed into clay in Mesopotamia."},
{"a":"BABYLON","c":"The Mesopotamian city Hammurabi ruled from."},
{"a":"SUMER","c":"The southern Mesopotamian land of the earliest cities."},
{"a":"ASSYRIA","c":"The northern Mesopotamian empire whose capital was Nineveh."},
{"a":"NINEVEH","c":"The Assyrian capital sacked in 612 BCE."},
{"a":"HITTITE","c":"The Anatolian people who fought Egypt at Kadesh."},
{"a":"PHOENICIA","c":"The coastal Levantine land whose traders spread the alphabet."},
{"a":"CARTHAGE","c":"The Phoenician colony Rome destroyed in 146 BCE."},
{"a":"HANNIBAL","c":"The Carthaginian general who crossed the Alps with elephants."},
{"a":"LEGION","c":"The main formation of the Roman army."},
{"a":"CENTURION","c":"The officer who commanded a Roman century."},
{"a":"CONSUL","c":"One of the two annual chief magistrates of the Roman Republic."},
{"a":"SENATE","c":"The council of elders that advised Rome's magistrates."},
{"a":"FORUM","c":"The public square at the centre of a Roman town."},
{"a":"AQUEDUCT","c":"The channel that carried water into a Roman city."},
{"a":"COLOSSEUM","c":"The Flavian amphitheatre at the heart of Rome."},
{"a":"GLADIATOR","c":"A fighter trained to perform in the Roman arena."},
{"a":"CAESAR","c":"The name Julius bore and later emperors took as a title."},
{"a":"AUGUSTUS","c":"The title the Senate gave Octavian in 27 BCE."},
{"a":"PATRICIAN","c":"A member of Rome's hereditary governing families."},
{"a":"PLEBEIAN","c":"An ordinary Roman citizen outside the old noble families."},
{"a":"TRIBUNE","c":"The magistrate elected to protect the Roman plebs."},
{"a":"POMPEII","c":"The town buried by Vesuvius in 79 CE."},
{"a":"VESUVIUS","c":"The volcano that buried Pompeii and Herculaneum."},
{"a":"ROMULUS","c":"The legendary founder Rome was named after."},
{"a":"ETRUSCAN","c":"The people of central Italy who ruled Rome before the Republic."},
{"a":"ACROPOLIS","c":"The fortified height above a Greek city."},
{"a":"PARTHENON","c":"The temple of Athena that crowns the Athenian Acropolis."},
{"a":"AGORA","c":"The market and meeting place of a Greek city."},
{"a":"HOPLITE","c":"The armoured Greek citizen who fought in the phalanx."},
{"a":"PHALANX","c":"The close-packed formation of Greek spearmen."},
{"a":"SPARTA","c":"The Greek city whose citizens were raised as soldiers."},
{"a":"ATHENS","c":"The Greek city credited with the first democracy."},
{"a":"MARATHON","c":"The plain where Athens beat the Persians in 490 BCE."},
{"a":"SALAMIS","c":"The strait where the Greek fleet broke Xerxes' navy."},
{"a":"THERMOPYLAE","c":"The pass Leonidas held against the Persian army."},
{"a":"OSTRACISM","c":"The Athenian vote that banished a citizen for ten years."},
{"a":"ORACLE","c":"The prophetic voice consulted at Delphi."},
{"a":"DELPHI","c":"The sanctuary of Apollo where Greeks sought prophecy."},
{"a":"OLYMPIA","c":"The sanctuary where the Greek games were held every four years."},
{"a":"TRIREME","c":"The three-banked warship of the classical Greek navies."},
{"a":"HELOT","c":"The enslaved farmer of the Spartan state."},
{"a":"TYRANT","c":"A Greek ruler who seized power outside the usual laws."},
{"a":"SOCRATES","c":"The Athenian philosopher condemned to drink hemlock."},
{"a":"PLATO","c":"The philosopher who founded the Academy at Athens."},
{"a":"ARISTOTLE","c":"The philosopher who tutored Alexander the Great."},
{"a":"HOMER","c":"The poet credited with the Iliad and the Odyssey."},
{"a":"ILIAD","c":"Homer's poem of the wrath of Achilles at Troy."},
{"a":"ODYSSEY","c":"Homer's poem of a long voyage home from Troy."},
{"a":"HERODOTUS","c":"The Greek writer called the father of history."},
{"a":"ALEXANDER","c":"The Macedonian king who reached the Indus."},
{"a":"MACEDON","c":"The northern kingdom Philip and Alexander ruled."},
{"a":"HELLENISTIC","c":"The age of Greek-speaking kingdoms after Alexander."},
{"a":"PERSIA","c":"The empire Cyrus founded and Alexander overthrew."},
{"a":"SATRAP","c":"The provincial governor of the Persian empire."},
{"a":"CYRUS","c":"The Persian king who took Babylon in 539 BCE."},
{"a":"DARIUS","c":"The Persian king defeated at Marathon."},
{"a":"XERXES","c":"The Persian king whose fleet lost at Salamis."},
{"a":"CARAVAN","c":"The company of merchants and pack animals crossing a desert."},
{"a":"CONFUCIUS","c":"The Chinese teacher whose sayings fill the Analects."},
{"a":"ANALECTS","c":"The collected sayings of Confucius."},
{"a":"DYNASTY","c":"A line of rulers from one family."},
{"a":"MANDARIN","c":"A senior official of imperial China."},
{"a":"EUNUCH","c":"A castrated official of the Chinese or Ottoman court."},
{"a":"TERRACOTTA","c":"The fired clay of the buried army at Xian."},
{"a":"GUNPOWDER","c":"The Chinese invention of saltpetre, charcoal and sulphur."},
{"a":"COMPASS","c":"The magnetic instrument Chinese sailors used to steer by."},
{"a":"PORCELAIN","c":"The fine white ceramic first fired in China."},
{"a":"JUNK","c":"The flat-bottomed Chinese sailing ship."},
{"a":"SHANG","c":"The Chinese dynasty of the oracle bones."},
{"a":"MANCHU","c":"The people from the northeast who founded China's last dynasty."},
{"a":"TANG","c":"The Chinese dynasty whose capital was Changan."},
{"a":"SONG","c":"The Chinese dynasty that printed with movable type."},
{"a":"MING","c":"The Chinese dynasty that sent Zheng He to sea."},
{"a":"QING","c":"The last imperial dynasty of China."},
{"a":"SAMURAI","c":"The warrior class of feudal Japan."},
{"a":"SHOGUN","c":"The military ruler who governed Japan in the emperor's name."},
{"a":"BUSHIDO","c":"The code of conduct expected of a samurai."},
{"a":"KATANA","c":"The curved sword carried by a samurai."},
{"a":"SHINTO","c":"The indigenous religion of Japan."},
{"a":"KYOTO","c":"The Japanese capital for over a thousand years."},
{"a":"MEIJI","c":"The Japanese restoration that ended the shogunate."},
{"a":"BUDDHISM","c":"The religion founded by Siddhartha Gautama."},
{"a":"NIRVANA","c":"The release from rebirth sought in Buddhism."},
{"a":"STUPA","c":"The domed mound built over Buddhist relics."},
{"a":"ASHOKA","c":"The Mauryan emperor who turned to Buddhism after Kalinga."},
{"a":"MAURYA","c":"The Indian dynasty Chandragupta founded."},
{"a":"GUPTA","c":"The Indian dynasty of the classical golden age."},
{"a":"SANSKRIT","c":"The classical literary language of India."},
{"a":"VEDA","c":"One of the oldest sacred texts of India."},
{"a":"MONSOON","c":"The seasonal wind that brings India its rains."},
{"a":"HARAPPA","c":"One of the great cities of the Indus civilisation."},
{"a":"INDUS","c":"The river whose valley held a Bronze Age civilisation."},
{"a":"MUGHAL","c":"The Muslim dynasty that ruled much of India from Delhi."},
{"a":"AKBAR","c":"The Mughal emperor remembered for religious tolerance."},
{"a":"AGRA","c":"The city on the Yamuna where Shah Jahan built a marble tomb."},
{"a":"CALIPH","c":"The title of the successor to Muhammad as leader of Islam."},
{"a":"MOSQUE","c":"The building where Muslims gather to pray."},
{"a":"MINARET","c":"The tower from which the call to prayer is made."},
{"a":"QURAN","c":"The scripture of Islam."},
{"a":"MECCA","c":"The city Muslims face in prayer."},
{"a":"MEDINA","c":"The city Muhammad moved to in 622."},
{"a":"HIJRA","c":"Muhammad's migration from Mecca, from which Muslims count years."},
{"a":"BAGHDAD","c":"The Abbasid capital founded on the Tigris in 762."},
{"a":"ABBASID","c":"The caliphate that ruled from Baghdad."},
{"a":"UMAYYAD","c":"The caliphate that ruled from Damascus."},
{"a":"CORDOBA","c":"The Andalusian city famous for its great mosque."},
{"a":"CRUSADE","c":"A medieval Christian military expedition to the Holy Land."},
{"a":"SALADIN","c":"The sultan who retook Jerusalem in 1187."},
{"a":"JERUSALEM","c":"The city holy to Jews, Christians and Muslims alike."},
{"a":"BYZANTINE","c":"The eastern Roman empire ruled from Constantinople."},
{"a":"BYZANTIUM","c":"The Greek colony that later became Constantinople."},
{"a":"JUSTINIAN","c":"The emperor who had the Roman law codified."},
{"a":"MOSAIC","c":"A picture made from small pieces of coloured glass or stone."},
{"a":"OTTOMAN","c":"The Turkish empire that took Constantinople in 1453."},
{"a":"JANISSARY","c":"The elite infantry soldier of the Ottoman sultan."},
{"a":"SULTAN","c":"The title of the Ottoman ruler."},
{"a":"VIZIER","c":"The chief minister of a Muslim ruler."},
{"a":"FEUDAL","c":"The medieval system of land held in return for service."},
{"a":"VASSAL","c":"A man who held land from a lord in return for service."},
{"a":"MANOR","c":"The estate at the centre of medieval rural life."},
{"a":"SERF","c":"A peasant bound to the land he worked."},
{"a":"KNIGHT","c":"The mounted warrior of medieval Europe."},
{"a":"CHIVALRY","c":"The code of conduct expected of a knight."},
{"a":"CASTLE","c":"The fortified residence of a medieval lord."},
{"a":"MOAT","c":"The water-filled ditch dug round a castle."},
{"a":"DRAWBRIDGE","c":"The bridge that could be raised to seal a castle gate."},
{"a":"KEEP","c":"The strong central tower of a castle."},
{"a":"MONASTERY","c":"The house where monks lived under a rule."},
{"a":"ABBOT","c":"The head of a monastery."},
{"a":"FRIAR","c":"A member of a preaching order who lived on alms."},
{"a":"TITHE","c":"The tenth of his produce a peasant owed the Church."},
{"a":"CATHEDRAL","c":"The church that holds a bishop's seat."},
{"a":"GOTHIC","c":"The medieval style of pointed arches and flying buttresses."},
{"a":"BUTTRESS","c":"The masonry support that takes the thrust of a high wall."},
{"a":"CLOISTER","c":"The covered walk round a monastery courtyard."},
{"a":"ILLUMINATED","c":"Describing a manuscript decorated with gold and colour."},
{"a":"VELLUM","c":"The prepared calfskin medieval scribes wrote on."},
{"a":"VIKING","c":"The Norse seafarer who raided and traded across Europe."},
{"a":"LONGSHIP","c":"The shallow-drafted vessel the Vikings sailed and rowed."},
{"a":"RUNE","c":"A letter of the old Germanic alphabet."},
{"a":"SAGA","c":"A Norse prose narrative of families or kings."},
{"a":"DANELAW","c":"The part of England where Danish law ran."},
{"a":"NORMAN","c":"The people from northern France who conquered England in 1066."},
{"a":"HASTINGS","c":"The battle that gave England to William in 1066."},
{"a":"DOMESDAY","c":"The survey of England William ordered in 1085."},
{"a":"CHARTER","c":"The document by which a king granted rights to his subjects."},
{"a":"BARON","c":"A great landholder who held directly from the king."},
{"a":"PARLIAMENT","c":"The assembly that grew into England's legislature."},
{"a":"PLAGUE","c":"The disease that killed a third of Europe after 1347."},
{"a":"FLAGELLANT","c":"A penitent who whipped himself during the Black Death."},
{"a":"GUILD","c":"The association that controlled a medieval craft or trade."},
{"a":"APPRENTICE","c":"A youth bound to learn a trade from a master."},
{"a":"HANSA","c":"The league of north German trading towns."},
{"a":"CRUSADER","c":"A Christian who took the cross to fight in the east."},
{"a":"INQUISITION","c":"The Church court set up to try heresy."},
{"a":"HERESY","c":"Religious opinion the Church condemned as false."},
{"a":"ANATHEMA","c":"The formal curse by which the Church cut a person off."},
{"a":"RENAISSANCE","c":"The rebirth of classical learning and art in Europe."},
{"a":"FLORENCE","c":"The Tuscan city where the Renaissance began."},
{"a":"MEDICI","c":"The banking family that ruled Renaissance Florence."},
{"a":"FRESCO","c":"A painting made on wet plaster."},
{"a":"PATRON","c":"The wealthy backer who paid for a work of art."},
{"a":"HUMANISM","c":"The Renaissance study of classical texts and human affairs."},
{"a":"PRINTING","c":"Gutenberg's invention that spread books across Europe."},
{"a":"GUTENBERG","c":"The Mainz goldsmith who printed with movable metal type."},
{"a":"REFORMATION","c":"The sixteenth-century split in western Christianity."},
{"a":"LUTHER","c":"The monk whose theses opened the Reformation in 1517."},
{"a":"INDULGENCE","c":"The remission of penance whose sale Luther attacked."},
{"a":"PROTESTANT","c":"A Christian of the churches that broke with Rome."},
{"a":"CALVIN","c":"The reformer whose Geneva became a Protestant model."},
{"a":"PURITAN","c":"An English Protestant who wanted the Church purified further."},
{"a":"HUGUENOT","c":"A French Protestant of the sixteenth century."},
{"a":"JESUIT","c":"A member of the Society of Jesus."},
{"a":"ARMADA","c":"The Spanish fleet England scattered in 1588."},
{"a":"CARAVEL","c":"The small fast ship of the Portuguese voyages."},
{"a":"ASTROLABE","c":"The instrument sailors used to take the sun's altitude."},
{"a":"SEXTANT","c":"The instrument that measures the angle of a star above the horizon."},
{"a":"MAGELLAN","c":"The captain whose expedition first circled the world."},
{"a":"COLUMBUS","c":"The Genoese sailor who crossed the Atlantic in 1492."},
{"a":"ENCOMIENDA","c":"The Spanish grant of native labour in the Americas."},
{"a":"CORTES","c":"The Spaniard who overthrew the Aztec empire."},
{"a":"PIZARRO","c":"The Spaniard who overthrew the Inca empire."},
{"a":"AZTEC","c":"The people whose capital was Tenochtitlan."},
{"a":"INCA","c":"The Andean empire ruled from Cuzco."},
{"a":"MAYA","c":"The Mesoamerican people who built Tikal and Palenque."},
{"a":"CHINAMPA","c":"The raised garden bed the Aztecs farmed on the lake."},
{"a":"CUZCO","c":"The Inca capital high in the Andes."},
{"a":"QUIPU","c":"The knotted cords the Inca kept records on."},
{"a":"TERRACE","c":"The stepped platform cut into a hillside for farming."},
{"a":"MONOPOLY","c":"The exclusive trading right a chartered company held."},
{"a":"GALLEON","c":"The large armed sailing ship of Spain's treasure fleets."},
{"a":"PLANTATION","c":"The large estate worked by forced labour in the colonies."},
{"a":"ABOLITION","c":"The movement to end the slave trade and slavery."},
{"a":"WILBERFORCE","c":"The MP who led the campaign against the British slave trade."},
{"a":"AMISTAD","c":"The slave ship whose captives won their freedom in a US court."},
{"a":"UNDERGROUND","c":"With Railroad, the network that helped enslaved Americans escape."},
{"a":"MUSKET","c":"The smoothbore shoulder gun of early modern armies."},
{"a":"BAYONET","c":"The blade fixed to a musket's muzzle."},
{"a":"CANNON","c":"The heavy gun that brought down medieval walls."},
{"a":"PIKE","c":"The long spear carried beside musketeers in early modern armies."},
{"a":"CAVALRY","c":"Soldiers who fight on horseback."},
{"a":"INFANTRY","c":"Soldiers who fight on foot."},
{"a":"ARTILLERY","c":"The branch of an army that serves the guns."},
{"a":"SIEGE","c":"The surrounding of a fortified place to force its surrender."},
{"a":"TREATY","c":"A formal agreement between states."},
{"a":"ARMISTICE","c":"An agreement to stop fighting."},
{"a":"BLOCKADE","c":"The sealing of a port or coast to stop supplies."},
{"a":"PHILOSOPHE","c":"A French thinker of the eighteenth-century Enlightenment."},
{"a":"VOLTAIRE","c":"The French writer who attacked intolerance and censorship."},
{"a":"ROUSSEAU","c":"The author of The Social Contract."},
{"a":"DIDEROT","c":"The editor of the great French Encyclopedie."},
{"a":"BASTILLE","c":"The Paris fortress stormed on 14 July 1789."},
{"a":"GUILLOTINE","c":"The machine of the French Revolution's executions."},
{"a":"JACOBIN","c":"A member of the radical club of the French Revolution."},
{"a":"ROBESPIERRE","c":"The Jacobin who fell with the end of the Terror."},
{"a":"NAPOLEON","c":"The general who crowned himself emperor of the French."},
{"a":"WATERLOO","c":"The battle that ended Napoleon's rule in 1815."},
{"a":"TRAFALGAR","c":"The sea battle where Nelson broke the Franco-Spanish fleet."},
{"a":"NELSON","c":"The admiral killed at Trafalgar."},
{"a":"WELLINGTON","c":"The general who commanded the allies at Waterloo."},
{"a":"CONGRESS","c":"With Vienna, the settlement that redrew Europe after Napoleon."},
{"a":"BOSTON","c":"With Tea Party, the 1773 protest against a British tax."},
{"a":"LEXINGTON","c":"Where the first shots of the American Revolution were fired."},
{"a":"YORKTOWN","c":"Where Cornwallis surrendered in 1781."},
{"a":"DECLARATION","c":"The document adopted by Congress on 4 July 1776."},
{"a":"JEFFERSON","c":"The main author of the Declaration of Independence."},
{"a":"FRANKLIN","c":"The American who won France's alliance in the Revolution."},
{"a":"AMENDMENT","c":"A formal change added to a constitution."},
{"a":"FEDERALIST","c":"A supporter of the stronger union proposed in 1787."},
{"a":"LOUISIANA","c":"The territory the United States bought from France in 1803."},
{"a":"FRONTIER","c":"The moving edge of American settlement in the west."},
{"a":"HOMESTEAD","c":"The act that granted western land to settlers who farmed it."},
{"a":"SECESSION","c":"The withdrawal of the southern states from the Union."},
{"a":"CONFEDERACY","c":"The states that left the Union in 1860 and 1861."},
{"a":"GETTYSBURG","c":"The 1863 battle and the address Lincoln gave there."},
{"a":"LINCOLN","c":"The president who led the Union through the Civil War."},
{"a":"APPOMATTOX","c":"Where Lee surrendered to Grant in 1865."},
{"a":"FREEDMEN","c":"The people freed from slavery after the American Civil War."},
{"a":"SUFFRAGE","c":"The right to vote."},
{"a":"SUFFRAGETTE","c":"A woman who campaigned militantly for the vote in Britain."},
{"a":"CHARTIST","c":"A supporter of the 1830s British campaign for the People's Charter."},
{"a":"INDUSTRIAL","c":"With Revolution, the change from hand work to machines."},
{"a":"FACTORY","c":"The building where machines and workers were gathered together."},
{"a":"SPINNING","c":"With jenny, Hargreaves' machine for making thread."},
{"a":"LOOM","c":"The machine on which cloth is woven."},
{"a":"STEAM","c":"The power that drove the first factories and railways."},
{"a":"LOCOMOTIVE","c":"The engine that pulls a train."},
{"a":"RAILWAY","c":"The iron road that transformed nineteenth-century travel."},
{"a":"CANAL","c":"The artificial waterway dug to carry goods by barge."},
{"a":"TELEGRAPH","c":"The invention that sent messages down a wire."},
{"a":"DYNAMO","c":"The machine that turns motion into electric current."},
{"a":"UNION","c":"The organisation workers formed to bargain with employers."},
{"a":"STRIKE","c":"A refusal to work, used to press a demand."},
{"a":"SOCIALISM","c":"The belief that the means of production should be held in common."},
{"a":"MARX","c":"The author of Das Kapital."},
{"a":"CAPITAL","c":"The title of Marx's great work on political economy."},
{"a":"COMMUNE","c":"The revolutionary government that held Paris in 1871."},
{"a":"IMPERIALISM","c":"The extension of one state's rule over other lands."},
{"a":"COLONY","c":"A territory settled or governed by a distant power."},
{"a":"SCRAMBLE","c":"With for Africa, the European partition of the continent."},
{"a":"BERLIN","c":"The 1884 conference that set rules for dividing Africa."},
{"a":"SUEZ","c":"The canal that shortened the route from Europe to Asia."},
{"a":"DOMINION","c":"A self-governing territory of the British Empire."},
{"a":"SEPOY","c":"An Indian soldier in the service of a European power."},
{"a":"GANDHI","c":"The leader of India's non-violent independence movement."},
{"a":"SATYAGRAHA","c":"Gandhi's term for non-violent resistance."},
{"a":"PARTITION","c":"The 1947 division of British India into two states."},
{"a":"NEHRU","c":"India's first prime minister."},
{"a":"APARTHEID","c":"South Africa's system of enforced racial separation."},
{"a":"MANDELA","c":"The prisoner who became South Africa's president in 1994."},
{"a":"TRENCH","c":"The ditch soldiers fought and lived in on the Western Front."},
{"a":"SOMME","c":"The 1916 battle on the Western Front with vast British losses."},
{"a":"VERDUN","c":"The 1916 battle the French fought to hold at all costs."},
{"a":"YPRES","c":"The Belgian town fought over three times in the First World War."},
{"a":"GALLIPOLI","c":"The failed Allied landing on the Dardanelles in 1915."},
{"a":"ZEPPELIN","c":"The German airship that bombed Britain in the First World War."},
{"a":"SUBMARINE","c":"The vessel whose unrestricted warfare helped bring America in."},
{"a":"VERSAILLES","c":"The 1919 treaty that settled terms with Germany."},
{"a":"LEAGUE","c":"With of Nations, the body set up in 1920 to keep the peace."},
{"a":"BOLSHEVIK","c":"The faction that seized power in Russia in 1917."},
{"a":"LENIN","c":"The Bolshevik leader who returned to Russia in 1917."},
{"a":"SOVIET","c":"Originally a workers' council; later the Russian state's name."},
{"a":"TSAR","c":"The title of the Russian emperor."},
{"a":"RASPUTIN","c":"The holy man whose influence damaged the last tsar's court."},
{"a":"STALIN","c":"The Soviet leader who ordered the Five-Year Plans."},
{"a":"KOLKHOZ","c":"The collective farm of the Soviet countryside."},
{"a":"GULAG","c":"The Soviet system of forced-labour camps."},
{"a":"FASCISM","c":"The authoritarian nationalist movement Mussolini founded."},
{"a":"MUSSOLINI","c":"The Italian dictator who marched on Rome in 1922."},
{"a":"NAZI","c":"The party that took power in Germany in 1933."},
{"a":"REICHSTAG","c":"The German parliament whose burning followed Hitler's rise."},
{"a":"APPEASEMENT","c":"The policy of conceding to Hitler's demands to avoid war."},
{"a":"MUNICH","c":"The 1938 agreement that handed Germany the Sudetenland."},
{"a":"ANSCHLUSS","c":"Germany's 1938 annexation of Austria."},
{"a":"BLITZKRIEG","c":"The fast combined-arms attack of the German army in 1939."},
{"a":"DUNKIRK","c":"The 1940 evacuation of Allied troops from a French beach."},
{"a":"BLITZ","c":"The German bombing of British cities in 1940 and 1941."},
{"a":"RADAR","c":"The invention that gave Britain warning of incoming aircraft."},
{"a":"ENIGMA","c":"The German cipher machine broken at Bletchley Park."},
{"a":"BLETCHLEY","c":"The English house where Allied codebreakers worked."},
{"a":"STALINGRAD","c":"The 1942 battle that turned the war in the east."},
{"a":"NORMANDY","c":"The coast the Allies landed on in June 1944."},
{"a":"HOLOCAUST","c":"The Nazi murder of six million Jews."},
{"a":"AUSCHWITZ","c":"The largest of the Nazi extermination camps."},
{"a":"NUREMBERG","c":"The city where Nazi leaders were tried after the war."},
{"a":"HIROSHIMA","c":"The first city destroyed by an atomic bomb."},
{"a":"MANHATTAN","c":"With Project, the American programme that built the atom bomb."},
{"a":"DETENTE","c":"The easing of tension between the superpowers in the 1970s."},
{"a":"CONTAINMENT","c":"The American policy of holding Soviet power where it stood."},
{"a":"CHURCHILL","c":"The prime minister who led Britain through the Second World War."},
{"a":"MARSHALL","c":"The American plan that funded Europe's post-war recovery."},
{"a":"NATO","c":"The western alliance founded in 1949."},
{"a":"WARSAW","c":"With Pact, the eastern military alliance formed in 1955."},
{"a":"AIRLIFT","c":"The flights that supplied West Berlin through the 1948 blockade."},
{"a":"CUBA","c":"The island of the 1962 missile crisis."},
{"a":"SPUTNIK","c":"The first artificial satellite, launched in 1957."},
{"a":"APOLLO","c":"The American programme that landed men on the moon."},
{"a":"MANDATE","c":"A territory a League of Nations member governed on its behalf."},
{"a":"GLASNOST","c":"Gorbachev's policy of greater openness."},
{"a":"PERESTROIKA","c":"Gorbachev's policy of restructuring the Soviet economy."},
{"a":"GORBACHEV","c":"The last leader of the Soviet Union."},
{"a":"SOLIDARITY","c":"The Polish trade union that challenged communist rule."}
];
