/* Glossary tooltip descriptions, keyed by Wikipedia article slug (decoded). Add terms one at a time with
   `node .claude/add-glossary.js <entry.json>` (see CLAUDE.md). Missing terms fall back to the slug name. */
window.GLOSSARY = {
"Sima_Qian": "The Han historian (c. 145–86 BCE) regarded as the father of Chinese historiography. His <i>Records of the Grand Historian</i> set the form for the official histories of every later dynasty. He famously chose mutilation over death in order to finish his work.",
"Paleolithic": "The Paleolithic, or Old Stone Age, is the earliest and by far the longest phase of the Stone Age, spanning most of human prehistory. It began with the first use of stone tools by early humans and lasted until the end of the last Ice Age, throughout which people lived as nomadic hunter-gatherers. Stretching over millions of years, it encompasses the emergence and spread of the human species.",
"Stone_Age": "The Stone Age is the earliest and by far the longest prehistoric period, the first stage of the three-age system, defined by the manufacture of stone tools before the working of metals. It spans roughly the first 99 percent of human history, beginning with the oldest known stone tools and ending with the advent of metallurgy. Its boundaries vary by region, ending around 4000 to 2000 BCE in different areas as societies entered the Bronze Age or, in parts of Africa, passed directly to iron.",
"Bronze_Age": "The middle period of the three-age archaeological system, falling between the Stone Age and the Iron Age. It is defined by the widespread use of bronze, an alloy of copper and tin, and coincided with the rise of writing, cities, and complex states in regions such as Mesopotamia and Egypt. Because it is marked by technology rather than a fixed date, its span varies by region, beginning around 3300 BCE in the Near East and arriving later elsewhere.",
"Iron_Age": "The Iron Age is the final stage of the three-age system, a prehistoric and protohistoric period defined by the widespread smelting and working of iron and steel for tools and weapons. It followed the Bronze Age, as iron implements gradually replaced bronze ones once techniques for removing impurities and controlling carbon content were mastered. Its onset varies widely by region, beginning near the Bronze Age collapse in the Near East and centuries later in Europe.",
"Ice_Age": "An ice age is a long period in the history of the Earth during which global temperatures fall and continental ice sheets and mountain glaciers spread across large parts of the planet. Geologists recognize at least five major ice ages over the past 2.4 billion years, each lasting many millions of years and alternating between colder glacial phases and milder interglacial phases; the current one began about 2.58 million years ago and continues today, since vast ice sheets still cover Antarctica and Greenland. In everyday usage the Ice Age generally means the most recent glacial phase, which reached its coldest point around 20,000 years ago and ended about 11,700 years ago.",
"Middle_Paleolithic": "The Middle Paleolithic is the middle subdivision of the Old Stone Age, spanning roughly 300,000 to 50,000 years ago across Europe, the Near East, and much of Asia. It is defined largely by prepared-core knapping methods such as the Levallois technique, which yielded more standardized flakes and supported the first composite tools like hafted stone-tipped spears. The period is associated with Neanderthals and early anatomically modern humans, and it produced some of the earliest known deliberate burials of the dead.",
"Upper_Paleolithic": "The Upper Paleolithic is the final subdivision of the Paleolithic, lasting from roughly 50,000 to 12,000 years ago and ending with the close of the last Ice Age. It is associated with the spread of anatomically modern humans across most of the world and with a marked increase in the variety and refinement of stone tools, especially long, narrow blades struck from prepared cores together with specialised implements of bone, antler, and ivory. The period also saw the first widespread figurative art, including cave paintings, engravings, carved animal and human figurines, and personal ornaments.",
"Three-age_system": "The three-age system is a framework that divides prehistory into three successive periods, the Stone Age, the Bronze Age, and the Iron Age, each defined by the material that dominated tool and weapon making. The Danish antiquarian Christian Jürgensen Thomsen worked it out from 1816 while sorting the prehistoric collection in Copenhagen that grew into the National Museum of Denmark, and set it out in a museum guidebook published in 1836. Later research added refinements such as the Copper Age and finer subdivisions, and although the scheme fits regions such as the Americas and sub-Saharan Africa poorly, it remains the backbone of prehistoric chronology in Europe and the Near East.",
"Knapping": "Knapping is the technique of shaping stone by striking flakes from a core with a hammerstone or with a softer hammer of antler, bone, or hard wood, and by pressing flakes off the edge with a pointed tool in the method known as pressure flaking. It relies on fine-grained stones such as flint, chert, and obsidian, which break with a smooth, predictable conchoidal fracture that lets the worker control the size and shape of each flake. The technique dates back to the earliest stone tools of prehistory and produced handaxes, blades, scrapers, and arrowheads; in more recent centuries knappers also made gunflints for firearms and shaped flint for building.",
"Hunter-gatherer": "A hunter-gatherer is a member of a society that obtains its food by hunting wild animals, fishing, and gathering wild plants, fruits, and other edible resources. All humans lived this way for the overwhelming majority of their existence, until the adoption of agriculture beginning roughly 12,000 years ago, so foraging accounts for well over 90 percent of human history. Hunter-gatherer groups were typically mobile, living in small bands of a few dozen people that shared food widely under flexible and largely egalitarian leadership, and a small number of communities around the world still follow this way of life today.",
"Lower_Paleolithic": "The Lower Paleolithic is the earliest and longest subdivision of the Paleolithic, extending from the first known stone tools around 3.3 million years ago to roughly 300,000 years ago. It was the age of early hominins such as Homo habilis, Homo erectus, and Homo heidelbergensis, who made the simple flaked cores and choppers of the Oldowan industry and later the bifacial hand axes of the Acheulean. Some of the earliest evidence for the controlled use of fire also belongs to this period, marking a major step in human technological and behavioural development.",
"Pleistocene": "The Pleistocene is the geological epoch spanning roughly 2.58 million to 11,700 years ago, the first epoch of the Quaternary Period. It was marked by repeated cycles of glaciation, the ice ages, during which vast sheets of ice spread across large parts of the Northern Hemisphere and sea levels fell sharply. The epoch saw the rise of large mammals such as mammoths, many of which later went extinct, along with the evolution of anatomically modern humans and their spread across nearly every continent.",
"Archaeology": "Archaeology is the study of human history and prehistory through the excavation and analysis of material remains. It examines artifacts, architecture, and other physical evidence to understand how past peoples lived. It is especially valuable for prehistoric societies that left no written records.",
"Megafauna": "Megafauna are the large animals of a given region or geological period, conventionally those whose adult body mass exceeds a set threshold, most often placed at about 44 kilograms, although proposed limits range from roughly 10 kilograms to well over 1,000 kilograms. The Pleistocene epoch supported an especially rich megafauna, among them mammoths, mastodons, giant ground sloths and woolly rhinoceroses. Many of these large animals died out toward the end of the last Ice Age, in a wave of extinctions that most researchers attribute to a combination of climatic change and human hunting, though the relative weight of each cause remains debated.",
"Australopithecus": "<i>Australopithecus</i> is an extinct genus of early hominins that lived in Africa between roughly 4.2 and 2 million years ago, walking upright on two legs while keeping a small, ape-sized brain. Among its best-known fossils is the roughly 3.2-million-year-old partial skeleton nicknamed Lucy, a member of the species <i>Australopithecus afarensis</i>. The genus is widely regarded as ancestral to, or closely related to, the human genus <i>Homo</i>.",
"Sonia_Harmand": "Sonia Harmand is a French archaeologist and lithic technologist whose work focuses on the earliest stone tools and the origins of tool-making. She has led the West Turkana Archaeological Project in northern Kenya since 2012, dividing her career between the Centre National de la Recherche Scientifique in France and Stony Brook University in New York. In 2011 her team found flaked stone artifacts at the site of Lomekwi 3 that were dated to 3.3 million years ago, about 700,000 years older than any previously known, pushing the start of the archaeological record back before the appearance of the genus <i>Homo</i>.",
"Jason_E._Lewis": "Jason E. Lewis is an American paleoanthropologist whose research spans the earliest stone tools, the fossil record of eastern Africa, and the history of physical anthropology. Based at Stony Brook University and its Turkana Basin Institute, he co-directs the West Turkana Archaeological Project in northern Kenya. He was a co-discoverer of the 3.3-million-year-old artifacts at Lomekwi 3, the oldest stone tools yet found, and he also led a re-measurement of the 19th-century collection of human skulls assembled by Samuel George Morton, which challenged the widely repeated claim that Morton had skewed his data.",
"Greece": "Greece is a country in southeastern Europe occupying the southern end of the Balkan peninsula together with several thousand islands in the Aegean, Ionian and Mediterranean seas. Mountains cover about four-fifths of its territory and its deeply indented coastline is the longest of any country in the Mediterranean basin, conditions that favored seafaring and left inland communities divided by hard terrain. Its ancient city-states produced the earliest known democratic government along with lasting traditions of philosophy, drama, mathematics and historical writing, while the modern Greek state grew out of a war of independence against Ottoman rule and was recognized as sovereign in 1830.",
"John_Lubbock,_1st_Baron_Avebury": "John Lubbock, from 1900 the 1st Baron Avebury, was a British banker, member of parliament and naturalist who helped turn the study of prehistory into a scientific discipline. His survey <i>Pre-historic Times</i>, published in 1865 and revised through seven editions, introduced the terms Paleolithic and Neolithic for the earlier and later phases of the Stone Age, and both remain in everyday use. In parliament he carried the act that gave ancient monuments their first legal protection in Britain and the act that created the country's first statutory public holidays, which were popularly called St Lubbock's Days.",
"Neanderthal": "Neanderthals, classified as <i>Homo neanderthalensis</i>, were a population of archaic humans who lived across Europe and western and central Asia from at least 400,000 years ago until roughly 40,000 years ago. They take their name from the Neander valley near Düsseldorf, where a partial skeleton found in 1856 became the type specimen of the species, and the hundreds of fossils recovered since show a stocky, powerfully built body with a large braincase and prominent brow ridges. They made prepared-core stone tools, hunted large game, controlled fire and buried some of their dead, and genetic evidence shows they interbred with the ancestors of people living today, leaving a small proportion of Neanderthal DNA in most present-day populations outside Africa.",
"Homo_sapiens": "<i>Homo sapiens</i> is the species to which all living people belong and the only surviving member of the human genus <i>Homo</i>. Fossils combining the modern small face, rounded braincase and distinct chin appear in Africa by about 300,000 years ago, though these features seem to have emerged piecemeal in populations spread across the continent rather than all at once in a single place. Members of the species later settled every continent and are associated with symbolic art, complex language, and eventually agriculture, cities and writing.",
"Homo_erectus": "<i>Homo erectus</i> is an extinct species of early human that appeared in Africa about 2 million years ago and survived on the island of Java until roughly 110,000 years ago, making it one of the longest-lived species in the human genus. It was the first known human with body proportions close to those of people today, having long legs, short arms and a narrow trunk suited to walking and running across open country. It was also the first human species known to have spread beyond Africa, reaching eastern and southeastern Asia, and its African sites yield the teardrop-shaped hand axes of the Acheulean industry along with some of the earliest evidence for the controlled use of fire.",
"Oldowan": "The Oldowan is the earliest widespread stone tool industry, made across much of Africa and later in parts of Eurasia from roughly 2.6 million years ago until about 1.7 million years ago, with recent finds in Kenya suggesting an origin closer to 2.9 million. Its toolkit is simple: rounded cores struck a few times with a hammerstone to produce sharp-edged flakes, together with the choppers and battered stones left behind, all used for cutting meat from carcasses, breaking bones for marrow and pounding plant food. It takes its name from Olduvai Gorge in Tanzania, where Louis Leakey identified such tools in the 1930s, and the hominins who made it are thought to include <i>Homo habilis</i>, early <i>Homo erectus</i> and possibly <i>Paranthropus</i>.",
"Acheulean": "The Acheulean is a stone tool industry defined by the large bifacial hand axe, a core worked on both faces into a symmetrical oval or teardrop shape with a continuous cutting edge, usually accompanied by cleavers, picks and the flakes struck off in shaping them. It began in Africa about 1.7 million years ago and lasted until somewhere between 200,000 and 130,000 years ago depending on the region, which makes it the longest-running toolmaking tradition known, and its products are found across Africa, the Middle East, Europe and southern Asia. Named after the gravels of Saint-Acheul near Amiens in northern France, where such tools were recovered in the 1850s, it is attributed mainly to <i>Homo erectus</i> and later <i>Homo heidelbergensis</i>.",
"Neolithic": "The Neolithic, or New Stone Age, is the final phase of the Stone Age, in which people came to depend on cultivated crops and domesticated animals rather than on wild food alone. Its characteristic traits are permanent villages, pottery, weaving, and stone tools finished by grinding and polishing instead of flaking alone, and it is the phase in which the first monumental structures and the first clear signs of social ranking appear. Because farming was taken up at different times in different places, the period has no single span: it begins around 10,000 BCE in the Middle East and only in the 3rd millennium BCE elsewhere, ending wherever metalworking took hold.",
"Mesolithic": "The Mesolithic is a phase of the Stone Age falling between the Paleolithic and the Neolithic, covering the hunter-gatherer societies that adapted to the warmer, wetter conditions after the last Ice Age. Its tools are dominated by microliths, small blades and points struck from carefully prepared cores and set into wooden or bone hafts to make arrows, harpoons and composite knives, and its sites show heavy use of fish, shellfish, waterfowl and hazelnuts, along with domesticated dogs and some of the oldest boats known. The term was introduced by the antiquarian Hodder Westropp in 1866 and is used mainly for Europe, since the sequence it describes fits some regions poorly: the equivalent period in the Levant is usually called the Epipalaeolithic, and in Africa the label is rarely applied at all."
};

/* Optional date shown next to a term (e.g. "c. 145-86 BCE", "1644-1912"). Keyed by the same slug. */
window.GLOSSARY_DATES = Object.assign(window.GLOSSARY_DATES || {}, {
"Sima_Qian": "c. 145–86 BCE",
"Paleolithic": "c. 3.3 Mya–10,000 BCE",
"Stone_Age": "c. 3.3 Mya - 3300 BCE",
"Bronze_Age": "c. 3300–1200 BCE",
"Iron_Age": "from c. 1200 BCE",
"Middle_Paleolithic": "c. 300,000 - 50,000 BP",
"Upper_Paleolithic": "c. 50,000 - 12,000 BP",
"Lower_Paleolithic": "c. 3.3 Mya – 300,000 BP",
"Pleistocene": "c. 2.58 Mya – 11,700 BP",
"Australopithecus": "c. 4.2 - 2 Mya",
"Sonia_Harmand": "b. 1974",
"John_Lubbock,_1st_Baron_Avebury": "1834–1913",
"Neanderthal": "c. 400,000 – 40,000 BP",
"Homo_sapiens": "from c. 300,000 BP",
"Homo_erectus": "c. 2 Mya – 110,000 BP",
"Oldowan": "c. 2.6 – 1.7 Mya",
"Acheulean": "c. 1.7 Mya – 130,000 BP",
"Neolithic": "c. 10,000 – 3000 BCE",
"Mesolithic": "c. 10,000 – 4000 BCE"
});

/* Optional alternative background spellings that also open a term's popup (slug -> [forms]); plurals auto-link. */
window.GLOSSARY_ALIASES = Object.assign(window.GLOSSARY_ALIASES || {}, {
"Ice_Age": ["glaciation","glacial period"],
"Middle_Paleolithic": ["Middle Palaeolithic"],
"Upper_Paleolithic": ["Late Paleolithic","Late Stone Age"],
"Three-age_system": ["three age system"],
"Knapping": ["flintknapping","flint knapping"],
"Hunter-gatherer": ["hunter-gatherers","hunter gatherer"],
"Lower_Paleolithic": ["Lower Palaeolithic"],
"Archaeology": ["archaeological","archaeologist","archaeologists"],
"Australopithecus": ["australopithecine"],
"Jason_E._Lewis": ["Jason Lewis"],
"Greece": ["Greek","Greeks"],
"John_Lubbock,_1st_Baron_Avebury": ["John Lubbock","Lubbock","Lord Avebury"],
"Neanderthal": ["Neanderthals","Neandertal","Homo neanderthalensis"],
"Homo_sapiens": ["H. sapiens","anatomically modern human"],
"Homo_erectus": ["H. erectus"],
"Oldowan": ["Oldowan industry"],
"Acheulean": ["Acheulian","Acheulean industry"],
"Neolithic": ["New Stone Age"]
});

/* Category tags per term (slug -> [tags]) — shown in the admin glossary list and filterable from its left bar. */
window.GLOSSARY_TAGS = Object.assign(window.GLOSSARY_TAGS || {}, {
"Sima_Qian": ["person","history","literature","han dynasty"],
"Paleolithic": ["era","archaeology","history"],
"Stone_Age": ["era","archaeology","history","technology"],
"Bronze_Age": ["era","history","archaeology"],
"Iron_Age": ["era","archaeology","history","technology"],
"Ice_Age": ["era","science","nature","archaeology"],
"Middle_Paleolithic": ["era","archaeology","prehistory","history"],
"Upper_Paleolithic": ["era","archaeology","prehistory","technology"],
"Three-age_system": ["concept","archaeology","history"],
"Knapping": ["practice","archaeology","technology"],
"Hunter-gatherer": ["practice","archaeology","history"],
"Lower_Paleolithic": ["era","archaeology","prehistory","history","technology"],
"Pleistocene": ["era","geology","science","nature"],
"Archaeology": ["concept","archaeology","history","science"],
"Megafauna": ["concept","biology","palaeontology","prehistory","nature"],
"Australopithecus": ["hominin","palaeontology","evolution","prehistory"],
"Sonia_Harmand": ["person","archaeology","prehistory","science"],
"Jason_E._Lewis": ["person","archaeology","prehistory","science"],
"Greece": ["place","geography","history","greece"],
"John_Lubbock,_1st_Baron_Avebury": ["person","archaeology","science","history"],
"Neanderthal": ["hominin","palaeontology","evolution","prehistory"],
"Homo_sapiens": ["hominin","palaeontology","evolution","prehistory"],
"Homo_erectus": ["hominin","palaeontology","evolution","prehistory"],
"Oldowan": ["industry","archaeology","prehistory","technology"],
"Acheulean": ["industry","archaeology","prehistory","technology"],
"Neolithic": ["era","archaeology","prehistory","history"],
"Mesolithic": ["era","archaeology","prehistory","history"]
});
