/* "Who said it?" quote pool — famous historical figures. Each: q (the quote), who (the speaker), cat (what
   the speaker is KNOWN FOR), era (WHEN they lived), context (2-sentence explanation shown on reveal).
   Researched from primary/standard sources and adversarially fact-checked for correct attribution.
   window.QUOTEGAME, loaded before app.js.

   `cat` is one of five: philosophy, statecraft, science, reform, letters. It exists so a round's three
   WRONG answers can be people of the same kind (Aug 2026, on request — the same change Multiple Choice
   and the Picture round made): drawn at random, a line of Stoic philosophy was answered against a
   physicist, a civil-rights leader and a playwright, which is a round won by elimination and teaches
   nothing about who said what.
   It is a fact about the SPEAKER rather than the quote, and it is deliberately coarse — five broad
   families, none of them a category of one, since a category with nobody else in it can supply no
   decoys at all. Where a life spans two (Marcus Aurelius ruled an empire and is quoted as a Stoic;
   Nelson Mandela was an activist who became a head of state) the one filed is the one the QUOTATION
   comes from, or failing that the one they are best known for.

   `era` is the same idea on the other axis, added Aug 2026 on the same request, because the category
   alone was not narrow enough: a Stoic maxim answered against Nietzsche, Kant and Simone de Beauvoir is
   still a round a reader can win by noticing which name is two thousand years older than the other
   three. Five values — ancient (to c. 500), medieval (to c. 1450), earlymodern (to c. 1750), modern
   (the long 19th century), contemporary (a life reaching well into the 20th) — deliberately coarse, and
   cut roughly where the history collections cut. `buildWhoSaidRounds` prefers a decoy sharing BOTH,
   then the category, then the era, then anybody: so a thin cell costs nothing, it simply falls through.
   TWO CELLS HOLD ONE PERSON EACH and are left that way rather than padded — reform/earlymodern (Luther)
   and science/medieval (Roger Bacon) — since inventing a companion for a cell is how a pool acquires a
   speaker nobody has heard of, or a quotation nobody said. Adding a real one to either is welcome. */
window.QUOTEGAME = [
  { "q": "Learning without thought is labour lost; thought without learning is perilous.", "who": "Confucius", "cat": "philosophy", "era": "ancient", "context": "Confucius was a Chinese philosopher and teacher of the Spring and Autumn period whose ethical teachings were compiled by his followers in the Analects. This line, from Book II of the Analects, holds that study and reflection each fail without the other and must work together." },
  { "q": "If you know the enemy and know yourself, you need not fear the result of a hundred battles.", "who": "Sun Tzu", "cat": "statecraft", "era": "ancient", "context": "Sun Tzu was an ancient Chinese military strategist traditionally credited with writing The Art of War. This maxim, from the chapter on attack by stratagem, argues that clear knowledge of both one's opponent and oneself is the foundation of victory." },
  { "q": "A journey of a thousand miles begins with a single step.", "who": "Laozi", "cat": "philosophy", "era": "ancient", "context": "Laozi was the semi-legendary Chinese sage regarded as the founder of Taoism and the author of the Tao Te Ching. From chapter 64 of that work, the line teaches that even the greatest undertakings are accomplished by starting with a small, immediate action." },
  { "q": "The unexamined life is not worth living.", "who": "Socrates", "cat": "philosophy", "era": "ancient", "context": "Socrates was a classical Athenian philosopher known chiefly through the dialogues of his student Plato. He spoke these words, recorded in Plato's Apology, at his trial, insisting that a life without self-scrutiny and questioning was not worth living even to avoid a death sentence." },
  { "q": "One swallow does not make a summer, nor does one day; and so too one day, or a short time, does not make a man blessed and happy.", "who": "Aristotle", "cat": "philosophy", "era": "ancient", "context": "Aristotle was a Greek philosopher and student of Plato whose writings span logic, ethics, politics, and natural science. In this passage from the Nicomachean Ethics he argues that lasting happiness is a matter of a complete life, not a single moment of good fortune." },
  { "q": "Waste no more time arguing what a good man should be. Be one.", "who": "Marcus Aurelius", "cat": "philosophy", "era": "ancient", "context": "Marcus Aurelius was a Roman emperor and Stoic philosopher who recorded private reflections in his Meditations. In Book 10 he urges himself to stop debating virtue in the abstract and instead simply act as a good person." },
  { "q": "The die is cast.", "who": "Julius Caesar", "cat": "statecraft", "era": "ancient", "context": "Julius Caesar was a Roman general and statesman whose career ended the Roman Republic. According to Suetonius, he spoke these words in 49 BCE as he led his army across the Rubicon river into Italy, an act of war against the Senate that committed him irrevocably to civil conflict." },
  { "q": "Oh, what times! Oh, what customs!", "who": "Cicero", "cat": "statecraft", "era": "ancient", "context": "Cicero was a Roman orator, statesman, and writer of the late Republic. He exclaimed this line (Latin: O tempora, o mores!) in his First Catilinarian Oration before the Senate in 63 BCE, expressing outrage at the state of the republic as Catiline's conspiracy against the government went on and its leader remained at large." },
  { "q": "What is history but a fable agreed upon?", "who": "Napoleon Bonaparte", "cat": "statecraft", "era": "modern", "context": "Napoleon Bonaparte was a French general who rose to become Emperor of the French and dominated European affairs in the early nineteenth century. He made this remark on the unreliability of historical accounts during his exile on Saint Helena, as recorded by the Count de Las Cases in the Memorial de Sainte-Helene on 20 November 1816." },
  { "q": "I have nothing to offer but blood, toil, tears and sweat.", "who": "Winston Churchill", "cat": "statecraft", "era": "contemporary", "context": "Winston Churchill was the British Prime Minister who led the United Kingdom through most of the Second World War. He spoke these words in his first address to the House of Commons as Prime Minister on 13 May 1940, warning the nation of the hardship of the struggle ahead against Nazi Germany." },
  { "q": "Government of the people, by the people, for the people, shall not perish from the earth.", "who": "Abraham Lincoln", "cat": "statecraft", "era": "modern", "context": "Abraham Lincoln was the sixteenth President of the United States, who led the country through its Civil War. He delivered this closing line of the Gettysburg Address on 19 November 1863, dedicating a cemetery for fallen soldiers and framing the war as a test of whether democratic self-government could endure." },
  { "q": "My life is my message.", "who": "Mahatma Gandhi", "cat": "reform", "era": "contemporary", "context": "Mahatma Gandhi was the leader of India's nonviolent independence movement against British rule. He gave this reply when asked for a message to pass on to others, meaning that his convictions were expressed and proven through the way he actually lived rather than through any separate statement." },
  { "q": "I have a dream that my four little children will one day live in a nation where they will not be judged by the color of their skin but by the content of their character.", "who": "Martin Luther King Jr.", "cat": "reform", "era": "contemporary", "context": "King was an American Baptist minister and the foremost leader of the mid-20th-century civil rights movement. He spoke these words in his \"I Have a Dream\" speech at the March on Washington on August 28, 1963, envisioning a future of racial equality." },
  { "q": "I have cherished the ideal of a democratic and free society in which all persons live together in harmony and with equal opportunities. It is an ideal which I hope to live for and to achieve. But if needs be, it is an ideal for which I am prepared to die.", "who": "Nelson Mandela", "cat": "statecraft", "era": "contemporary", "context": "Mandela was a South African anti-apartheid leader who later became the country's first democratically elected president. He delivered these words from the dock at the Rivonia Trial on April 20, 1964, while facing a possible death sentence for opposing apartheid." },
  { "q": "Imagination is more important than knowledge. For knowledge is limited, whereas imagination embraces the entire world, stimulating progress, giving birth to evolution.", "who": "Albert Einstein", "cat": "science", "era": "contemporary", "context": "Einstein was a German-born theoretical physicist who developed the theory of relativity. He made this remark in an interview with George Sylvester Viereck, published in The Saturday Evening Post in October 1929, reflecting on the sources of scientific insight." },
  { "q": "If I have seen further it is by standing on the shoulders of giants.", "who": "Isaac Newton", "cat": "science", "era": "earlymodern", "context": "Newton was an English mathematician and physicist whose work laid the foundations of classical mechanics. He wrote this line in a letter to fellow scientist Robert Hooke dated February 5, 1675, acknowledging that his discoveries built on the achievements of earlier thinkers." },
  { "q": "In this world nothing can be said to be certain, except death and taxes.", "who": "Benjamin Franklin", "cat": "statecraft", "era": "modern", "context": "Franklin was an American statesman, scientist, and one of the Founding Fathers of the United States. He wrote this remark in a 1789 letter to the French scientist Jean-Baptiste Le Roy, commenting on the newly established U.S. Constitution and life's few certainties." },
  { "q": "The credit belongs to the man who is actually in the arena, whose face is marred by dust and sweat and blood; who strives valiantly; who errs, and comes short again and again, because there is no effort without error and shortcoming.", "who": "Theodore Roosevelt", "cat": "statecraft", "era": "contemporary", "context": "Roosevelt was the 26th president of the United States and a soldier, conservationist, and reformer. He spoke these words, known as \"The Man in the Arena,\" in his \"Citizenship in a Republic\" address at the Sorbonne in Paris on April 23, 1910, praising those who dare to act over those who merely criticize." },
  { "q": "It is much safer to be feared than loved, if one of the two must be lacking.", "who": "Niccolò Machiavelli", "cat": "statecraft", "era": "earlymodern", "context": "Machiavelli was a Florentine Renaissance diplomat and political theorist, author of The Prince. The line comes from Chapter 17 of The Prince, where he argues that a ruler who cannot be both loved and feared should prefer to be feared, since fear is a more reliable hold on subjects." },
  { "q": "Doubt is not a pleasant condition, but certainty is an absurd one.", "who": "Voltaire", "cat": "philosophy", "era": "modern", "context": "Voltaire was a French Enlightenment writer and philosopher known for his wit and advocacy of reason and civil liberties. He wrote the line in a letter to Frederick William, Prince of Prussia, on 28 November 1770, criticizing dogmatic claims to certainty about metaphysical questions." },
  { "q": "The only thing we have to fear is fear itself.", "who": "Franklin D. Roosevelt", "cat": "statecraft", "era": "contemporary", "context": "Roosevelt was the 32nd President of the United States, who led the country through the Great Depression and most of World War II. He spoke these words in his first inaugural address on March 4, 1933, urging Americans not to let panic paralyze the nation's recovery from the economic crisis." },
  { "q": "Ask not what your country can do for you—ask what you can do for your country.", "who": "John F. Kennedy", "cat": "statecraft", "era": "contemporary", "context": "Kennedy was the 35th President of the United States, serving from 1961 until his assassination in 1963. He delivered this call to civic duty in his inaugural address on January 20, 1961, urging citizens to contribute to the common good rather than expect benefits from government." },
  { "q": "Iron rusts from disuse; stagnant water loses its purity and in cold weather becomes frozen; even so does inaction sap the vigour of the mind.", "who": "Leonardo da Vinci", "cat": "letters", "era": "earlymodern", "context": "Leonardo was an Italian Renaissance polymath renowned as a painter, inventor, and scientist. The reflection is recorded in his notebooks from the Codex Atlanticus, likening idleness of the mind to metal corroding and water stagnating when left unused." },
  { "q": "Alone we can do so little; together we can do so much.", "who": "Helen Keller", "cat": "reform", "era": "contemporary", "context": "Keller was an American author and activist who, though deaf and blind from early childhood, became a prominent advocate for people with disabilities. She spoke the line as the closing of a short address during her vaudeville stage appearances in the 1920s, emphasizing the power of cooperation and mutual dependence." },
  { "q": "I have sworn upon the altar of God eternal hostility against every form of tyranny over the mind of man", "who": "Thomas Jefferson", "cat": "statecraft", "era": "modern", "context": "Thomas Jefferson was the principal author of the Declaration of Independence and the third President of the United States. He wrote this line in a private letter defending freedom of belief against government coercion, and it is now inscribed beneath the dome of the Jefferson Memorial." },
  { "q": "These are the times that try men's souls", "who": "Thomas Paine", "cat": "reform", "era": "modern", "context": "Thomas Paine was an English-born political writer whose pamphlets helped galvanize the American Revolution. He opened the first number of The American Crisis with this line in the bleak winter of 1776, and Washington had it read aloud to his troops before crossing the Delaware." },
  { "q": "If there is no struggle, there is no progress", "who": "Frederick Douglass", "cat": "reform", "era": "modern", "context": "Frederick Douglass was an escaped slave who became the leading African American abolitionist, orator, and writer of the nineteenth century. He delivered this line in his address marking the anniversary of West Indian emancipation, arguing that power concedes nothing without demand." },
  { "q": "A foolish consistency is the hobgoblin of little minds", "who": "Ralph Waldo Emerson", "cat": "letters", "era": "modern", "context": "Ralph Waldo Emerson was an American essayist and the central figure of the Transcendentalist movement. He wrote this in his essay Self-Reliance, urging readers to trust their own evolving convictions rather than clinging to past positions for the sake of appearing consistent." },
  { "q": "I went to the woods because I wished to live deliberately, to front only the essential facts of life", "who": "Henry David Thoreau", "cat": "letters", "era": "modern", "context": "Henry David Thoreau was an American naturalist, essayist, and Transcendentalist known for his experiment in simple living at Walden Pond. He wrote this to explain why he withdrew to the woods, seeking to strip life to its essentials rather than reach death having never truly lived." },
  { "q": "There is grandeur in this view of life, with its several powers, having been originally breathed into a few forms or into one; and that, whilst this planet has gone cycling on according to the fixed law of gravity, from so simple a beginning endless forms most beautiful and most wonderful have been, and are being, evolved.", "who": "Charles Darwin", "cat": "science", "era": "modern", "context": "Charles Darwin was the English naturalist who proposed the theory of evolution by natural selection. This is the closing sentence of On the Origin of Species, in which he casts the vast diversity of life as the majestic product of simple natural laws working over immense time." },
  { "q": "The philosophers have only interpreted the world, in various ways; the point is to change it.", "who": "Karl Marx", "cat": "philosophy", "era": "modern", "context": "Karl Marx was the German philosopher and economist whose critique of capitalism founded modern communist thought. This is the eleventh and final of his Theses on Feuerbach, contrasting mere contemplation of the world with the imperative of revolutionary action, and it is engraved on his tomb." },
  { "q": "What does not kill me makes me stronger.", "who": "Friedrich Nietzsche", "cat": "philosophy", "era": "modern", "context": "Friedrich Nietzsche was the German philosopher known for his critiques of morality, religion, and traditional values. This aphorism, from the Maxims and Arrows section of Twilight of the Idols, expresses his idea that hardship and adversity can temper and strengthen a person." },
  { "q": "Enlightenment is man's emergence from his self-imposed nonage.", "who": "Immanuel Kant", "cat": "philosophy", "era": "modern", "context": "Immanuel Kant was the German Enlightenment philosopher whose work reshaped metaphysics, ethics, and epistemology. This is the opening definition of his 1784 essay answering the question 'What is Enlightenment?', where 'nonage' means the immaturity of relying on others' guidance instead of one's own reason." },
  { "q": "Man is born free, and everywhere he is in chains.", "who": "Jean-Jacques Rousseau", "cat": "philosophy", "era": "modern", "context": "Jean-Jacques Rousseau was the Genevan Enlightenment philosopher whose political writings deeply influenced modern democratic and revolutionary thought. This is the celebrated opening line of Book I, Chapter 1 of The Social Contract, contrasting humanity's natural freedom with the constraints imposed by society." },
  { "q": "We are all in the gutter, but some of us are looking at the stars.", "who": "Oscar Wilde", "cat": "letters", "era": "modern", "context": "Oscar Wilde was an Irish poet and playwright celebrated for his sparkling wit and aestheticism. Spoken by Lord Darlington in Act III of the play Lady Windermere's Fan, the line contrasts human squalor with the capacity to aspire toward something higher." },
  { "q": "When in doubt, tell the truth.", "who": "Mark Twain", "cat": "letters", "era": "modern", "context": "Mark Twain was the American author and humorist behind The Adventures of Tom Sawyer and Huckleberry Finn. He offered this maxim as one of the epigraphs from Pudd'nhead Wilson's New Calendar, wry practical advice that honesty is the safest default." },
  { "q": "All my life through, the new sights of Nature made me rejoice like a child.", "who": "Marie Curie", "cat": "science", "era": "contemporary", "context": "Marie Curie was the Polish-French physicist and chemist who pioneered research on radioactivity and won Nobel Prizes in two sciences. Writing in her own autobiographical notes, she recalled how a lifelong sense of wonder at the natural world drove her curiosity and discovery." },
  { "q": "You must do the thing you think you cannot do.", "who": "Eleanor Roosevelt", "cat": "reform", "era": "contemporary", "context": "Eleanor Roosevelt was the longest-serving First Lady of the United States and a leading human-rights advocate who chaired the drafting of the Universal Declaration of Human Rights. She wrote this in a chapter on overcoming fear, urging readers to build courage by confronting exactly what frightens them." },
  { "q": "Look again at that dot. That's here. That's home. That's us.", "who": "Carl Sagan", "cat": "science", "era": "contemporary", "context": "Carl Sagan was an American astronomer and science communicator known for the Cosmos television series and books that made space accessible to millions. He wrote these words reflecting on the Voyager 1 photograph of Earth as a tiny speck seen from beyond Neptune, a meditation on our shared fragility." },
  { "q": "In spite of everything I still believe that people are really good at heart", "who": "Anne Frank", "cat": "letters", "era": "contemporary", "context": "Anne Frank was a German-born Jewish girl whose diary, written while hiding from the Nazis in Amsterdam, became one of the most widely read accounts of the Holocaust. She wrote this line in her diary entry of 15 July 1944, affirming her faith in humanity even as persecution closed in, less than a month before the annex was discovered." },
  { "q": "Without courage we cannot practice any other virtue with consistency. We can't be kind, true, merciful, generous, or honest", "who": "Maya Angelou", "cat": "letters", "era": "contemporary", "context": "Maya Angelou was an American poet and memoirist best known for her autobiography I Know Why the Caged Bird Sings and the poem Still I Rise. She offered this reflection on courage as the foundation of all other virtues in a 1988 interview, a theme she returned to often in her later talks." },
  { "q": "No, the only tired I was, was tired of giving in", "who": "Rosa Parks", "cat": "reform", "era": "contemporary", "context": "Rosa Parks was an American civil-rights activist whose refusal to give up her bus seat to a white passenger in 1955 sparked the Montgomery Bus Boycott. In her autobiography she wrote this to correct the myth that she stayed seated because she was physically weary, explaining that her real exhaustion was with racial injustice." },
  { "q": "Slavery is the daughter of darkness: an ignorant people is a blind instrument of its own destruction", "who": "Simón Bolívar", "cat": "statecraft", "era": "modern", "context": "Simón Bolívar was the Venezuelan general and statesman who led much of South America to independence from Spain and is revered across the continent as El Libertador. He delivered this warning in his 1819 Angostura Address, arguing that education and moral formation, not force, are the true foundations of a free republic." },
  { "q": "It is not from the benevolence of the butcher, the brewer, or the baker that we expect our dinner, but from their regard to their own interest", "who": "Adam Smith", "cat": "philosophy", "era": "modern", "context": "Adam Smith was an 18th-century Scottish moral philosopher and economist whose book The Wealth of Nations helped found modern economics. This line illustrates his central insight that people are led to serve one another not by charity but by appealing to each party's own self-interest." },
  { "q": "Give me a place to stand, and I will move the earth.", "who": "Archimedes", "cat": "science", "era": "ancient", "context": "Archimedes was a Greek mathematician, physicist, and engineer of the 3rd century BCE. He reportedly said this while demonstrating the principle of the lever, boasting that with a firm fulcrum he could move any weight, as recorded by the later writer Pappus of Alexandria." },
  { "q": "Men are disturbed not by things, but by the views which they take of them.", "who": "Epictetus", "cat": "philosophy", "era": "ancient", "context": "Epictetus was a Greek Stoic philosopher who had been born into slavery and taught in Rome and Nicopolis. This line opens a central lesson of his Enchiridion, that our judgments about events, rather than the events themselves, are the true source of our distress." },
  { "q": "Life is short, and the art long; the occasion fleeting; experience fallacious, and judgment difficult.", "who": "Hippocrates", "cat": "science", "era": "ancient", "context": "Hippocrates was a physician of Classical Greece regarded as a founder of Western medicine. This is the first and most famous of his Aphorisms, reflecting on how vast the medical art is compared to a single lifetime and how uncertain a doctor's decisions must be." },
  { "q": "Man is the measure of all things: of the things that are, that they are, and of the things that are not, that they are not.", "who": "Protagoras", "cat": "philosophy", "era": "ancient", "context": "Protagoras was a 5th-century BCE Greek Sophist and teacher of rhetoric from Abdera. This opening line of his lost work Truth, preserved by Plato and Sextus Empiricus, expresses his relativism, that human perception is the standard by which things are judged." },
  { "q": "No man is so foolish as to desire war rather than peace; for in peace sons bury their fathers, but in war fathers bury their sons.", "who": "Herodotus", "cat": "letters", "era": "ancient", "context": "Herodotus was a 5th-century BCE Greek writer often called the Father of History. In his Histories the deposed Lydian king Croesus speaks these words to the Persian king Cyrus, reflecting on the tragic reversal of the natural order that war brings." },
  { "q": "We do not say that a man who takes no interest in politics minds his own business; we say that he has no business here at all.", "who": "Pericles", "cat": "statecraft", "era": "ancient", "context": "Pericles was the leading statesman of Athens during its golden age in the 5th century BCE. In the Funeral Oration recorded by Thucydides, he praises Athenian democracy by insisting that active civic participation is the duty of every citizen." },
  { "q": "Death, therefore, the most awful of evils, is nothing to us, seeing that, when we are, death is not come, and, when death is come, we are not.", "who": "Epicurus", "cat": "philosophy", "era": "ancient", "context": "Epicurus was a Greek philosopher of the 4th and 3rd centuries BCE who founded the school known as Epicureanism. In his Letter to Menoeceus he argues that death should hold no fear, since we can never actually experience it." },
  { "q": "The mind is not a vessel to be filled, but a fire to be kindled.", "who": "Plutarch", "cat": "letters", "era": "ancient", "context": "Plutarch was a Greek biographer and essayist of the 1st and 2nd centuries CE, best known for his Parallel Lives. In his essay On Listening to Lectures he compares the student's mind to wood that must be set alight, urging education that awakens independent thought rather than mere memorization." },
  { "q": "We suffer more often in imagination than in reality.", "who": "Seneca", "cat": "philosophy", "era": "ancient", "context": "Seneca the Younger was a Roman Stoic philosopher and statesman of the 1st century CE. In Letter 13 to Lucilius, titled On Groundless Fears, he observes that anxiety about anticipated misfortune torments us more than the misfortunes that actually occur." },
  { "q": "The great man is he who does not lose his child's heart.", "who": "Mencius", "cat": "philosophy", "era": "ancient", "context": "Mencius was a Chinese Confucian philosopher of the 4th century BCE, regarded as the tradition's second great teacher after Confucius. This saying from the book bearing his name reflects his belief that human nature is innately good and that virtue lies in preserving one's original sincerity." },
  { "q": "Now I do not know whether I was then a man dreaming I was a butterfly, or whether I am now a butterfly dreaming I am a man.", "who": "Zhuangzi", "cat": "philosophy", "era": "ancient", "context": "Zhuangzi was a Chinese Daoist philosopher of the Warring States period in the 4th century BCE. His famous butterfly dream questions the boundary between illusion and reality, and whether we can ever be certain of the nature of our own existence." },
  { "q": "Hatred does not cease by hatred, but only by love; this is the eternal rule.", "who": "Gautama Buddha", "cat": "philosophy", "era": "ancient", "context": "Siddhartha Gautama, the Buddha, was the Indian sage of roughly the 5th century BCE whose teachings founded Buddhism. This verse from the Dhammapada teaches that responding to enmity with more enmity only perpetuates it, and that only loving-kindness can truly end conflict." },
  { "q": "The Moving Finger writes; and, having writ, moves on: nor all thy Piety nor Wit shall lure it back to cancel half a Line.", "who": "Omar Khayyam", "cat": "letters", "era": "medieval", "context": "Omar Khayyam was a Persian polymath, poet, and astronomer of the 11th and 12th centuries. In this famous quatrain from the Rubaiyat, rendered into English by Edward FitzGerald, he reflects that the past is irrevocable and cannot be undone by regret or prayer." },
  { "q": "Abandon all hope, ye who enter here.", "who": "Dante Alighieri", "cat": "letters", "era": "medieval", "context": "Dante Alighieri was an Italian poet of the late 13th and early 14th centuries, author of the Divine Comedy. This line is the inscription over the gate of Hell in the Inferno, warning the damned that they leave all hope behind as they pass within." },
  { "q": "In the country of the blind, the one-eyed man is king.", "who": "Erasmus", "cat": "letters", "era": "earlymodern", "context": "Desiderius Erasmus was a Dutch humanist scholar and theologian of the Renaissance, famous for his edition of the Greek New Testament and for Praise of Folly. He popularized this proverb in his Adagia, a celebrated collection of classical sayings, to observe that even modest ability commands authority among those who have none." },
  { "q": "I die the King's good servant, and God's first.", "who": "Thomas More", "cat": "statecraft", "era": "earlymodern", "context": "Sir Thomas More was an English humanist, statesman, and Lord Chancellor who wrote Utopia and was executed in 1535 for refusing to accept Henry VIII as head of the Church of England. He spoke these words on the scaffold, affirming his loyalty to the king but his higher loyalty to God." },
  { "q": "I cannot and will not recant anything, for to go against conscience is neither right nor safe.", "who": "Martin Luther", "cat": "reform", "era": "earlymodern", "context": "Martin Luther was a German monk and theologian whose protests against Church practices launched the Protestant Reformation. He spoke these documented words before the Diet of Worms in 1521, refusing the emperor's demand that he retract his writings." },
  { "q": "I know I have the body of a weak and feeble woman, but I have the heart and stomach of a king, and of a king of England too.", "who": "Elizabeth I", "cat": "statecraft", "era": "earlymodern", "context": "Elizabeth I was Queen of England and Ireland from 1558 to 1603, presiding over a cultural and naval golden age. She spoke these words in her speech to the troops at Tilbury in 1588, rallying her army as it awaited the Spanish Armada." },
  { "q": "I do not feel obliged to believe that the same God who has endowed us with sense, reason, and intellect has intended us to forgo their use.", "who": "Galileo Galilei", "cat": "science", "era": "earlymodern", "context": "Galileo Galilei was an Italian astronomer and physicist of the late Renaissance whose support for the heliocentric model brought him into conflict with the Church. He wrote this in his 1615 Letter to the Grand Duchess Christina, arguing that faith and reasoned scientific inquiry need not contradict each other." },
  { "q": "All the world's a stage, and all the men and women merely players; they have their exits and their entrances.", "who": "William Shakespeare", "cat": "letters", "era": "earlymodern", "context": "William Shakespeare was an English playwright and poet of the late 16th and early 17th centuries, widely regarded as the greatest writer in the English language. This line, spoken by the melancholy Jaques in As You Like It, introduces the celebrated Seven Ages of Man speech comparing human life to a play." },
  { "q": "There is no royal road to geometry.", "who": "Euclid", "cat": "science", "era": "ancient", "context": "Euclid was a Greek mathematician of Alexandria whose Elements set out geometry as a chain of proofs from a handful of axioms and served as the standard textbook for two thousand years. Proclus records that he gave this reply to King Ptolemy I, who had asked whether there were some shorter way to master the subject than working through the Elements." },
  { "q": "In these matters the only certainty is that nothing is certain.", "who": "Pliny the Elder", "cat": "science", "era": "ancient", "context": "Pliny the Elder was a Roman official and naturalist who compiled the Natural History, an encyclopaedia of everything known to the ancient world, and died observing the eruption of Vesuvius in 79 CE. He wrote this line in Book II while discussing the nature of the heavens, conceding the limits of what could be established about them." },
  { "q": "I know that I am mortal by nature and ephemeral; but when I trace at my pleasure the windings to and fro of the heavenly bodies, I no longer touch the earth with my feet.", "who": "Ptolemy", "cat": "science", "era": "ancient", "context": "Ptolemy was a Greek astronomer of second-century Alexandria whose Almagest gave the earth-centred model of the heavens its definitive form. The lines come from an epigram preserved in the Greek Anthology and traditionally ascribed to him, on the exhilaration of astronomical work." },
  { "q": "The strong do what they can and the weak suffer what they must.", "who": "Thucydides", "cat": "letters", "era": "ancient", "context": "Thucydides was an Athenian general and historian whose account of the Peloponnesian War set out to explain events by human causes rather than divine ones. The line is the Athenian envoys' argument in the Melian Dialogue in Book V, stating that questions of justice arise only between equals in power." },
  { "q": "Fortune favours the bold.", "who": "Virgil", "cat": "letters", "era": "ancient", "context": "Virgil was the Roman poet of the Augustan age whose Aeneid recounts the flight of Aeneas from Troy and the founding of the Roman line. The words are spoken in Book X (audentis Fortuna iuvat) as a warrior urges himself into battle, and they passed into proverb long afterwards." },
  { "q": "Wonders are many, and none is more wonderful than man.", "who": "Sophocles", "cat": "letters", "era": "ancient", "context": "Sophocles was an Athenian tragedian of the fifth century BCE, author of Antigone and Oedipus the King. The line opens the choral Ode on Man in Antigone, which goes on to catalogue human mastery of the sea, the soil and the beasts, and then the one thing that mastery cannot escape." },
  { "q": "Upon those who step into the same rivers, different and yet different waters flow.", "who": "Heraclitus", "cat": "philosophy", "era": "ancient", "context": "Heraclitus was a Greek philosopher of Ephesus around 500 BCE, known for holding that everything is in flux and that opposites are bound together. This is his surviving fragment on the river, quoted by later writers; the familiar form that no man steps into the same river twice is a later paraphrase of it." },
  { "q": "Carthage must be destroyed.", "who": "Cato the Elder", "cat": "statecraft", "era": "ancient", "context": "Cato the Elder was a Roman senator and censor of the second century BCE, famous for his austerity and his hostility to Carthage. Plutarch records that he ended every speech in the Senate, whatever its subject, by declaring that Carthage must be destroyed, until Rome went to war and razed it in 146 BCE." },
  { "q": "Nothing is wretched unless you think it so; and on the other hand, nothing brings happiness unless you are content with it.", "who": "Boethius", "cat": "philosophy", "era": "medieval", "context": "Boethius was a Roman senator and philosopher who wrote the Consolation of Philosophy in prison while awaiting execution around 524. In Book II, Philosophy tells him that misery and contentment lie in a person's own judgement of their circumstances rather than in the circumstances themselves." },
  { "q": "Grace does not destroy nature, but perfects it.", "who": "Thomas Aquinas", "cat": "philosophy", "era": "medieval", "context": "Thomas Aquinas was a thirteenth-century Dominican friar and theologian whose Summa Theologiae reconciled Christian doctrine with the newly recovered philosophy of Aristotle. He states the principle in the first question of that work, arguing that reason and revelation complete one another rather than standing opposed." },
  { "q": "Human beings are the children of their customs and the things they have grown used to, not the children of their natural disposition.", "who": "Ibn Khaldun", "cat": "philosophy", "era": "medieval", "context": "Ibn Khaldun was a fourteenth-century North African historian and official whose Muqaddimah proposed a general science of how societies rise and decay. The observation belongs to his argument that character is formed by upbringing and habit, and that a people's way of life shapes what they are able to become." },
  { "q": "And gladly would he learn, and gladly teach.", "who": "Geoffrey Chaucer", "cat": "letters", "era": "medieval", "context": "Chaucer was an English poet and royal official of the late fourteenth century whose Canterbury Tales follows a company of pilgrims telling stories on the road to Canterbury. The line describes the threadbare Clerk of Oxford in the General Prologue, who spent every penny he had on books." },
  { "q": "Argument concludes a question, but it does not make us feel certain, unless the truth is discovered by way of experience.", "who": "Roger Bacon", "cat": "science", "era": "medieval", "context": "Roger Bacon was a thirteenth-century English friar and scholar who urged the study of languages, mathematics and what he called experimental science. He wrote this in the Opus Majus, prepared for Pope Clement IV, arguing that reasoning alone cannot settle a question that observation could settle instead." },
  { "q": "I think, therefore I am.", "who": "René Descartes", "cat": "philosophy", "era": "earlymodern", "context": "Descartes was a French philosopher and mathematician of the seventeenth century, often called the founder of modern philosophy. He reached this conclusion in Part IV of the Discourse on Method, having resolved to doubt everything he could: whatever else might be illusion, the doubting itself proved a thinker existed." },
  { "q": "The heart has its reasons, which reason does not know.", "who": "Blaise Pascal", "cat": "philosophy", "era": "earlymodern", "context": "Pascal was a French mathematician, physicist and religious thinker of the seventeenth century who helped found probability theory before turning to theology. The line comes from the Pensees, his unfinished defence of Christian faith, arguing that some convictions are reached by a kind of knowing that argument cannot supply." },
  { "q": "The most manifest sign of wisdom is a continual cheerfulness.", "who": "Michel de Montaigne", "cat": "philosophy", "era": "earlymodern", "context": "Montaigne was a French nobleman of the sixteenth century who invented the essay as a form, writing candidly about himself as a way of examining human nature. The remark comes from the essay on the education of children, where he objects to teaching that makes learning grim." },
  { "q": "Peace is not the absence of war; it is a virtue, a state of mind, a disposition for benevolence, confidence and justice.", "who": "Baruch Spinoza", "cat": "philosophy", "era": "earlymodern", "context": "Spinoza was a Dutch philosopher of the seventeenth century, expelled from his synagogue for his views and later the author of the Ethics. He wrote this in the unfinished Political Treatise, distinguishing a genuine commonwealth from one whose subjects are merely too cowed to fight." },
  { "q": "The life of man: solitary, poor, nasty, brutish, and short.", "who": "Thomas Hobbes", "cat": "statecraft", "era": "earlymodern", "context": "Hobbes was an English political philosopher whose Leviathan, published in 1651 after the English Civil War, argued that people submit to a sovereign to escape the violence of a lawless condition. The phrase describes that condition, which he called the war of every man against every man." },
  { "q": "Knowledge itself is power.", "who": "Francis Bacon", "cat": "science", "era": "earlymodern", "context": "Francis Bacon was an English statesman and philosopher who argued that natural knowledge should be built up from patient observation and experiment rather than deduced from ancient authorities. The Latin phrase appears in his Meditationes Sacrae of 1597, and the programme it announces shaped the founding of the Royal Society." },
  { "q": "In the middle of all sits the Sun enthroned. In this most beautiful temple could we place this luminary in any better position from which he can illuminate the whole at once?", "who": "Nicolaus Copernicus", "cat": "science", "era": "earlymodern", "context": "Copernicus was a Polish astronomer and cleric whose On the Revolutions of the Heavenly Spheres, published in 1543, placed the sun rather than the earth at the centre of the planetary system. The passage from Book I defends that arrangement on grounds of fitness and order as much as of calculation." },
  { "q": "The Analytical Engine has no pretensions whatever to originate anything. It can do whatever we know how to order it to perform.", "who": "Ada Lovelace", "cat": "science", "era": "modern", "context": "Ada Lovelace was an English mathematician who worked with Charles Babbage on his proposed Analytical Engine, a mechanical general-purpose computer never built in their lifetimes. She wrote this in the notes appended to her 1843 translation of a paper on the machine, in a passage weighing what such a device could and could not be said to do." },
  { "q": "Nothing is too wonderful to be true, if it be consistent with the laws of nature.", "who": "Michael Faraday", "cat": "science", "era": "modern", "context": "Faraday was an English experimentalist, largely self-taught, whose work on electromagnetic induction underlies the electric motor and the generator. He wrote the line in his laboratory diary in 1849, at the start of an investigation into whether gravity and electricity might be related." },
  { "q": "In the fields of observation, chance favours only the prepared mind.", "who": "Louis Pasteur", "cat": "science", "era": "modern", "context": "Pasteur was a French chemist and microbiologist whose work established the germ theory of disease and gave its name to pasteurisation. He said this in an address at Lille in 1854, arguing that an accidental discovery still requires someone equipped to recognise what they have seen." },
  { "q": "The only purpose for which power can be rightfully exercised over any member of a civilised community, against his will, is to prevent harm to others.", "who": "John Stuart Mill", "cat": "philosophy", "era": "modern", "context": "Mill was an English philosopher and political economist and briefly a member of Parliament. He set out this harm principle in the first chapter of On Liberty in 1859, as the single test by which society may interfere with an individual." },
  { "q": "It is a truth universally acknowledged, that a single man in possession of a good fortune must be in want of a wife.", "who": "Jane Austen", "cat": "letters", "era": "modern", "context": "Jane Austen was an English novelist of the early nineteenth century whose six novels examine marriage, money and manners among the landed gentry. This is the opening sentence of Pride and Prejudice, whose irony is that the truth belongs to the neighbourhood's ambitions rather than to the gentleman's." },
  { "q": "Happy families are all alike; every unhappy family is unhappy in its own way.", "who": "Leo Tolstoy", "cat": "letters", "era": "modern", "context": "Tolstoy was a Russian novelist whose War and Peace and Anna Karenina are among the longest-admired works of European fiction. This is the first sentence of Anna Karenina, opening a novel that sets one collapsing marriage beside a household finding its way." },
  { "q": "I do not wish them to have power over men, but over themselves.", "who": "Mary Wollstonecraft", "cat": "reform", "era": "modern", "context": "Mary Wollstonecraft was an English writer whose Vindication of the Rights of Woman, published in 1792, argued that women appear weaker than men because they are educated to be so. The line answers the charge that her argument was a bid for dominance rather than for self-command." },
  { "q": "Failure is impossible.", "who": "Susan B. Anthony", "cat": "reform", "era": "modern", "context": "Susan B. Anthony spent half a century campaigning for the abolition of slavery and for women's suffrage in the United States, and was tried and fined for voting in 1872. She closed her last public speech, at a celebration of her eightieth birthday in 1906, with these words; women did not win the federal vote until fourteen years later." },
  { "q": "Politics is the art of the possible.", "who": "Otto von Bismarck", "cat": "statecraft", "era": "modern", "context": "Bismarck was the Prussian minister-president who unified Germany under Prussian leadership and served as its first chancellor. He made this remark in conversation in 1867, defending the compromises of practical statecraft against those who judged policy by its ideals alone." },
  { "q": "Whereof one cannot speak, thereof one must be silent.", "who": "Ludwig Wittgenstein", "cat": "philosophy", "era": "contemporary", "context": "Wittgenstein was an Austrian-British philosopher whose work on language shaped twentieth-century philosophy twice over, in early and late forms that he himself came to see as opposed. This is the seventh and final proposition of the Tractatus Logico-Philosophicus, closing the book by marking the limit of what language can state." },
  { "q": "One is not born, but rather becomes, a woman.", "who": "Simone de Beauvoir", "cat": "philosophy", "era": "contemporary", "context": "Simone de Beauvoir was a French philosopher and novelist and a central figure in existentialism. She opens the second volume of The Second Sex, published in 1949, with this sentence, arguing that what a society treats as feminine nature is the product of how girls are raised." },
  { "q": "The sad truth is that most evil is done by people who never make up their minds to be good or evil.", "who": "Hannah Arendt", "cat": "philosophy", "era": "contemporary", "context": "Hannah Arendt was a German-born political theorist who fled Nazi Germany and wrote on totalitarianism and on the trial of Adolf Eichmann. The remark comes from The Life of the Mind and belongs to her long argument that great wrongs are commonly committed by people who never stop to think about what they are doing." },
  { "q": "A woman must have money and a room of her own if she is to write fiction.", "who": "Virginia Woolf", "cat": "letters", "era": "contemporary", "context": "Virginia Woolf was an English novelist and essayist and a central figure of literary modernism. She argues the case in A Room of One's Own, published in 1929 and based on lectures given at two women's colleges, holding that the scarcity of women writers was a matter of means and privacy rather than of talent." },
  { "q": "If liberty means anything at all, it means the right to tell people what they do not want to hear.", "who": "George Orwell", "cat": "letters", "era": "contemporary", "context": "Orwell was an English novelist and essayist whose Animal Farm and Nineteen Eighty-Four are the century's best-known fables of political power. He wrote the line in a preface on press freedom composed for Animal Farm and left out of the published book; it was not printed until 1972." },
  { "q": "The first principle is that you must not fool yourself, and you are the easiest person to fool.", "who": "Richard Feynman", "cat": "science", "era": "contemporary", "context": "Feynman was an American theoretical physicist who shared the Nobel Prize for his work on quantum electrodynamics and later served on the inquiry into the Challenger disaster. He said this in a commencement address at Caltech in 1974 on what he called cargo cult science, work that keeps the outward form of research without its honesty." },
  { "q": "We can only see a short distance ahead, but we can see plenty there that needs to be done.", "who": "Alan Turing", "cat": "science", "era": "contemporary", "context": "Turing was an English mathematician who formalised the idea of computation, worked on breaking German ciphers during the Second World War, and asked early whether machines could think. This is the closing sentence of his 1950 paper in Mind that proposed what is now called the Turing test." },
  { "q": "The problem of the twentieth century is the problem of the color line.", "who": "W. E. B. Du Bois", "cat": "reform", "era": "contemporary", "context": "Du Bois was an American sociologist and historian, the first Black American to earn a doctorate from Harvard, and a founder of the NAACP. He states this at the opening of The Souls of Black Folk in 1903, naming racial division as the defining question of the century then beginning." },
  { "q": "At the stroke of the midnight hour, when the world sleeps, India will awake to life and freedom.", "who": "Jawaharlal Nehru", "cat": "statecraft", "era": "contemporary", "context": "Nehru was the leader of the Indian National Congress under British rule and became independent India's first prime minister. He spoke these words to the Constituent Assembly in the last minutes of 14 August 1947, as British rule ended and the subcontinent was partitioned." }
];
