#!/usr/bin/env node
/* pack.js — step 8 of the Atlas v2 build: the intermediate outputs → the files the site serves.

     node pack.js            out/land.json → atlas/data/topology.bin
     node pack.js --dry      build the bytes and report the size, write nothing

   PHASE 0 SCOPE: one input (build-land.js's out/land.json) and one output. Later phases add the
   polity steps, rivers and lakes to the same topology, the tiles, and atlas/data/credits.js
   (generated by merging every output's header, §2.10a); the shape of this script does not change.

   THE HEADER'S `sources` BLOCK is copied from sources.json for exactly the ids the input names,
   verbatim: name, version, url, licence, licenceUrl, attribution, retrieved, sha256. That is what
   makes the file self-describing — check-topology.js refuses an arc or face whose source index is
   not in it, and the credits page is rendered from it, so a source cannot ship uncredited.

   Vertex ids in land.json are per arc already (an arc lists its own coordinates); here the arcs are
   simply concatenated in order, which is the layout the format wants (an arc's first vertex is a
   delta from the previous arc's last).
*/
"use strict";
const fs = require("fs"), path = require("path");
const F = require("./lib/format.js");
const { headerSources } = require("./fetch-sources.js");

const HERE = __dirname;
const IN = path.join(HERE, "out", "land.json");
const OUTFILE = path.join(HERE, "..", "..", "atlas", "data", "topology.bin");
const dry = process.argv.includes("--dry");

const L = JSON.parse(fs.readFileSync(IN, "utf8"));
let nV = 0; for (const a of L.arcs) nV += a.x.length;
const lon = new Int32Array(nV), lat = new Int32Array(nV), rank = new Uint8Array(nV);
const arcs = [];
let off = 0;
for (const a of L.arcs) {
  for (let i = 0; i < a.x.length; i++) { lon[off + i] = a.x[i]; lat[off + i] = a.y[i]; rank[off + i] = a.r[i]; }
  arcs.push({ offset: off, count: a.x.length, kind: a.kind, source: a.source, minLod: a.minLod, flags: a.flags || 0 });
  off += a.x.length;
}
const topology = {
  quantum: L.quantum,
  lod: L.lod,
  generated: new Date().toISOString(),
  generator: "folio atlas-build: build-land.js → pack.js (" + require("./package.json").version + ")",
  sources: headerSources(L.sources),
  entities: L.entities,
  steps: L.steps,
  vertices: { lon, lat }, rank,
  arcs,
  faces: L.faces,
  extra: {
    stepYears: L.stepYears,
    tolerances_m: L.tolerances_m,
    sourceVersions: L.versions,
    built: { step: L.step, at: L.generated, stats: L.stats },
  },
};
const bytes = F.write(topology);
const kb = (bytes.length / 1024).toFixed(1), mb = (bytes.length / 1048576).toFixed(3);
console.log(`topology.bin: ${bytes.length} bytes (${kb} KB, ${mb} MB) — ${nV} vertices, ${arcs.length} arcs, ${L.faces.length} faces, ${L.entities.length} entities, ${L.steps.length} steps`);
// where the bytes go, so the budget can be read against its parts
{ const h = F.read(bytes, { headerOnly: true }).header; const parts = Object.entries(h.sections).map(([k, v]) => `${k} ${(v.length / 1024).toFixed(1)} KB`); console.log(`  header ${(JSON.stringify(h).length / 1024).toFixed(1)} KB; ` + parts.join(", ")); }
if (!dry) {
  fs.mkdirSync(path.dirname(OUTFILE), { recursive: true });
  fs.writeFileSync(OUTFILE, bytes);
  console.log(`  wrote ${path.relative(path.join(HERE, "..", ".."), OUTFILE)}`);
}
