#!/usr/bin/env python3
"""What each reflexive verb MEANS, and how to recognise it in a translation.

Two problems share one table.

Wiktionary files a reflexive as a form of its base verb and gives it no meaning
of its own -- `sentarse` is "infinitive of sentar combined with se" -- so the
gloss on the card has to be written here or the card carries no meaning at all.

And a reflexive's FORMS are its base verb's, so a sentence cannot be matched on
the form alone: every `llamarse` example came back as `llamar` "to phone".
Requiring an agreeing clitic fixes most of it, but not where the base verb takes
a dative in the same shape ("me llamará por teléfono") or where two verbs share
a form -- `sentarse` and `sentirse` both make "me siento", which is either "I
sit down" or "I feel".  The aligned English settles it, and the words that do
the settling are the gloss's own.

A reflexive with no entry here still works: it keeps the agreement test and
loses the English one.  `build_deck` and `examples` both say so on every run, so
a level that introduces new reflexives announces them rather than shipping a
card whose meaning reads "infinitive of ... combined with se".
"""

# word: (meaning shown on the card, English words that identify it in a translation)
REFLEXIVES = {
    # A1
    'llamarse':    ('to be called, to be named',        ('name', 'called')),
    'levantarse':  ('to get up, to stand up',           ('get up', 'gets up', 'got up', 'getting up',
                                                         'rise', 'rose', 'stand up', 'stood up')),
    'ducharse':    ('to have a shower, to shower',      ('shower',)),
    'lavarse':     ('to wash (oneself)',                ('wash', 'brush')),
    'bañarse':     ('to have a bath, to bathe',         ('bath', 'swim', 'swam')),
    'despertarse': ('to wake up',                       ('wake', 'woke', 'awake')),
    'dedicarse':   ('to work as, to devote oneself to', ('devote', 'dedicat', 'for a living', 'do you do')),
    # A2
    'quejarse':    ('to complain',                      ('complain',)),
    'irse':        ('to leave, to go away',             ('leave', 'left', 'leaving', 'go away',
                                                         'went away', 'goes away', 'gone')),
    'quedarse':    ('to stay, to remain',               ('stay', 'stayed', 'staying', 'remain')),
    'casarse':     ('to get married',                   ('marry', 'married', 'marriage', 'wedding')),
    'ponerse':     ('to put on (clothes); to become',   ('put on', 'puts on', 'putting on', 'wear',
                                                         'wore', 'became', 'become', 'becomes', 'got')),
    'preocuparse': ('to worry',                         ('worry', 'worried', 'worrying')),
    'sentarse':    ('to sit down',                      ('sit', 'sat', 'seat')),
    'sentirse':    ('to feel (a certain way)',          ('feel', 'felt', 'feeling')),
    'moverse':     ('to move (oneself)',                ('move', 'moved', 'moving')),
    'reunirse':    ('to meet, to gather',               ('meet', 'met', 'meeting', 'gather')),
    'divertirse':  ('to enjoy oneself, to have fun',    ('fun', 'enjoy', 'enjoyed', 'amuse',
                                                         'good time')),
    'encontrarse': ('to meet; to feel; to be located',  ('meet', 'met', 'feel', 'felt',
                                                         'located', 'situated')),
    'acostarse':   ('to go to bed, to lie down',        ('bed', 'lie down', 'lay down', 'lying down')),
    'quitarse':    ('to take off (clothes)',            ('take off', 'takes off', 'took off',
                                                         'taking off', 'remove')),
    'vestirse':    ('to get dressed',                   ('dress', 'dressed', 'dressing')),
    'despedirse':  ('to say goodbye',                   ('goodbye', 'good-bye', 'farewell',
                                                         'see you', 'say bye')),
    'caerse':      ('to fall down, to fall over',       ('fall', 'fell', 'fallen', 'falling')),
    'cambiarse':   ('to change (clothes); to move house', ('change', 'changed', 'changing', 'moved')),
    'separarse':   ('to separate, to split up',         ('separate', 'separated', 'split')),
    'divorciarse': ('to get divorced',                  ('divorce', 'divorced')),
    'parecerse':   ('to look alike, to resemble',       ('look like', 'looks like', 'looked like',
                                                         'resemble', 'alike', 'similar')),
    'afeitarse':   ('to shave',                         ('shave', 'shaved', 'shaving')),
    'enfadarse':   ('to get angry',                     ('angry', 'anger', 'mad at', 'annoyed', 'cross with')),
    'probarse':    ('to try on',                        ('try on', 'tries on', 'tried on', 'trying on')),
    'acordarse':   ('to remember',                      ('remember', 'remembered', 'recall')),
    'alegrarse':   ('to be glad, to cheer up',          ('glad', 'happy', 'pleased', 'cheer', 'delighted')),
    'aburrirse':   ('to get bored',                     ('bored', 'boring', 'boredom')),
    'cansarse':    ('to get tired',                     ('tired', 'tire', 'exhausted', 'worn out')),
    'peinarse':    ('to comb one’s hair',          ('comb', 'hair')),
    'cepillarse':  ('to brush (one’s teeth or hair)', ('brush', 'teeth', 'hair')),
    'apellidarse': ('to have as a surname',             ('surname', 'last name', 'family name')),
    # B1
    'abrazarse':   ('to hug, to embrace',               ('hug', 'hugged', 'hugging', 'embrace', 'embraced')),
    'acercarse':   ('to approach, to come closer',      ('approach', 'approached', 'closer', 'close to',
                                                         'came up', 'come up', 'draw near', 'drew near')),
    'acostumbrarse': ('to get used to',                 ('used to', 'accustomed', 'get used', 'got used')),
    'adaptarse':   ('to adapt, to adjust',              ('adapt', 'adapted', 'adapting', 'adjust', 'adjusted')),
    'alejarse':    ('to move away, to go off',          ('move away', 'moved away', 'go away', 'went away',
                                                         'get away', 'got away', 'walk away', 'walked away',
                                                         'further away')),
    'arrepentirse': ('to regret, to repent',            ('regret', 'regretted', 'repent', 'repented', 'sorry')),
    'atreverse':   ('to dare',                          ('dare', 'dares', 'dared', 'daring')),
    'bajarse':     ('to get off, to get out; to go down', ('get off', 'got off', 'get out', 'got out',
                                                           'get down', 'got down', 'go down', 'went down',
                                                           'come down', 'came down', 'download')),
    'besarse':     ('to kiss (each other)',             ('kiss', 'kissed', 'kissing')),
    'comprometerse': ('to commit oneself; to get engaged', ('commit', 'committed', 'promise', 'promised',
                                                            'engaged', 'pledge', 'pledged')),
    'comunicarse': ('to communicate; to get in touch',  ('communicate', 'communicated', 'communicating',
                                                         'in touch', 'contact', 'contacted')),
    'conectarse':  ('to connect, to go online',         ('connect', 'connected', 'connecting', 'log on',
                                                         'logged on', 'online', 'internet')),
    'cortarse':    ('to cut oneself; to get cut off',   ('cut', 'cuts', 'cutting')),
    'darse':       ('to give oneself; darse cuenta, to realize', ('realize', 'realise', 'realized',
                                                                  'realised', 'notice', 'noticed',
                                                                  'give up', 'gave up', 'given up')),
    'deprimirse':  ('to get depressed',                 ('depressed', 'depressing', 'depression')),
    'descargarse': ('to be downloaded; to run down',    ('download', 'downloaded', 'discharge',
                                                         'discharged', 'run down', 'ran down', 'battery')),
    'echarse':     ('to lie down; to throw oneself',    ('lie down', 'lay down', 'lying down', 'threw',
                                                         'throw', 'thrown')),
    'enamorarse':  ('to fall in love',                  ('in love', 'fall in love', 'fell in love',
                                                         'falling in love', 'love with')),
    'enterarse':   ('to find out, to hear about',       ('find out', 'found out', 'finds out',
                                                         'hear about', 'heard about', 'hear of',
                                                         'heard of', 'know about', 'knew about')),
    'equivocarse': ('to be wrong, to make a mistake',   ('wrong', 'mistake', 'mistaken', 'mistakes',
                                                         'error', 'wrongly')),
    'esforzarse':  ('to make an effort, to try hard',   ('effort', 'try hard', 'tried hard', 'strive',
                                                         'strove', 'striving', 'hard to')),
    'evaporarse':  ('to evaporate',                     ('evaporate', 'evaporated', 'evaporating',
                                                         'evaporation')),
    'fijarse':     ('to notice, to pay attention',      ('notice', 'noticed', 'pay attention',
                                                         'paid attention', 'look at', 'looked at')),
    'hacerse':     ('to become, to turn into',          ('become', 'became', 'becomes', 'becoming',
                                                         'turn into', 'turned into', 'pretend',
                                                         'pretended')),
    'inscribirse': ('to sign up, to enrol',             ('sign up', 'signed up', 'signs up', 'enrol',
                                                         'enroll', 'enrolled', 'register', 'registered')),
    'jubilarse':   ('to retire',                        ('retire', 'retired', 'retires', 'retirement',
                                                         'retiring')),
    'llevarse':    ('to take away; to get on with someone', ('take', 'took', 'taken', 'taking',
                                                             'get along', 'got along', 'get on with',
                                                             'got on with')),
    'mantenerse':  ('to keep, to stay (in a state)',    ('keep', 'kept', 'stay', 'stayed', 'staying',
                                                         'remain', 'remained', 'maintain', 'maintained')),
    'marcharse':   ('to leave, to go away',             ('leave', 'left', 'leaving', 'leaves',
                                                         'go away', 'went away', 'set off')),
    'matricularse': ('to enrol, to register for a course', ('enrol', 'enroll', 'enrolled', 'register',
                                                            'registered', 'sign up', 'signed up')),
    'mudarse':     ('to move house',                    ('move', 'moved', 'moving', 'moves',
                                                         'relocate', 'relocated')),
    'nublarse':    ('to cloud over',                    ('cloud', 'clouds', 'clouded', 'cloudy',
                                                         'overcast')),
    'pintarse':    ('to put on make-up',                ('make-up', 'makeup', 'make up', 'lipstick',
                                                         'paint', 'painted')),
    'portarse':    ('to behave',                        ('behave', 'behaved', 'behaves', 'behaving',
                                                         'behaviour', 'behavior')),
    'quemarse':    ('to get burnt, to burn oneself',    ('burn', 'burnt', 'burned', 'burning',
                                                         'sunburn', 'sunburnt')),
    'romperse':    ('to break, to get broken',          ('break', 'broke', 'broken', 'breaking',
                                                         'breaks', 'tear', 'torn')),
    'secarse':     ('to dry, to dry oneself',           ('dry', 'dried', 'dries', 'drying')),
    # B2
    'abstenerse':  ('to abstain, to refrain',           ('abstain', 'abstained', 'refrain', 'refrained')),
    'acabarse':    ('to run out, to come to an end',    ('run out', 'ran out', 'runs out', 'used up',
                                                         'come to an end', 'came to an end', 'over')),
    'agacharse':   ('to bend down, to crouch',          ('bend down', 'bent down', 'crouch', 'crouched',
                                                         'duck', 'ducked', 'stoop')),
    'agotarse':    ('to run out, to sell out',          ('run out', 'ran out', 'sold out', 'sell out',
                                                         'exhausted', 'worn out')),
    'alojarse':    ('to stay, to be lodged',            ('stay', 'stayed', 'staying', 'lodge', 'lodged',
                                                         'accommodat', 'put up at')),
    'alzarse':     ('to rise, to rise up',              ('rise', 'rose', 'risen', 'rising', 'stand up',
                                                         'stood up', 'revolt', 'rebel')),
    'apagarse':    ('to go out, to switch itself off',  ('go out', 'went out', 'goes out', 'turn off',
                                                         'turned off', 'switch off', 'switched off',
                                                         'die out', 'died out')),
    'aproximarse': ('to approach, to draw near',        ('approach', 'approached', 'draw near',
                                                         'drew near', 'get close', 'got close', 'closer')),
    'apuntarse':   ('to sign up, to put one’s name down', ('sign up', 'signed up', 'signs up', 'join',
                                                           'joined', 'enrol', 'enroll', 'put my name')),
    'apurarse':    ('to hurry; to worry',               ('hurry', 'hurried', 'rush', 'rushed', 'worry',
                                                         'worried')),
    'asustarse':   ('to get frightened',                ('scared', 'frightened', 'afraid', 'startled',
                                                         'fright')),
    'avergonzarse': ('to be ashamed',                   ('ashamed', 'shame', 'embarrassed', 'embarrass')),
    'averiarse':   ('to break down (a machine)',        ('break down', 'broke down', 'broken down',
                                                         'breakdown', 'out of order')),
    'basarse':     ('to be based on',                   ('based on', 'base', 'bases', 'basis')),
    'caracterizarse': ('to be characterized by',        ('characteriz', 'characteris', 'feature',
                                                         'features', 'known for')),
    'clasificarse': ('to qualify; to be classified',    ('qualify', 'qualified', 'qualifies', 'classif',
                                                         'rank', 'ranked')),
    'componerse':  ('to be made up of, to consist of',  ('made up of', 'consist', 'consists', 'consisted',
                                                         'composed of', 'comprise')),
    'comportarse': ('to behave',                        ('behave', 'behaved', 'behaves', 'behaving',
                                                         'behaviour', 'behavior')),
    'confesarse':  ('to confess, to go to confession',  ('confess', 'confessed', 'confession')),
    'confundirse': ('to make a mistake, to get mixed up', ('mistake', 'mistaken', 'confused', 'confuse',
                                                           'mix up', 'mixed up', 'wrong')),
    'congelarse':  ('to freeze',                        ('freeze', 'froze', 'frozen', 'freezing')),
    'conservarse': ('to keep, to be preserved',         ('keep', 'kept', 'preserve', 'preserved',
                                                         'last', 'lasted')),
    'convertirse': ('to become, to turn into',          ('become', 'became', 'becomes', 'becoming',
                                                         'turn into', 'turned into', 'convert',
                                                         'converted')),
    'creerse':     ('to believe; to think oneself',     ('believe', 'believed', 'believes', 'fall for',
                                                         'fell for', 'thinks he', 'thinks she')),
    'cuidarse':    ('to look after oneself',            ('take care', 'takes care', 'took care',
                                                         'look after', 'looked after', 'careful')),
    'disfrazarse': ('to dress up, to disguise oneself', ('dress up', 'dressed up', 'disguise',
                                                         'disguised', 'costume')),
    'doctorarse':  ('to get a doctorate',               ('doctorate', 'phd', 'ph.d', 'doctoral')),
    'educarse':    ('to be educated, to be brought up', ('educat', 'brought up', 'raised', 'upbringing')),
    'emborracharse': ('to get drunk',                   ('drunk', 'drink', 'drank', 'drinking',
                                                         'intoxicated')),
    'enfrentarse': ('to face, to confront',             ('face', 'faced', 'faces', 'facing', 'confront',
                                                         'confronted', 'stand up to', 'took on')),
    'enredarse':   ('to get tangled up; to get involved', ('tangle', 'tangled', 'get involved',
                                                           'got involved', 'mess')),
    'entretenerse': ('to amuse oneself; to linger',     ('amuse', 'amused', 'entertain', 'entertained',
                                                         'pass the time', 'linger', 'dawdle')),
    'estresarse':  ('to get stressed',                  ('stress', 'stressed', 'stressful')),
    'estropearse': ('to break, to go off',              ('break', 'broke', 'broken', 'spoil', 'spoiled',
                                                         'spoilt', 'go off', 'went off', 'ruined')),
    'examinarse':  ('to sit an exam',                   ('exam', 'examination', 'test', 'sit the',
                                                         'take the exam', 'took the exam')),
    'exponerse':   ('to expose oneself, to run a risk', ('expose', 'exposed', 'exposing', 'risk',
                                                         'risked')),
    'formarse':    ('to train; to form',                ('train', 'trained', 'training', 'form',
                                                         'formed', 'forms')),
    'gastarse':    ('to spend; to wear out',            ('spend', 'spent', 'spends', 'wear out',
                                                         'worn out', 'used up')),
    'hallarse':    ('to be, to find oneself somewhere', ('found', 'locat', 'situated', 'lies', 'lay')),
    'ilusionarse': ('to get one’s hopes up, to get excited', ('hopes up', 'excited', 'excitement',
                                                              'looking forward', 'thrilled')),
    'imaginarse':  ('to imagine',                       ('imagine', 'imagined', 'imagines', 'imagining',
                                                         'picture')),
    'incorporarse': ('to sit up; to join (a post)',     ('sit up', 'sat up', 'join', 'joined', 'joins',
                                                         'start work', 'started work')),
    'inventarse':  ('to make up, to invent',            ('make up', 'made up', 'makes up', 'invent',
                                                         'invented', 'made-up')),
    'licenciarse': ('to graduate with a degree',        ('graduate', 'graduated', 'degree')),
    'limarse':     ('to file (one’s nails)',            ('file', 'filed', 'filing', 'nails')),
    'llenarse':    ('to fill up, to get full',          ('fill', 'filled', 'fills', 'filling', 'full',
                                                         'crowded')),
    'maquillarse': ('to put on make-up',                ('make-up', 'makeup', 'make up', 'cosmetics',
                                                         'lipstick')),
    'marearse':    ('to get dizzy, to feel sick',       ('dizzy', 'dizziness', 'sick', 'seasick',
                                                         'nauseous', 'faint')),
    'pelearse':    ('to fight, to have a row',          ('fight', 'fought', 'fighting', 'fights',
                                                         'quarrel', 'argue', 'argued', 'row')),
    'perderse':    ('to get lost; to miss something',   ('lost', 'lose', 'loses', 'losing', 'miss',
                                                         'missed', 'misses')),
    'pesarse':     ('to weigh oneself',                 ('weigh', 'weighed', 'weighs', 'weighing',
                                                         'scales')),
    'preguntarse': ('to wonder',                        ('wonder', 'wondered', 'wonders', 'wondering',
                                                         'ask myself', 'asked myself')),
    'presentarse': ('to introduce oneself; to turn up', ('introduce', 'introduced', 'turn up', 'turned up',
                                                         'show up', 'showed up', 'appear', 'appeared',
                                                         'run for', 'stood for')),
    'producirse':  ('to happen, to take place',         ('happen', 'happened', 'happens', 'take place',
                                                         'took place', 'occur', 'occurred')),
    'protegerse':  ('to protect oneself',               ('protect', 'protected', 'protects', 'protection',
                                                         'shelter')),
    'pudrirse':    ('to rot',                           ('rot', 'rots', 'rotted', 'rotten', 'decay',
                                                         'decayed')),
    'rascarse':    ('to scratch oneself',               ('scratch', 'scratched', 'scratching',
                                                         'scratches')),
    'recogerse':   ('to tie back one’s hair; to turn in', ('tie back', 'tied back', 'put up', 'hair',
                                                           'turn in', 'retire')),
    'recortarse':  ('to trim; to stand out against',    ('trim', 'trimmed', 'cut', 'cuts', 'silhouett',
                                                         'outline')),
    'registrarse': ('to register, to check in',         ('register', 'registered', 'registration',
                                                         'check in', 'checked in', 'sign up',
                                                         'signed up')),
    'relacionarse': ('to mix with people; to be related', ('socializ', 'socialis', 'mix with',
                                                           'mixed with', 'interact', 'relate',
                                                           'related', 'get along')),
    'resignarse':  ('to resign oneself',                ('resign', 'resigned', 'accept', 'accepted',
                                                         'put up with')),
    'retirarse':   ('to withdraw; to retire',           ('withdraw', 'withdrew', 'withdrawn', 'retire',
                                                         'retired', 'retreat', 'retreated', 'pull out')),
    'retrasarse':  ('to be late, to be delayed',        ('late', 'delay', 'delayed', 'behind schedule',
                                                         'running late')),
    'salirse':     ('to come off, to get out; to leak', ('come off', 'came off', 'get out', 'got out',
                                                         'leave', 'left', 'leak', 'leaked')),
    'saltarse':    ('to skip, to jump (a rule, a queue)', ('skip', 'skipped', 'skips', 'jump', 'jumped',
                                                           'ran a red', 'miss', 'missed')),
    'sorprenderse': ('to be surprised',                 ('surprise', 'surprised', 'surprising',
                                                         'astonish', 'astonished', 'amazed')),
    'suscribirse': ('to subscribe',                     ('subscribe', 'subscribed', 'subscription')),
    'tirarse':     ('to throw oneself, to dive',        ('throw', 'threw', 'thrown', 'dive', 'dove',
                                                         'dived', 'jump', 'jumped')),
    'titularse':   ('to be entitled; to graduate',      ('titled', 'entitled', 'called', 'graduate',
                                                         'graduated', 'degree')),
    'torcerse':    ('to twist (an ankle); to go wrong', ('twist', 'twisted', 'sprain', 'sprained',
                                                         'ankle', 'go wrong', 'went wrong')),
    'trasladarse': ('to move, to relocate',             ('move', 'moved', 'moving', 'moves', 'relocate',
                                                         'relocated', 'transfer', 'transferred')),
    'tumbarse':    ('to lie down',                      ('lie down', 'lay down', 'lying down',
                                                         'stretch out')),
    'vacunarse':   ('to get vaccinated',                ('vaccinat', 'vaccine', 'jab', 'immunis',
                                                         'immuniz', 'shot')),
    'volverse':    ('to become; to turn round',         ('become', 'became', 'becomes', 'turn around',
                                                         'turned around', 'turn round', 'turned round',
                                                         'go crazy', 'went crazy')),
}

GLOSS = {k: [v[0]] for k, v in REFLEXIVES.items()}
KEYWORDS = {k: v[1] for k, v in REFLEXIVES.items()}


def report_missing(words, where):
    """Name any reflexive this table does not cover, on every run."""
    miss = [w for w in words
            if w.endswith(('arse', 'erse', 'irse')) and w not in REFLEXIVES]
    if miss:
        print(f'    !! {where}: {len(miss)} reflexive(s) with no authored entry '
              f'-- they lose the English check and their meaning: {", ".join(sorted(miss))}')
    return miss
