/* lib/twin.js — the `.js` twin of a `.bin` data file, for file:// (Phase 1d; docs/atlas-v2-design.md §2.9, Q-R4 a).

   A browser opening index.html from a file will run a <script> but refuses fetch() of a local binary and refuses a
   Worker, so the two files the globe cannot do without — atlas/data/topology.bin and water.bin — get a twin beside
   them: the same bytes as base64 in a script that assigns window.ATLAS_TWIN["<name>"] = { bytes, sha256, b64 }, with
   the `sources` header §2.10a asks of every generated file as its first line (the same block the .bin carries). The
   browser decodes it with fetch("data:…;base64,…") — off the main thread — and feeds the main-thread shim exactly as
   it would the worker. The twin is written by pack.js / pack-water.js at --install (and alone with --twin, from the
   committed .bin), and check-topology.js / check-water.js decode it and refuse a twin whose sha256 is not the .bin's.

     const T = require("./lib/twin.js");
     T.writeTwin("atlas/data/topology.bin")   → { bytes, sha256, twinBytes, file }
     T.checkTwin("atlas/data/topology.bin")   → { ok, reason, bytes, twinBytes, sha256, twinSha }
*/
"use strict";
const fs = require("fs"), path = require("path"), crypto = require("crypto");
const F = require("./format.js");
const sha256 = (b) => crypto.createHash("sha256").update(b).digest("hex");
const twinPath = (binPath) => binPath + ".js";

function twinText(bytes, name, sources) {
  return "/* sources: " + JSON.stringify(sources || []) + " */\n" +
    `/* atlas/data/${name}.js — GENERATED by .claude/atlas-build/lib/twin.js: the bytes of atlas/data/${name}, base64, for a browser that\n` +
    "   opened Folio from a file and cannot fetch() a binary (docs/atlas-v2-design.md §2.9). The same header, the same sha256; the\n" +
    "   checker decodes it and compares. Do not edit: rebuild. */\n" +
    "window.ATLAS_TWIN = window.ATLAS_TWIN || {};\n" +
    `window.ATLAS_TWIN[${JSON.stringify(name)}] = { bytes: ${bytes.length}, sha256: ${JSON.stringify(sha256(bytes))}, b64: "` + Buffer.from(bytes).toString("base64") + "\" };\n";
}
function writeTwin(binPath) {
  const bytes = fs.readFileSync(binPath);
  const h = F.read(new Uint8Array(bytes), { headerOnly: true }).header;
  const text = twinText(bytes, path.basename(binPath), h.sources);
  fs.writeFileSync(twinPath(binPath), text);
  return { file: twinPath(binPath), bytes: bytes.length, sha256: sha256(bytes), twinBytes: Buffer.byteLength(text) };
}
function checkTwin(binPath) {
  const file = twinPath(binPath);
  if (!fs.existsSync(file)) return { ok: false, reason: "no twin at " + file };
  const bytes = fs.readFileSync(binPath), text = fs.readFileSync(file, "utf8");
  const first = text.split("\n")[0];
  const hm = /^\/\* sources: (\[.*\]) \*\/$/.exec(first);
  if (!hm) return { ok: false, reason: "the twin's first line is not a sources header" };
  const h = F.read(new Uint8Array(bytes), { headerOnly: true }).header;
  if (JSON.stringify(JSON.parse(hm[1])) !== JSON.stringify(h.sources || [])) return { ok: false, reason: "the twin's sources header differs from the .bin's" };
  const m = /b64: "([A-Za-z0-9+/=]*)" \};\n$/.exec(text);
  if (!m) return { ok: false, reason: "no base64 payload" };
  const decoded = Buffer.from(m[1], "base64");
  const want = sha256(bytes), got = sha256(decoded);
  const declared = /sha256: "([0-9a-f]{64})"/.exec(text);
  if (!declared || declared[1] !== want) return { ok: false, reason: "the twin declares another sha256", sha256: want, twinSha: declared && declared[1] };
  return { ok: got === want, reason: got === want ? "identical" : "decoded bytes differ", bytes: bytes.length, twinBytes: Buffer.byteLength(text), sha256: want, twinSha: got };
}
module.exports = { twinText, writeTwin, checkTwin, twinPath, sha256 };
