#!/usr/bin/env node
/* build-fronts.js — the Second World War's FRONTS in Europe, month by month, for the personal atlas.

     node .claude/build-fronts.js <ww2-atlas/data/territory/control> [--dry]

   WHY (Oct 2026, on request: "Add front line border maps for World War 2 if that's the only one you can
   find"). The Second World War card GROUPS other war cards (`war.group`), so it is not shaded as two sides
   on the atlas; what it gets instead is who held what, month by month — Axis, Axis-occupied, Allied,
   Allied-occupied — and the line where the two meet is the front.

   SOURCE AND LICENCE — PUBLIC DOMAIN, and checked at both ends. The polygons are the `data/territory/control`
   files of ww2-atlas (https://github.com/tanimutomo/ww2-atlas), whose data/LICENSE lists them as public
   domain: they are a machine conversion of the Wikimedia Commons series "Second World War Europe MM YYYY
   de.svg" by the user San Jose, each file tagged PD-self on Commons (checked 2026-10-01), which cites the
   German army's situation maps, the West Point history department and Wikipedia. Fetch the folder from that
   repository (raw.githubusercontent.com works where github.com does not) and pass its path; never commit it.
   Open and free sources only — see docs/atlas-borders-audit.md §3.

   WHAT IT COVERS, AND WHAT IT DOES NOT — the source's own limits, stated where a reader of the code meets
   them: EUROPE ONLY, monthly from August 1939 to December 1942, each map the approximate situation at the
   END of its month (not a daily front). North Africa is essentially absent; 1943–45 is not in this source
   at all (the public-domain US Army "Atlas of the World Battle Fronts", fortnightly from July 1943, is the
   next source and has to be georeferenced from scans — see the audit's ledger); Asia and the Pacific are
   not covered. Neutral countries carry no polygon.

   OUTPUT: `fronts.js`, a lazy bundle (`DATA_BUNDLES.fronts`):
     window.WW2_FRONTS = { card: "ww2-001", m: { "1941-12": [axis, axisOccupied, allied, alliedOccupied], … } }
   each entry a list of rings, outer rings only, Douglas–Peucker at TOL° and rounded to 0.01°.

   Zero dependencies. Not part of the site. */
"use strict";
const fs = require("fs"), path = require("path");
const ROOT = path.join(__dirname, "..");
const OUT = path.join(ROOT, "fronts.js");
const TOL = 0.02;
const args = process.argv.slice(2);
const DRY = args.includes("--dry");
const dir = args.find((a) => !a.startsWith("--"));
if (!dir || !fs.existsSync(path.join(dir, "index.json"))) { console.error("usage: node .claude/build-fronts.js <ww2-atlas/data/territory/control> [--dry]"); process.exit(1); }

function dp(pts, tol) {
  if (pts.length < 3) return pts.slice();
  const keep = new Uint8Array(pts.length); keep[0] = keep[pts.length - 1] = 1;
  const st = [[0, pts.length - 1]], t2 = tol * tol;
  while (st.length) {
    const [a, b] = st.pop(), ax = pts[a][0], ay = pts[a][1], dx = pts[b][0] - ax, dy = pts[b][1] - ay, L = dx * dx + dy * dy;
    let best = -1, bd = t2;
    for (let i = a + 1; i < b; i++) {
      let px = pts[i][0] - ax, py = pts[i][1] - ay;
      if (L) { const t = Math.max(0, Math.min(1, (px * dx + py * dy) / L)); px -= t * dx; py -= t * dy; }
      const d = px * px + py * py; if (d > bd) { bd = d; best = i; }
    }
    if (best >= 0) { keep[best] = 1; st.push([a, best], [best, b]); }
  }
  return pts.filter((p, i) => keep[i]);
}
function ring(r) {
  let p = r.map((q) => [Number(q[0]), Number(q[1])]);
  if (p.length > 1 && p[0][0] === p[p.length - 1][0] && p[0][1] === p[p.length - 1][1]) p.pop();
  if (p.length < 3) return null;
  p = dp(p.concat([p[0]]), TOL).slice(0, -1).map((q) => [Math.round(q[0] * 100) / 100, Math.round(q[1] * 100) / 100]);
  p = p.filter((q, i) => i === 0 || q[0] !== p[i - 1][0] || q[1] !== p[i - 1][1]);
  return p.length >= 3 ? p : null;
}
const ORDER = ["axis", "axis_occupied", "allied", "allied_occupied"];
const idx = JSON.parse(fs.readFileSync(path.join(dir, "index.json"), "utf8"));
const m = {};
let pts = 0;
for (const e of idx.months) {
  const fc = JSON.parse(fs.readFileSync(path.join(dir, e.file), "utf8"));
  const sets = ORDER.map(() => []);
  for (const f of fc.features) {
    const k = ORDER.indexOf(f.properties.control);
    if (k < 0) { console.error("unknown control value " + f.properties.control + " in " + e.file); process.exit(1); }
    const polys = f.geometry.type === "MultiPolygon" ? f.geometry.coordinates : [f.geometry.coordinates];
    for (const poly of polys) { const r = ring(poly[0]); if (r) { sets[k].push(r); pts += r.length; } }
  }
  if (!/^\d{4}-\d{2}$/.test(e.month)) { console.error("bad month " + e.month); process.exit(1); }
  m[e.month] = sets;
}
const months = Object.keys(m).sort();
const head = `/* fronts.js — GENERATED by .claude/build-fronts.js. Do not edit.
   The Second World War in EUROPE, month by month (${months[0]} … ${months[months.length - 1]}): for each month, the
   ground held by the Axis, occupied by the Axis, held by the Allies and occupied by the Allies, at the END
   of that month — the approximate situation, not a daily front. North Africa, Asia and 1943–45 are not in
   this source. SOURCE: Wikimedia Commons, "Second World War Europe MM YYYY de.svg" by San Jose (public
   domain, PD-self), vectorised by ww2-atlas (https://github.com/tanimutomo/ww2-atlas, data/territory/control,
   public domain). CHANGES MADE: outer rings only, simplified (Douglas–Peucker, ${TOL}°), rounded to 0.01°. */
`;
const body = head + "window.WW2_FRONTS = { card: \"ww2-001\", m: {\n" + months.map((k) => "  " + JSON.stringify(k) + ": " + JSON.stringify(m[k])).join(",\n") + "\n} };\n";
console.log(months.length + " months, " + pts + " points, " + (body.length / 1024).toFixed(0) + " KB");
if (DRY) process.exit(0);
fs.writeFileSync(OUT, body);
console.log("wrote fronts.js");
