#!/usr/bin/env python3
"""Regenerate .claude/fsrs-vectors.json — the reference vectors test-scheduler.js checks Folio's FSRS against.

WHY A FIXTURE RATHER THAN A READING OF THE MATHS. FSRS-6 is somebody else's algorithm, and an
implementation reconstructed from prose is exactly the thing that looks right and quietly schedules every
reader worse — the one failure a study site cannot afford. So Folio's arithmetic is compared against numbers
produced by the reference implementation itself, and the comparison is committed so it runs on every change
without needing Python or a network.

    python3 -m venv /tmp/fsrsenv && /tmp/fsrsenv/bin/pip install fsrs
    /tmp/fsrsenv/bin/python .claude/gen-fsrs-vectors.py > .claude/fsrs-vectors.json

`fsrs` is a DEV dependency and must not enter the repo (the zero-dependency rule) — install it in a scratch
venv, as Playwright is. Re-run this only when the reference or the default parameters actually move, and say
so in the commit: if test-scheduler.js section 10 fails after an app.js change, app.js is wrong, not this.

Fuzzing is off and every timestamp is fixed, so the output is deterministic and a regenerated file should be
byte-identical unless something real has changed.
"""
import json, itertools
from datetime import datetime, timedelta, timezone
from fsrs import Scheduler, Card, Rating, State
from fsrs.scheduler import LOWER_BOUNDS_PARAMETERS, UPPER_BOUNDS_PARAMETERS

try:                                    # which reference produced the file — the one thing that dates it
    from importlib.metadata import version
    REF = "py-fsrs " + version("fsrs")
except Exception:
    REF = "py-fsrs (version unknown)"

W = list(Scheduler().parameters)
# `ref` is recorded so "regenerate only when the reference moves" has something to compare against: a
# fixture with no provenance cannot tell a deliberate version bump from a fixture edited to fit a bug.
out = {"ref": REF, "params": W, "cases": [], "curve": [], "intervals": []}

# --- the pure pieces, sampled over a wide grid
sch = Scheduler(enable_fuzzing=False)
for s in [0.001, 0.5, 1, 3, 21, 100, 365, 3650]:
    for el in [0, 1, 2, 7, 30, 365]:
        c = Card(); c.stability = s; c.difficulty = 5.0
        c.last_review = datetime(2026, 1, 1, tzinfo=timezone.utc)
        out["curve"].append({"s": s, "elapsed": el,
                             "r": (1 + sch._FACTOR * el / s) ** sch._DECAY})
for s in [0.4, 1, 5, 40, 400, 4000]:
    for r in [0.7, 0.8, 0.9, 0.95, 0.98]:
        sc = Scheduler(enable_fuzzing=False, desired_retention=r)
        out["intervals"].append({"s": s, "retention": r, "days": sc._next_interval(stability=s)})

# --- the state machine, driven exactly as Folio drives it
T0 = datetime(2026, 3, 1, 9, 0, 0, tzinfo=timezone.utc)
RAT = {"again": Rating.Again, "hard": Rating.Hard, "good": Rating.Good, "easy": Rating.Easy}
def snap(c):
    return {"state": c.state.name, "step": c.step, "stability": c.stability,
            "difficulty": c.difficulty,
            "due_min": None if c.due is None else round((c.due - c.last_review).total_seconds() / 60, 6)}

# Every sequence of up to 4 grades, with a realistic gap between reviews.
#
# THE FRACTIONAL GAPS ARE NOT DECORATION. The reference measures the delay between two reviews in WHOLE
# days (`(a - b).days`, which floors), both for the forgetting curve and for the same-day test — so a card
# answered 1.46 days later is scored at ONE day, not 1.46. Every gap here was a multiple of a day until
# Aug 2026, which is exactly why Folio's own fractional reading of the same delay went unnoticed: the two
# conventions agree on every whole-day gap and on nothing else.
for seq in itertools.product(["again", "hard", "good", "easy"], repeat=3):
    for gap_min in [0, 30, 1440, 1440 * 9, 2100, 1440 * 3 + 700]:
        sch = Scheduler(enable_fuzzing=False)
        c = Card()
        t = T0
        steps = []
        for g in seq:
            c, _ = sch.review_card(c, RAT[g], t)
            steps.append({"grade": g, **snap(c)})
            t = t + timedelta(minutes=gap_min if gap_min else 1)
        out["cases"].append({"seq": list(seq), "gap_min": gap_min, "steps": steps})

# --- THE OPTIMISER'S LOSS, on a dataset the reference scores for us
#
# The optimiser's own OUTPUT cannot be compared against the reference — it is Adam over a torch graph
# against Adam over numerical gradients, and two gradient descents do not land on the same 21 numbers. What
# CAN be compared, and is the thing that must be right, is the LOSS being descended: get that wrong and the
# optimiser confidently walks a reader's schedule somewhere worse. So a synthetic review history is built
# here and scored by the reference's own `Optimizer._compute_batch_loss` at two parameter sets.
#
# The history is generated by SCHEDULING it — cards are reviewed at the interval FSRS itself asks for, with
# a seeded coin-flip for the grade — so the sequences look like a reader's rather than like a grid.
from fsrs.optimizer import Optimizer
from fsrs.review_log import ReviewLog
import random

rng = random.Random(7)
logs = []
T1 = datetime(2026, 1, 1, 8, 0, 0, tzinfo=timezone.utc)
gen = Scheduler(enable_fuzzing=False)
for card_i in range(60):
    c = Card()
    t = T1 + timedelta(days=card_i % 7, minutes=card_i * 13)
    for _ in range(rng.randint(2, 9)):
        # a reader who mostly remembers: Again 15%, Hard 20%, Good 55%, Easy 10%
        r = rng.random()
        rating = Rating.Again if r < 0.15 else Rating.Hard if r < 0.35 else Rating.Good if r < 0.90 else Rating.Easy
        c, log = gen.review_card(c, rating, t)
        logs.append(log)
        t = c.due
opt = Optimizer(logs)
PERTURBED = [round(x * 1.11 + 0.01, 6) for x in W]
out["loss"] = {
    "reviews": [{"card": rl.card_id, "t": rl.review_datetime.isoformat(), "g": int(rl.rating)} for rl in logs],
    "default": opt._compute_batch_loss(parameters=W),
    "perturbed_params": PERTURBED,
    "perturbed": opt._compute_batch_loss(parameters=PERTURBED),
}
out["bounds"] = {"lower": list(LOWER_BOUNDS_PARAMETERS), "upper": list(UPPER_BOUNDS_PARAMETERS)}
print(json.dumps(out))
